### PR TITLE
Add Rate us Implementation

### LINKED ISSUE #3912: Feat: Rate us
### Describe the feature

I want to integrate the rate us frontend with backend so that users rating the platform have their ratings stored along with their data in the database.

### Add ScreenShots

Screenshot 2024-10-23 120036

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

## fixes #3912 

# Description

This PR adds the rate us backend so that users submitting their ratings , get their data stored in the database.
created ratings models, rotues and controllers for the purpose.

issue #3912

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-10-25 235140
Screenshot 2024-10-25 235532

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
i am not getting the alert message , after submitting .

**Comment by haseebzaki-07** [comment]
Maybe it is because of the localhost URL that is called, because it working very fine on my end.
Screenshot 2024-10-26 111809

https://github.com/user-attachments/assets/a2432688-9603-49cc-8249-45d8637c1595

**Comment by sailaja-adapa** [comment]
@haseebzaki-07 implement this one in another way since u r saying it is url based

**Comment by haseebzaki-07** [comment]
hey @sailaja-adapa please check

**Comment by haseebzaki-07** [comment]
hey @sailaja-adapa @abhi03ruchi please review

**Comment by sailaja-adapa** [comment]
work with updated branch @haseebzaki-07  once view deployment preview

**Pull request closed without merging**
