### PR TITLE
Bug : missing **github**  icon issue resolved

### PR DESCRIPTION
**Pull request by GAVINESHWAR**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.)
issue : #1943 

# Description
The github icon is missing the footer section of main page , that issue has been resolved.

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

issue : #1943 
# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Before:
Screenshot 2024-06-17 144256

After:

image

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by GAVINESHWAR** [comment]
@anuragverma108 and @RishabhDhawad you merged my changes but didn't add any labels like bug, gssoc, level. So I request you to  add those labels to the PR to get points for my contribution from gssoc 24. 
Thank you

**Comment by RitiChandak** [comment]
@GAVINESHWAR Done! Apologies for the delay.

**Comment by GAVINESHWAR** [comment]
> @GAVINESHWAR Done! Apologies for the delay.

Could you please add level as well sir, so that I can get points sir .

Thank you

**Comment by RitiChandak** [comment]
Due to basic changes, I am unable to assign a level.

**Pull request merged**
