### PR TITLE
Fixed broken redirect links

### PR DESCRIPTION
**Pull request by ThisIsSahaj**
# Related Issue 

Fixes:  #1189 

# Description

I have fixed all the broken re-direct links in the project, it included the links of navbar & footer of all the different pages.
(Below I have added only 1 such example)

# Type of PR

- [x] Bug fix

# Screenshots / videos (if applicable)

https://github.com/anuragverma108/SwapReads/assets/118066299/fb8e6366-8dab-4cf2-bd43-3bff829e6873

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by huamanraj** [comment]
resolve conflicts

**Comment by anuragverma108** [comment]
image
Conflicting files
assets/html/book_recommend.html
assets/html/booklistswap.html


Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by ThisIsSahaj** [comment]
> image Conflicting files assets/html/book_recommend.html assets/html/booklistswap.html
> 
> Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review. Thank you!

I have already resolved the conflicts @anuragverma108

**Comment by anuragverma108** [comment]
@ThisIsSahaj Open a new PR

**Comment by ThisIsSahaj** [comment]
> @ThisIsSahaj Open a new PR

Done at #1620 @anuragverma108

**Pull request closed without merging**
