### PR TITLE
commit by Chelseasingla1 in index.html #74 

### PR DESCRIPTION
**Pull request by Chelseasingla1**
I added Stripe Checkout feature.
To execute this you need to go to https://docs.stripe.com/keys this link for generating API keys , and create a new payment link from here https://dashboard.stripe.com/test/payment-links/create

Screenshot 2024-05-11 113734

This is how it is looking:
Screenshot 2024-05-11 113609

To test it after adding keys:
[https://youtu.be/KsxnOPHfbYo](url)
Follow this link

### CODE REVIEW

**Comment by Chelseasingla1** [comment]
This is currently in test mode you need to add bank details for official transactions

**Comment by Chelseasingla1** [comment]
#74

**Comment by anuragverma108** [comment]
image
Solve this conflicting issue and raise PR again.
Also the YT link which you have given is not working.

**Comment by Chelseasingla1** [comment]
> image Solve this conflicting issue and raise PR again. Also the YT link which you have given is not working.

@anuragverma108 okay will do that but are you able to figure out stripe checkout system is that okay?

**Pull request closed without merging**
