### PR TITLE
added pre loader to swapreads

### PR DESCRIPTION
**Pull request by SanikaBhalerao1345**
# Related Issue

none

Fixes:  #3745 
# Description

added a pre-loader 

#3745 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
NA

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by SanikaBhalerao1345** [comment]
@abhi03ruchi pls check my pr

**Comment by abhi03ruchi** [comment]
the preloader doesnt match the ui of the website.

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/734fe9a6-b17c-472f-9eba-1828b3018727

can u add a preloader like this one ?

**Comment by SanikaBhalerao1345** [comment]
@abhi03ruchi okk

**Pull request closed without merging**
