### PR TITLE
Enhancing the Navbar !!

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4368

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
# BEFORE:
image

# AFTER:
image

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
why have u deleted script code of about us page ?

**Comment by abhi03ruchi** [comment]
the intriguing-mysteries navbar still has issue . 

#4322 is already working for enhancing the literary realms section .

**Comment by abhi03ruchi** [comment]
also plz mention properly what have u done and what pages have u modified .

**Comment by abhi03ruchi** [comment]
create another pr .

**Comment by SrijaVuppala295** [comment]
@abhi03ruchi , the script tag is containg lot of errors ,
image

**Comment by SrijaVuppala295** [comment]
@abhi03ruchi , is this present pr okay , okay any modifications need to be done ? should i need to change the footer 
image

**Pull request closed without merging**
