### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Dipanita45**
# Related Issue

Added security to the website

Fixes:  #4413 

# Description

Added security to protect 

<#4413   ------->

# Type of PR

- [no] Bug fix
- [no] Feature enhancement
- [yes] Documentation update
- [no] Other (specify): _______________

# Checklist:
@anuragverma108 

-\\\
- [ yes] I have tested the changes thoroughly before submitting this pull request.

Please merge my pull request and label me 
@

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
u have created this page , but not added it to readme .

Screenshot 2024-11-02 at 9 04 51 AM

u can add it here . beside code of conduct

**Comment by abhi03ruchi** [comment]
security@swapreads.com does not exist .

**Comment by Dipanita45** [comment]
Okay

**Comment by abhi03ruchi** [comment]
there are some branch conflicts . resolve them properly .

**Pull request closed without merging**
