### PR TITLE
Recreating the SuspenseThrillers page for more user experience !!

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4529

## Description
This PR introduces several enhancements to the Romance Books page to improve the overall user experience and aesthetics.

## Improvements Made
- **Title Bar**: Enhanced with a clear title and improved typography.
- **Icon Integration**: Added a unique literature-themed icon for better branding.
- **Navbar**: Redesigned for responsiveness and added hover effects.
- **Footer**: Updated with links, social media icons, and copyright information.
- **Card Design**: Improved layout, high-quality images, and interactive flip effect for book cards.
- **Responsive Design**: Ensured optimal display on various devices using CSS media queries.
- **Visual Consistency**: Established a cohesive color palette and consistent typography.
- **Accessibility Features**: Added descriptive alt text for images and ensured good color contrast.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

# BEFORE:
image
image

# AFTER:

image
image
image

https://github.com/user-attachments/assets/5023093a-4190-4ffd-a5e1-aaded609b6e7

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , mam it really took a lot of time to enhance the total page , there were many issues in prev code, please make sure you add level 3 label !!

**Comment by abhi03ruchi** [comment]
i am now not able to see ur changes in the genre section except the fantasy page . is it visible to u or its my internet .

**Comment by SrijaVuppala295** [comment]
@abhi03ruchi , there was a url issue , now i changed the index.html, Now the changes will be visible !

**Comment by abhi03ruchi** [comment]
where have u changed in classic literature pr ? its still not visible to me . u had done changes in many pages . 

only classic literature and fantasy page is visible .

**Comment by SrijaVuppala295** [comment]
@abhi03ruchi , I will create a another pr in next 1hr , i will make sure you get all the visible changes !!

**Comment by SrijaVuppala295** [comment]
please check this pr ==> #4587

**Pull request merged**
