### PR TITLE
Implement Cursor Trail Effect on DONATE BOOKS TO NGO page

### PR DESCRIPTION
**Pull request by neeru24**
fixes: #4863 

**Description:**
This PR implements a cursor trail effect on the DONATE BOOKS TO NGO Page, enhancing the user interface by adding colorful circles that follow the mouse cursor.

**Changes Made:**
- **HTML:** Added multiple `<div class="circle"></div>` elements to create the trail effect.
- **CSS:** Defined styles for the circles, including size, color, and transition effects.
- **JavaScript:** 
  - Captured mouse movements to update the position of the circles.
  - Implemented a color array for dynamic visuals.
  - Used `requestAnimationFrame` for smooth animations.

This change aims to create a more engaging and interactive user experience.

@sailaja-adapa @abhi03ruchi

### CODE REVIEW

**Comment by neeru24** [comment]
fixes: #4863 
can you merge the PR?? By mistake, I mentioned wrong issue here @abhi03ruchi

**Comment by abhi03ruchi** [comment]
change the name of the pr , and also in description write correct issue no .

**Comment by neeru24** [comment]
> change the name of the pr , and also in description write correct issue no . 

Done

**Comment by neeru24** [comment]
@sailaja-adapa kindly merge it

**Pull request merged**
