### PR TITLE
Donate organisation UI and responsive

### PR DESCRIPTION
**Pull request by TBorundia**
Fixes:  #2807

# Description
Improved UI of page, added submission message and also made the page responsive for all screen size.

# Type of PR

- [ ] Bug fix
- [X]  Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/f7242af4-dfc3-4986-89d9-3f2126ee3ce5

image

# Checklist:
- [X] I have made this change from my own.
- [X]  I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X]  I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by TBorundia** [comment]
@huamanraj @anuragverma108 Sir,
Please review this PR as soon as possible because GSSoC'24 is closing soon.

**Comment by huamanraj** [comment]
Niceee🚀

**Comment by TBorundia** [comment]
@huamanraj Sir , Can you please assign it with level 2 for my work.

**Comment by huamanraj** [comment]
> @huamanraj Sir , Can you please assign it with level 2 for my work.



done ✅

**Pull request merged**
