### PR TITLE
ADD Q&A Suggestion Template

### PR DESCRIPTION
**Pull request by alo7lika**
# Related Issue

Fixes: #4868 

# Description

Incorporating a Q&A Suggestion Template into the project enhances communication by providing a structured way for users and contributors to ask questions and provide feedback. This addition fosters a collaborative culture, improves project usability, and enables contributors to make suggestions more effectively, which ultimately leads to a more robust and user-friendly project.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
N/A

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by alo7lika** [comment]
@anuragverma108 the task has been completed. Kindly review the PR.
Dont forget to add label "GSSOC-EXT"

**Comment by alo7lika** [comment]
> @anuragverma108 the task has been completed. Kindly review the PR. Dont forget to add label "GSSOC-EXT"

@abhi03ruchi @sailaja-adapa please review

**Comment by abhi03ruchi** [comment]
add pic of changes ,

**Comment by alo7lika** [comment]
> add pic of changes ,

Screenshot 2024-10-31 142548
After merging the template will look like this

Screenshot 2024-11-10 114732
and this is the code

@abhi03ruchi

**Pull request merged**
