### PR TITLE
Fix Bugs on Get in Touch Section

### PR DESCRIPTION
**Pull request by rupeshv2121**
1.Fix the size of Form for contact us.
2.Fix the images issues which is not showing earlier due to wrong url path for images. 
3.Fix the side block of address information like resizing the block, removing extra lines.

Fixes:  #2990 

please add the label under hacktoberfest and gssoc'24-ext

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@rupeshv2121 resolve conflicts and also post a image where u made changes

**Comment by rupeshv2121** [comment]
Sorry I forgot to take ss but the conflicts are silly due to github it add some extra symbols in the file like ======, ------, >>>>>>
I remove these symbol

**Comment by rupeshv2121** [comment]
Pls Add label gssoc-ext, hacktoberfest-accpeted

**Comment by rupeshv2121** [comment]
@huamanraj @RitiChandak @RishabhDhawad  Pls Check and merge my pr under gssoc-ext and hacktoberfest alongwith level

**Pull request merged**
