### PR TITLE
unnecessary arrow in homepage are removed  #2864

### PR DESCRIPTION
**Pull request by rahmathkhasim**
# Issue

Fixes: Unnecessary arrows visible on both the left and right sides of the image in the UI which are removed now

# Description

There are unnecessary arrows visible on both the left and right sides of the image in the UI, which are not needed and clutter the design. These arrows don't seem to serve any functional purpose and can confuse the user. This affects the visual appearance of the page and might distract users from the main content.

#2864

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by rahmathkhasim** [comment]
@sailaja-adapa, I'm confused - issue #2864 was already resolved and merged, but now the changes seem to have been rolled back. Can you provide insight into what happened?.i don't know is this right place to ask

**Comment by sailaja-adapa** [comment]
It's because other contributors didn't updated branch and made PR so again may be these changes rolled back

**Comment by rahmathkhasim** [comment]
Okay Thankyou

**Comment by sailaja-adapa** [comment]
@rahmathkhasim rework on that issue

**Pull request merged**
