### PR TITLE
updating login page

### PR DESCRIPTION
**Pull request by RiyaaBhatt**

### CODE REVIEW

**Comment by anuragverma108** [comment]
@RiyaaBhatt Attach before & after screenshot. Also look into index.html - some conflicting issue is there. Make sure that your page should be responsive.

**Comment by RiyaaBhatt** [comment]
before
after
ss

ss1

**Comment by RiyaaBhatt** [comment]
mobile friendly
image

**Comment by anuragverma108** [comment]
image

Resolve this conflicting issue. 
Pull all the changes of the rep & create PR again.

**Pull request closed without merging**
