### PR TITLE
Add romantic and suspense-thriller  books

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

Fixes:  #3995

# Description

this PR creates two new pages for romance and suspense-thriller and links them with the cards.
# issue #3995 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/03c180b3-e1d5-417d-8905-97d13f2ebe8a

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resource
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
there are branch conflicts .

**Comment by abhi03ruchi** [comment]
for classic literature  add the page , without api in this manner . so that user can see easily ( without writing code in vs code ).

u can create separate pr for it .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi resolved merge conflicts
and I will do the classic-literature page.

**Comment by abhi03ruchi** [comment]
check deploy preview . 
Screenshot 2024-10-28 at 11 34 43 PM

some bug has come , after u resolved merge conflict .

**Comment by haseebzaki-07** [comment]
hey @abhi03ruchi please check now

**Pull request merged**
