### PR TITLE
fix navbar for all pages 

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Fixed navbar for 

- event 
- community page 
- login 
- audi books

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
the changes u have done are not visible in the deploy preview . the navbar look same as before.  

booklistswap page navbar is good . add that navbar to all the pages .

**Comment by shubhagarwal1** [comment]
> the changes u have done are not visible in the deploy preview . the navbar look same as before.
> 
> booklistswap page navbar is good . add that navbar to all the pages .

my bad, thing worng code pushed, hey @abhi03ruchi can you please list the pages that need to have navbar
also can i make new navbar for them 
that will be consisten to thepage you mention here, as because code is so redundant in all the pages it is difficult to pick the specific code for the navbar, hope you understand.

**Comment by abhi03ruchi** [comment]
ok

**Comment by shubhagarwal1** [comment]
> ok

Hey @abhi03ruchi can you please merge this one, i will work on the navbar then, it would be great help

**Comment by abhi03ruchi** [comment]
no , i can't because changes are not visible at all .

**Comment by abhi03ruchi** [comment]
the pages that u mentioned above , all pages mentioned  in the profile avatar dropdown and 


chk pages mentioned in Quick Link and Copyright Policy , Privacy Notice etc ...  all the links stated in the link below.
Screenshot 2024-10-24 at 9 30 06 AM

**Comment by shubhagarwal1** [comment]
> the pages that u mentioned above , all pages mentioned in the profile avatar dropdown and
> 
> chk pages mentioned in Quick Link and Copyright Policy , Privacy Notice etc ... all the links stated in the link below. Screenshot 2024-10-24 at 9 30 06 AM

Okay i understand now please tell what exactly i have to do, i will start working accordingly.

**Comment by abhi03ruchi** [comment]
books page navbar has good design ( it just needs to be center aligned )  . add that navbar design to all the pages .

**Comment by abhi03ruchi** [comment]
u are already assigned , work on it . and add changes.

**Comment by shubhagarwal1** [comment]
> u are already assigned , work on it . and add changes.

okay, i will make sure to add changes

**Comment by anuragverma108** [comment]
Conflicting files
assets/html/event.html
assets/html/login.html

@shubhagarwal1 

We are unable to identify your contribution in the current PR. Kindly attach **before and after screenshots** to clearly showcase the changes you have made. Additionally, please provide a detailed explanation of the work you have done in the PR description. This will help us better understand your contribution and proceed with the review. 


Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by shubhagarwal1** [comment]
Hey @anuragverma108, 
Thank you for the feedback and guidance. I apologize for any lack of clarity in my recent PR. I'll add the requested before-and-after screenshots to demonstrate the changes clearly, along with a detailed explanation in the PR description to outline my contributions.

I’ll also make sure to pull the latest changes, resolve the conflicts, and open a new PR for review once completed.

Thanks again for your patience, and please let me know if there’s anything specific you'd like included.

Best regards,
Shubh

**Pull request closed without merging**
