### PR TITLE
Added downwards carousel in genre section for light mode #1988

### PR DESCRIPTION
**Pull request by DevNandini02**
# Description
Implemented downwards carousel in genre section only for light mode. 

#1988 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/anuragverma108/SwapReads/assets/124669890/b954173f-3111-42f2-bbc5-0010cd4a0007

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by DevNandini02** [comment]
@RitiChandak I tried to make changes in the dark mode too but some issue is coming as the structure of the carousel is changing in the dark mode which may be due to previous codes written by somebody else.

**Comment by RitiChandak** [comment]
@DevNandini02 What problem are you facing?

**Comment by DevNandini02** [comment]
> @DevNandini02 What problem are you facing?

@RitiChandak in dark mode i just changed the color of the carousel cards but the structure of the carousel is also getting changed .

https://github.com/anuragverma108/SwapReads/assets/124669890/a09a98ea-7dae-467f-9448-05d48e6f0466

As you can see in dark mode a lot of gap is coming in the card than the light mode carousel. Also its difficult to rectify whether anybody else has used similar class names or what properties they have defined for dark mode as the css code is quite messed up in both index.html and style.css file.

**Comment by RitiChandak** [comment]
@DevNandini02 I'll contact you regarding this

**Comment by DevNandini02** [comment]
@RitiChandak please merge this PR.

**Comment by RitiChandak** [comment]
hi @DevNandini02 if we are implementing a feature, it should work properly

**Comment by RitiChandak** [comment]
either you make it properly like in light mode or i won't be able to merge it

**Comment by RitiChandak** [comment]
and if you need any help, please free to contact any of us @RishabhDhawad @huamanraj @anuragverma108 or me

**Pull request closed without merging**
