### PR TITLE
 Add Cursor Tail Effector in Map page ! #4234

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add Cursor Tail Effector in Map page done - #4234

https://github.com/user-attachments/assets/2cdee413-77ab-4a27-8d7d-d97417cc5d77

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi please merge my PR

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi @sailaja-adapa @atmajaa  please merge my PR with label

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi @sailaja-adapa @atmajaa

**Comment by sailaja-adapa** [comment]
@Subhajit-2023-44 it already exists work on new issue

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 it already exists work on new issue

@sailaja-adapa ma'am can you please merge my PR and give me level 1 because i send PR first, but someone solve it in his pr which he send after me..

Screenshot 2024-10-30 144703

**Comment by Subhajit-2023-44** [comment]
@sailaja-adapa Thank You

**Pull request merged**
