### PR TITLE
Fixes#3736:Improved the UI of the navbar by adding hover effects.

### PR DESCRIPTION
**Pull request by Arghya-Chakraborty0812**
# Related Issue

None

Fixes:  #3736 
# Description
Improved the UI of the navbar by adding hover effects.I could not add a footer.
Issue.No:#3736

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/d2cc1e80-c5ac-4ca8-9200-6ff10e4ce093

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

I could not add a footer but I had added hover on the navbar.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
the pink navbar on this page actually doesnt look nice .
 U could add the same navbar design that is on the other pages ( community support page ).

**Comment by Arghya-Chakraborty0812** [comment]
New Preview:

https://github.com/user-attachments/assets/5bdb6e14-40a9-4b0d-bf41-27174947431e

**Comment by abhi03ruchi** [comment]
Screenshot 2024-10-19 at 3 16 56 PM
icons in the navbar design are dynamic . ( chk community support page or login page ).
Just copy the navbar code from there .

**Comment by Arghya-Chakraborty0812** [comment]
Can you please unassign this to me @abhi03ruchi

**Pull request closed without merging**
