### PR TITLE
I have improved the book exchange form

### PR DESCRIPTION
**Pull request by Vivisteria11**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
None

https://github.com/user-attachments/assets/3ae496f0-ec8b-4ad2-b1b6-aa28776d770c

Fixes:  #2877 

# Description

I have improved the form Book exchange HUB ,it was a very simple form before but now I have included more details where users input the genre of the book ,the condition it is in ,they can also input a discount price of their choice and I have included a function which will predict the selling price of the book based on that in INR. Users need to input their name and email ,along with this an optional field where they can type any interesting information about the book they are selling to appeal to another Reader and also an image can  be uploaded for more context. Finally they can submit their form.

# Type of PR

- [x] Feature enhancement -I have improved the book exchange form to make it more specific and user friendly.

# Checklist:

- [x ] I have taken help from some online resources.
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.

- [ x] My changes generate no new warnings.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
resolve merge conflicts @Vivisteria11

**Comment by Vivisteria11** [comment]
I am new to the open source process, kindly guide me if I have to perform any more changes .

**Comment by abhi03ruchi** [comment]
Screenshot 2024-10-18 at 7 31 16 AM
Just change the text alignment to left .

**Comment by Vivisteria11** [comment]
When I ran it before making the pull request it was aligned properly. How did it change. 
Should I go back and push the changes through git again ??

**Comment by sailaja-adapa** [comment]
your changes were good but please work with updated branch

**Pull request closed without merging**
