### PR TITLE
Add Cursor Tail Effector in Authors & Tips page done ! #4156

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add Cursor Tail Effector in Authors & Tips page done - #4156

https://github.com/user-attachments/assets/1e40fb48-85c6-4072-abb6-4d24c6a8a659

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
PA please merge my PR with level 2 

Thank you

**Comment by abhi03ruchi** [comment]
decrease the size of the cursor a little bit ( keep it  home page cursor size ) .

**Comment by Subhajit-2023-44** [comment]
> decrease the size of the cursor a little bit ( keep it home page cursor size ) .

ok wait i will give new pr

**Comment by Subhajit-2023-44** [comment]
> decrease the size of the cursor a little bit ( keep it home page cursor size ) .

@abhi03ruchi done #4166, please merge my PR with level 2

Thank You

**Pull request closed without merging**
