### PR TITLE
Footer and Styles Alignment

### PR DESCRIPTION
**Pull request by Molza01**
# Related Issue

None

Fixes:  #4330 

# Description

The Alignment of the footer contents in the footer is not aligned properly and also the changed some styles too.

Isuue Number - #4330

# Type of PR

- [x] Bug fix

# Screenshots / videos (if applicable)
Before!!
Screenshot 2024-10-31 145403

After!!

Screenshot 2024-10-31 153807

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
not looking good improve it more since it look like before footer  only @Molza01

**Comment by Molza01** [comment]
@sailaja-adapa Ok ma'am.

**Comment by Molza01** [comment]
I have made changes into the footer. I have done adjustment and alignment and given style to it also.


Screenshot!!

Before
Screenshot 2024-10-31 153807


After
Screenshot 2024-11-01 011104

**Comment by abhi03ruchi** [comment]
remove the backgrd color from quick links 

Screenshot 2024-11-01 at 9 20 35 AM

  aisa karo . chk community spotlight page.

**Comment by Molza01** [comment]
I have done the changes and generated an another pr #4371 .
@abhi03ruchi

**Pull request closed without merging**
