### PR TITLE
add book recommendation 

### PR DESCRIPTION
**Pull request by jainaryan04**
# Related Issue

Fixes:  #4993 

# Description
add a button to give users book recommendations from a defined array of objects.

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

@abhi03ruchi please merge
# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
image

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by jainaryan04** [comment]
@abhi03ruchi

**Comment by jainaryan04** [comment]
@atmajaa

**Comment by atmajaa** [comment]
@jainaryan04 This feels like a separate page on it's own.  Navbar and footer is not present and there are just 4-5 books.

**Comment by jainaryan04** [comment]
ok will add @atmajaa

**Pull request merged**
