### PR TITLE
Sending confirmation email upon Subscribing

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
# Related Issue

Fixes:  #2774 

# Description

User will recieve a confirmation email upon successfully subscribing to the website. And giving a alert upon subscribing.

# Type of PR

- [X] Feature enhancement

# Screenshots / videos (if applicable)
[f0d79d07-61ec-4bc5-8600-fc9605429b41.webm](https://github.com/user-attachments/assets/66dcc0d2-23e7-499a-ac06-780c626b1d69)

image

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@huamanraj 
I've resolved the conflicts. Please review this PR and assign the appropriate labels.
Note: I have not included the EmailJS credentials in the code.

**Comment by huamanraj** [comment]
This branch has conflicts that must be resolved

Conflicting files
index.html

**Comment by huamanraj** [comment]
> @huamanraj 
> I've resolved the conflicts yesterday.

still there are conflicts

**Comment by huamanraj** [comment]
> @huamanraj 
> I'll open another PR. However, instead of closing it, please let me know if there are any conflicts, and I can resolve them within the same PR.


ok! i can do this but closing PR helps to manage and prioritise the PRs and less conflict issues

**Comment by Bhattu-Anitha-07** [comment]
Ok @huamanraj 
I'll be opening a new PR. Please merge it as soon as possible if you can. 
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@huamanraj Thanks for reopening this PR.
I've resolved the conflicts, please review this PR and assign labels.
Thank you.

**Comment by huamanraj** [comment]
done @Bhattu-Anitha-07 👍

**Pull request merged**
