### PR TITLE
add translator in navbar all pages

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4058 

# Description

add translator in navbar all pages

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/1258b7b9-8aae-496e-aa97-dfd54b680584

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Antima2004** [comment]
please assign this pr under label level 3 and I have completed the navbar section , footer section and some pages are left

**Comment by abhi03ruchi** [comment]
also chk all the pages footer , translate button is put there , which actually doesnt work . remove it .

u can work on this issue and raise a pr .

**Comment by Antima2004** [comment]
i already raise the pr please assign me
@abhi03ruchi

**Comment by Antima2004** [comment]
making directly pr can i gets these point @abhi03ruchi

**Comment by abhi03ruchi** [comment]
> making directly pr can i gets these point @abhi03ruchi
follow the rule . create issue and then raise pr .

**Comment by Antima2004** [comment]
So for this pr i can't get any point??

> > making directly pr can i gets these point @abhi03ruchi
> > follow the rule . create issue and then raise pr .

**Comment by abhi03ruchi** [comment]
chk in leaderboard .

**Comment by Antima2004** [comment]
> chk in leaderboard .

I checked but it's not updated my points

**Comment by abhi03ruchi** [comment]
this maybe because updation doesnt happen in real time .

chk the page .

The leaderboard was last updated on: 10/28/2024, 12:09:31 PM No New PRs merged after 31th October 7:00p.m are counted[More details about badges](https://github.com/GSSoC24/Contributor/discussions/288).

**Comment by Antima2004** [comment]
Ok thanks 🙏

**Comment by Antima2004** [comment]
@abhi03ruchi 
I have almost completed adding translator in your website but few are left in the navbar submenu part (i. e. 7 pages) can i get level 3 for this??

**Pull request merged**
