### PR TITLE
Duplicate index.html Removed with no Problems in paths in Navbar 

### PR DESCRIPTION
**Pull request by Maheshwari-Love**
# Related Issue

Fixes:  #1271 

# Description

So Finally I have found that on deleting index.html file inside the assest folder created the problem with following three page:
Login
Sign Up
Forgot password
The navbar was Not working as the paths were given wrong or we can say that in these three files the two different navbar were made i have changed them as one with all working paths.

Refer Video.

https://github.com/anuragverma108/SwapReads/assets/142833275/be2a0fd5-d94b-4dfb-85b9-70268a141c9e

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Maheshwari-Love** [comment]
@huamanraj please review and merge

**Review by huamanraj — APPROVED** [review]

**Comment by huamanraj** [comment]
> @huamanraj please review and merge
> 

have you checked is everything working fine?

**Comment by Maheshwari-Love** [comment]
> > @huamanraj please review and merge
> 
> have you checked? is everything working fine?

yes completely fine

**Comment by Maheshwari-Love** [comment]
@huamanraj i have uploaded the video of working of site after changes

**Review by huamanraj — APPROVED** [review]

**Pull request merged**
