### PR TITLE
ADD Git Contributors Page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #3758 
Screenshot 2024-10-20 at 11 18 36 PM

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
that section is already present in about us @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> > that section is already present in about us @shubhagarwal1
> 
> i was assigned this issue, i just worked on the code ADD a dedicated page for Git Contributors #3758 i just didnt knew about the page nor was informed, many folks may get tricked like this, as it takes a lot of effort to build a page.
Thankyou for your considertion

**Comment by sailaja-adapa** [comment]
I am really sorry for this by wasting ur time work on new issue I will assign high level don't worry @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> I am really sorry for this by wasting ur time work on new issue I will assign high level don't worry @shubhagarwal1

Do you have any specific implementation, or any feature planning, please share would love to work on it.

**Comment by sailaja-adapa** [comment]
Fix the Navbar on all pages with all options included @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> Fix the Navbar on all pages with all options included @shubhagarwal1

ok Sure...

**Pull request closed without merging**
