### PR TITLE
Translator button in remaining pages

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4058 

# Description

Changes and added translator button in the remaining pages of your website, finally completed adding translator button in your whole website pages.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/11dee2a6-6d12-452f-8ff1-80586a82ade8

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
delete the assets/html/pricing.html page as updated pricing section is already present in the home page . 

u may work on this issue and raise pr .

**Comment by Antima2004** [comment]
I have to only delete  the assets/html/pricing.html page???

> delete the assets/html/pricing.html page as updated pricing section is already present in the home page .
> 
> u may work on this issue and raise pr .

**Comment by abhi03ruchi** [comment]
ya , u may work on this issue . it is redundant .

**Comment by Antima2004** [comment]
done

> ya , u may work on this issue . it is redundant .

**Pull request merged**
