### PR TITLE
FIX: added join now

### PR DESCRIPTION
**Pull request by shelar1423**
This PR fixes issue #238 

before:
image

after:
image

### CODE REVIEW

**Comment by huamanraj** [comment]
> @huamanraj kindly have a look and let me know if this works good,thank you
> 

work on better design consistency! it doesn't go well !

**Comment by shelar1423** [comment]
> > @huamanraj kindly have a look and let me know if this works good,thank you
> > 
> 
> work on better design consistency! it doesn't go well ! 

Is it with the position on the text or exactly what is it so that I can change it accordingly

**Comment by huamanraj** [comment]
image

make it at left asigned as text and similar inverted theme button as icos

**Comment by shelar1423** [comment]
> image
> 
> make it at left asigned as text and similar inverted theme button as icos

cool ill just do it and update you

**Pull request closed without merging**
