### PR TITLE
E-books Feature Added

### LINKED ISSUE #974: Adding and E-book section to the homepage before user logs in
### Describe the feature

Adding an E-Books section to the homepage before logging in would enhance the user experience by providing easy access to digital reading materials. Each book cover could serve as a clickable link, leading users to more detailed information about the E-Book, such as its synopsis, author information, and reader reviews.

### Add ScreenShots

Screenshot 2024-05-29 021425

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by samarsajad**
## Fixes #974 
Added the E-books feature to the homepage after the user logs in. The E-books section was already there before logging in but now it has disappeared.
E-books Feature added to the  homepage after the user logs in
Before adding the feature 
Screenshot 2024-05-29 123244
After adding the feature
image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @anuragverma108

**Comment by samarsajad** [comment]
Kindly check my pull request @huamanraj @anuragverma108

**Comment by anuragverma108** [comment]
@samarsajad 
Please note that this is not in line with our code of conduct. To ensure clarity and proper assignment tracking, please attach the issue number to your PR description. This helps us confirm that the issue is assigned to you. Kindly update your PR with the issue number.
Example:
Fixes #123 - Brief description of the fix.

**Comment by samarsajad** [comment]
#974 
Added the E-books feature to the homepage after the user logs in. The E-books section was already there before logging in but now it has disappeared.  @anuragverma108

**Comment by anuragverma108** [comment]
image
Conflicting files
assets/css/style.css
Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
