### PR TITLE
Enhancing the ui design of the pricing section with same theme but better ui/ux.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4016 

# Description

Enhanced the pricing page making the buttons and ui elements similar to the entire page to make it consistent over the entire page.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

Please check this pr and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
highlight and increase the size of percentage off ( 25% etc ) for better user experience . 

decrease the height of the boxs . there is space above and below the buttons .  adjust the spacing .

**Comment by tarunkumar2005** [comment]
image

Check now @abhi03ruchi

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/f03db871-48f4-4c4c-a855-554b4a96c896

chk deploy preview . there is some bug , fix it .

**Comment by abhi03ruchi** [comment]
are u working on this issue? gssoc ext is about to end.

**Comment by tarunkumar2005** [comment]
Ya i had updated it but you said there is a bug i am trying to find that will update it soon.

**Comment by abhi03ruchi** [comment]
> Ya i had updated it but you said there is a bug i am trying to find that will update it soon.

check deploy preview .

**Comment by sailaja-adapa** [comment]
work with updated branch and raise new PR @tarunkumar2005

**Pull request closed without merging**
