### PR TITLE
Updated the "Quick Links" again

### PR DESCRIPTION
**Pull request by devikaharshey**
Fixes:  #4960

# Description

According to the suggestions received, I've again updated "Quick Links" and it looks much better now. It not only is responsive but also adds to better user experience.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-10 145202

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by devikaharshey** [comment]
@abhi03ruchi I've made the changes. Can you check it again?

**Comment by devikaharshey** [comment]
@abhi03ruchi and please merge the request if the changes are better.

**Comment by abhi03ruchi** [comment]
remove the hover effect color too .

**Comment by devikaharshey** [comment]
@abhi03ruchi I've removed the hover effect too (you can check code as well):
Screenshot 2024-11-10 163422

Does it look good now?

**Pull request merged**
