### PR TITLE
Added quick link icons and changed font size

### PR DESCRIPTION
**Pull request by likitha-kapu**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4712 

# Description
The quicklinks in the footer section of About us page has no icons.Added the icons to create better visual effect.Also changed the font size and colour of Swapreads and quick links heading.
#4712 

# Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
This the changes I have made:
image

# Checklist:

- [X ] I have made this change from my own.
- [ X] My code follows the style guidelines of this project.
- [ X] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generate no new warnings.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
resolve conflicts @likitha-kapu

**Comment by sailaja-adapa** [comment]
Already had icons in about page @likitha-kapu

**Comment by sailaja-adapa** [comment]
k

work on new issue on fixing these icons without overlapping work with updated branch @likitha-kapu

**Comment by likitha-kapu** [comment]
@sailaja-adapa  Yeah ok

**Comment by likitha-kapu** [comment]
@sailaja-adapa 
image
the icons are aligned properly already

**Comment by sailaja-adapa** [comment]
work with updated branch 
In new branch they were appearing like that @likitha-kapu

**Pull request closed without merging**
