### PR TITLE
 the box size of "Donate to Organisations" not matching with the other boxes dimensions

### PR DESCRIPTION
**Pull request by ark0078**
# Related Issue
I've updated the "DONATE BOOKS" option cause I've updated the the boxes dimensions of "DONATE TO ORGANISATIONS" and it was not aligning with other boxes dimensions before.Kindly check it and merge it..Also I've used the inline css along with html.Also the box dimensions are matching now and it now looks perfect.Please add the images in relevant places.
Screenshot (230)

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.) #3148 solved

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by ark0078** [comment]
@sailaja-adapa please check and merge it    #3148 solved now.

**Comment by sailaja-adapa** [comment]
update branch

**Comment by ark0078** [comment]
@sailaja-adapa what it's showing actually?the branch is already updated...check donations1.html

**Comment by ark0078** [comment]
#3180 @sailaja-adapa

**Comment by sailaja-adapa** [comment]
@ark0078 i think this section is already fine how about this can u change font in the cards

q

**Comment by ark0078** [comment]
@sailaja-adapa ,no    check the "Donations to Organisation" portion..it's not aligned with other buttons like "Donate to schools" and "Donate to Libraries"..if you just check properly,mine one has no issue with the alignment..all the "Donate to" buttons are in one line and in the same alignment..kindly check

**Comment by ark0078** [comment]
@sailaja-adapa do lemme know please...

**Comment by sailaja-adapa** [comment]
yeah sure @ark0078

**Comment by ark0078** [comment]
@sailaja-adapa accha,are you going to merge it now??or any changes required ??tell me please

**Comment by sailaja-adapa** [comment]
I am busy right now I will notify you soon

**Comment by ark0078** [comment]
@sailaja-adapa sure..no worries..just notify me once

**Comment by sailaja-adapa** [comment]
Yeah sure Thanks @ark0078

**Pull request merged**
