### PR TITLE
fixed issue of local run

### PR DESCRIPTION
**Pull request by Ridhima10**
Hello Pa, 
Issue resolved- #2546

Earlier there were two ports running, i fixed it and now it is running perfectly

### CODE REVIEW

**Comment by Ridhima10** [comment]
@huamanraj  kindly add label of level

**Comment by huamanraj** [comment]
> @huamanraj  kindly add label of level

as gssoc guidelines this much changes has no level!

**Comment by Ridhima10** [comment]
So it won't get any point?

**Comment by huamanraj** [comment]
> @huamanraj  So it won't get any point? 
> Also it took time to figure out what's the issue, it might seems minor but it was a major issue since people were not able to run your project locally! 

ok so you must have described in PR also so  GSSOC reviewers can see why it has a level

**Pull request merged**
