### PR TITLE
Login page dark mode

### PR DESCRIPTION
**Pull request by sau-mili**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #2712 

# Description
- Dark-mode of Login page improved
- Index page toggle button icons added
- Back to top button made visible in dark mode
[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

## after
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
image
https://github.com/user-attachments/assets/8d9b435f-090e-434d-94ec-0cd9b4b8f74e
image

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by huamanraj** [comment]
good work @sau-mili 👏🏿

**Comment by sanjay-kv** [comment]
image

@sau-mili you will be seeing a lot of change in points due to the labelling practice the community site. as i dont have the access to the repo, will be taking out points from other repo. 
https://github.com/GSSoC24/Contributor/discussions/517 check here as well.

**Comment by sau-mili** [comment]
It’s okay @sanjay-kv . I never demanded for any levels. The PAs assigned according to their choice. 
Also, contributors who are already maintainers of some repo do have an edge over others. Maybe you can check that as well.

**Comment by sanjay-kv** [comment]
@sau-mili We made sure that no contributors has previously been in the project we selected, If they became mainatiner its becuase of their hardwork, i do find people who good at contributions and give opportunity to work on gssoc website and my repo as well. 

thats how opensource work, i do agree they do get some more priority over others, but we make sure that everything follows guidelines, if you find anything not following guidelines can report to us.

**Pull request merged**
