### PR TITLE
Added downwards carousel to genre section #1988

### LINKED ISSUE #1988: Feat: Add a downwards carousel to Genre section
### Describe the feature

Since there are a number of cards in the genre section, we can add a downwards carousel that expands downwards on clicking the down arrow.

### Add ScreenShots

bottomcarousel

Like this on clicking the arrow other cards will expand downwards.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by DevNandini02**
# Description
Added a downwards carousel in the genre section for better user experience. As the user will click on the show more or less button the carousel will expand and minimize accordingly.

fixes #1988 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/anuragverma108/SwapReads/assets/124669890/a8c3e9c7-6d3b-46a4-aa19-5c676dba66f4

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@DevNandini02 level will be assigned after seeing your changes and work

**Comment by RitiChandak** [comment]
image
10,11,12 is not visible

**Comment by RitiChandak** [comment]
Implement the changes and either create a new pull request or reopen the existing one.

**Comment by DevNandini02** [comment]
@RitiChandak I had only implemented the carousel for light mode not for dark mode. Please check the light mode implementation.

**Pull request closed without merging**
