### PR TITLE
Enhanced Chapter Cards with Dynamic Hover Effects

### PR DESCRIPTION
**Pull request by neeru24**
fixes: #4621 

### Changes Made:

* **Added Transition Effects:**
    * Introduced smooth CSS transitions to the chapter cards for visual changes.
* **Implemented Hover Effect:**
    * Added a hover effect that scales the card up slightly when hovered over.
* **Added Box Shadow on Hover:**
    * Included a box shadow effect to enhance the visual depth of the card on hover.
* **Overall Visual Improvement:**
    * Enhanced the user experience by making the chapter cards more interactive and visually appealing.

Kindly merge it with level 2 if possible. @sailaja-adapa @abhi03ruchi 
Thank you!!

### Result: 

https://github.com/user-attachments/assets/1937842c-4a0e-49e0-b32e-0e4d82e034bd

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
hover effect on cards is already there .

**Comment by neeru24** [comment]
> hover effect on cards is already there . 

It's not there, check it out, only the border appears but I've made the changes to SCALE that UP

**Comment by abhi03ruchi** [comment]
ok , but this is a v minor  change . 

if u implement it in all pages of benefits section , then u may get level 2 .

**Comment by neeru24** [comment]
> ok , but this is a v minor  change . 
> 
> if u implement it in all pages of benefits section , then u may get level 2 . 

Sure 👍 I'll implement and will raise a new PR.

**Comment by neeru24** [comment]
> ok , but this is a v minor change .
> 
> if u implement it in all pages of benefits section , then u may get level 2 .

@abhi03ruchi Check this PR
https://github.com/anuragverma108/SwapReads/pull/4661

**Pull request closed without merging**
