### PR TITLE
Additional Footer in events page

### PR DESCRIPTION
**Pull request by likitha-kapu**
Fixes:  #4363  
# Description
The addition of a footer section on the events page is necessary to enhance user experience and accessibility. This footer should include key elements such as home,benefits,contact etc to encourage engagement. The addition of Swap Reads info is also required int the footer section.

Fixes: #4363  

# Type of PR

- [x ] Feature enhancement

# Screenshots / videos (if applicable)
image

# Checklist:
- [ X] I have made this change from my own.
- [X ] My code follows the style guidelines of this project.
- [ X] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generate no new warnings.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by likitha-kapu** [comment]
@abhi03ruchi check out my pull request

**Comment by abhi03ruchi** [comment]
the footer is not responsive , u can work on the issue and raise new pr

**Comment by likitha-kapu** [comment]
@abhi03ruchi i have created just the html and css part

**Comment by likitha-kapu** [comment]
@abhi03ruchi actually all the options are responsive except for the home options....once check out

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi i have created just the html and css part

ya , for resonsiveness u need to work on css .

**Comment by likitha-kapu** [comment]
@abhi03ruchi once check for the other options like pricing,recomended books etc..whether .they are responding or not

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi once check for the other options like pricing,recomended books etc..whether .they are responding or not

matlab ?

**Pull request merged**
