### PR TITLE
Fix and Improve Navbar Dropdown Functionality with Correct Link Paths

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #3655

# Description
## The Dropdown is not working for many pages like
 - ( pricing.html, booklistswap.html , freebooks.html , readerconnection.html  and etc...)
 - I HAVE MADE CHANGES TO ALL THESE PAGES

##  Implemented Proper Dropdown Toggle: 
-  Added JavaScript functionality to ensure the "More" dropdown menu in the navbar toggles correctly on click. The dropdown 
   now opens and closes as expected when the user clicks the "More" link.

##  Optimized User Interaction:
-  Prevented the default behavior of the anchor tag to avoid page reloads or unwanted navigation while interacting with the 
  dropdown. This ensures a smooth and intuitive experience for users.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
## BEFORE

https://github.com/user-attachments/assets/504cede7-fcbc-4df6-a4dd-4f39eee48fdd

## AFTER

https://github.com/user-attachments/assets/1e61903f-1ac3-4061-bf44-5a64218754b5

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
resolve conflicts @SrijaVuppala295

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , please review it , its resolved

**Comment by sailaja-adapa** [comment]
resolve conflicts @SrijaVuppala295

**Comment by sailaja-adapa** [comment]
create new PR @SrijaVuppala295

**Pull request closed without merging**
