### PR TITLE
add translater

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

None

Fixes:  #4053

# Description
Added translater in the audio page of your website.

#4053 

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/e6fafa00-2dd8-41fc-9835-7a14a5a77237

there are some size issue . fix it .

**Comment by Antima2004** [comment]
Ok

**Comment by abhi03ruchi** [comment]
add this translate button on all pages . 

u may work on this issue and raise pr . will increase the level for it .

**Comment by Antima2004** [comment]
ok i have to add this in all pages and then make pr again @abhi03ruchi

**Comment by Antima2004** [comment]
this pr is closed?? @abhi03ruchi

**Comment by abhi03ruchi** [comment]
yes this pr is closed as u have resolved the issue . 

create another issue ( adding translator in all pages) and raise new pr then

**Comment by Antima2004** [comment]
Ok

**Comment by Antima2004** [comment]
hello @abhi03ruchi 
i have to create two pr because there are lots of pages in your website and so many error so that you can give me level 3 in the separate pr because i have make many changes in every pages of your website
can i do this??

**Comment by abhi03ruchi** [comment]
ya sure .

**Comment by Antima2004** [comment]
ok

**Comment by Antima2004** [comment]
hello @abhi03ruchi 
i have commit  but there is no option for pr creation
please help me

**Comment by abhi03ruchi** [comment]
create a new issue ( add translation effect ) and then raise pr .

**Pull request merged**
