### PR TITLE
Fix navbar alignment issues

### PR DESCRIPTION
**Pull request by Ashish-Patnaik**
# Related Issue

None

Fixes:  #3358 

# Description

I fixed the alignment issues in navbar in About Us Page where the text overlaps the logo in the navbar and made the dropdown beautiful

#3358 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)
BEFORE
Capture

AFTER
y67

BEFORE

AFTER

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
the dropdown change has not been done on the  logIn / sinUp page . Plz chk all pages .

**Comment by sailaja-adapa** [comment]
mn

changes were not resembling @Ashish-Patnaik

**Comment by Ashish-Patnaik** [comment]
well i only fixed for the the about us page so should I change for all pages

**Comment by sailaja-adapa** [comment]
I kept u screenshot of about us page only work with updated branch since I made many changes to website raise new PR

**Pull request closed without merging**
