### PR TITLE
Add Project Statistics in Contributors page done ! 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add Project Statistics in Contributors page  - #4431
Done -

Screenshot 2024-11-02 020351

Before -

Screenshot 2024-11-02 020229

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
the contributor page , lacks responsiveness .

u can work on this issue and raise pr .

**Comment by Subhajit-2023-44** [comment]
> the contributor page , lacks responsiveness .
> 
> u may work on this issue and raise pr .

Okay i will try, 

@abhi03ruchi PA kindly give me level 2 🙏🏻

**Comment by Subhajit-2023-44** [comment]
> the contributor page , lacks responsiveness .
> 
> u may work on this issue and raise pr .

Okay i will try, Can you tell me what I can do?

@abhi03ruchi PA kindly give me level 2 🙏🏻

in other projects they also give level 2 for this ...

Screenshot 2024-11-02 022153

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 you just simply added those values statically but since it's new feature we are giving you level 2 if you want to work on updating values dynamically create new PR

Okay I will try 🙏🏻

**Pull request merged**
