### PR TITLE
Enhancing the Feedback section styling and adding name and email id for the form

### PR DESCRIPTION
**Pull request by shriyadindi**
# Related Issue

Enhancing the Feedback section styling and adding name and email id for the form

Fixes:  #4687 

# Description

Enhancing the Feedback section styling and adding name and email id for the form.

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-06 191426

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
Already present one is fine @shriyadindi no need of email and name
 do one thing just align rate us and tell us about your experince  text in middle of container
and also your changes were not according to colour theme work with updated branch

**Comment by shriyadindi** [comment]
@sailaja-adapa why are you closing the PR do you know how much effort it takes to create one? Just request the changes in the changes request section and I would work on that, closing the PR and telling to make new changes on a new PR is very disrepectful.

**Comment by sailaja-adapa** [comment]
mn
this footer section has been misallgined and also u changed colour theme of rate us container inorder to avoid u unnecessary time waste i just told u to work with updated branch since u directly made changes to index.html 
In another PR u raised i didn't closed it right i asked u to delete index.html just to not waste your time and i also thought to assign u good level since i aksed u to make changes again and again

**Comment by sailaja-adapa** [comment]
don't take it in bad way if u are working with your current branch it will take lot of time to you to make changes by changing colour correcting footer and also i merged many PR's which will cause you conflicts if u raise PR from your current branch that's why i closed your PR hope u get it @shriyadindi

**Pull request closed without merging**
