### PR TITLE
Added progress bar on romantic escapes page .

### PR DESCRIPTION
**Pull request by meetarora10**
# Related Issue
Add a progress bar on the romantic escapes page.

Fixes:  #2428

# Description
I have added a progress bar on the top of the navbar on the romantic escapes page exactly similar to the home page .

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
**Before**
https://github.com/user-attachments/assets/83770feb-cbc3-42c9-9773-88dbb769630d

**After**

https://github.com/user-attachments/assets/8b55f028-ecee-4985-baf1-61cfaef19e4d

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by meetarora10** [comment]
@huamanraj please review and merge this.

**Comment by meetarora10** [comment]
@huamanraj please have a look .

**Comment by huamanraj** [comment]
good work!! 👏🏿 but this is too basic change so you wont get any level as GSSOC guidelines and it was also mentioned in issue notice!!

**Comment by meetarora10** [comment]
@huamanraj this was not basic.

**Comment by meetarora10** [comment]
I have added progress bar as mentioned in the issue. 
You should told this while assigning me .

**Comment by meetarora10** [comment]
This was my issue and at least level 1 label would be fine.

**Comment by meetarora10** [comment]
If you want I can add progress bar in all other pages where it is not present.

**Comment by meetarora10** [comment]
In the issue you had given level 1 label @huamanraj .

**Comment by huamanraj** [comment]
> In the issue you had given level 1 label @huamanraj .

it is automated! the level is determined at PR  stage !

**Comment by huamanraj** [comment]
> @huamanraj this was not basic.

it is just copying from one file and pasting in another! just 5 lines of code change it is!

**Comment by meetarora10** [comment]
Okay fine bro.

**Pull request merged**
