### PR TITLE
Made changes in the nav bar

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Related Issue

Added FAQ s section in the nav bar

Fixes:  #1924 

# Description

Added FAQ s sectin in the nav bar

# Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
before

image

after

image

# Checklist:

- [x ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RishabhDhawad** [comment]
You have not been assigned to work on this issue. This violates our open-source code of conduct. 
Please focus on the issue you have been assigned to.
Do Not raise an issue before the assignment.

**Comment by Saipradyumnagoud** [comment]
@anuragverma108  @huamanraj  Please review my pull request

**Comment by Saipradyumnagoud** [comment]
> You have not been assigned to work on this issue. This violates our open-source code of conduct. Please focus on the issue you have been assigned to. Do Not raise an issue before the assignment.

In This repo while raising the issue we can self assign the issue to us i hope .

**Comment by RishabhDhawad** [comment]
You can definately raise a new Issue that you feel like. But you cant merge the PR before assignment. There are so many contributors who are waiting for the issue assignments by the Mentors. 
But for every other Project I am telling you , not to raise a PR before assignment of the issue. Unless it's assigned to you will not get points in the GSSoC leaderboard also this is against our Guidelines.

**Comment by anuragverma108** [comment]
@Saipradyumnagoud Follow open source code of conduct

**Pull request closed without merging**
