### PR TITLE
Footer alignment 

### PR DESCRIPTION
**Pull request by Molza01**
# Related Issue

None

Fixes:  #4539 

# Description

There was multiple pages in which the footer was aligned improperly and in few pages there was bug too.
I had styled the footer page and have linked to all the pages and also the pages which had contained bug has been resolved too.

#4539 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)
Before!!
Screenshot 2024-11-04 014458

After!!

Screenshot 2024-11-04 031450

Bug Before!!
Screenshot 2024-11-04 013857

Bug After!!
Screenshot 2024-11-04 031947

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Molza01** [comment]
Why PR Description Check error is coming?
@anuragverma108

**Comment by abhi03ruchi** [comment]
events page footer  is ok , but not in ur deployment . u can uncommit ur changes .

**Comment by abhi03ruchi** [comment]
https://swapreadsconnect.netlify.app/assets/html/about1.html delete this page .u can create in separate pr ...

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-05 at 10 15 03 PM
saare pages mein aisa footer daaldo . ( about us page wala)

**Review by Molza01 — COMMENTED** [review]
Change in font size.

**Comment by Molza01** [comment]
I have Changed and styled the footer of event.html and comsp.html.


Screenshot!!

Screenshot 2024-11-08 011351

**Pull request closed without merging**
