### PR TITLE
improving pages in profile dropdown 

### PR DESCRIPTION
**Pull request by Riyachauhan11**
# Related Issue
None

Fixes:  #4610

# Description
I have enhanced the appearance of edit profile and my profile pages and corrected the links in profile page.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

before and after:

https://github.com/user-attachments/assets/9fa46046-1610-4877-88b9-1e54ad062480

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Riyachauhan11** [comment]
should i work on the help page in profile dropdown?

**Comment by abhi03ruchi** [comment]
nice , just fix the home button on top right corner of the page . and its [My Profile]

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-05 at 8 20 45 AM

remove this footer , just keep the part below the horizontal line .

**Comment by Riyachauhan11** [comment]
> nice , just fix the home button on top right corner of the page . and its [My Profile]

what do you want me to change there? i didnt quite get it

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/250f6ff8-d209-4145-b5ad-4fadce4b7c31

**Pull request merged**
