### PR TITLE
Fixed the responsiveness of cards of About page

### PR DESCRIPTION
**Pull request by vishanurag**
# Related Issue

Fixes:  #2763

# Description

- Fixed the responsiveness of cards of About page in mobile-view.
- Now, the page will look good on mobile view as well.

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

Screenshot 2024-08-07 201155

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by vishanurag** [comment]
@huamanraj @anuragverma108 please review & merge my pull-request under GSSoC'24

**Comment by vishanurag** [comment]
@RitiChandak can you please add that level1 label in this pr please 🙏

**Comment by huamanraj** [comment]
> @RitiChandak @huamanraj @anuragverma108 can you please add that level1 label in this pr please 🙏 because I will not get points if level labels are not added in this pr. Hope you understand



sorry for responding late! its done

**Comment by vishanurag** [comment]
> > @RitiChandak @huamanraj @anuragverma108 can you please add that level1 label in this pr please 🙏 because I will not get points if level labels are not added in this pr. Hope you understand
> 
> sorry for responding late! its done

@huamanraj can you please do the same for pr #2750 🙏

**Pull request merged**
