### PR TITLE
SUCCESSFULLY  ENHANCED THE CONTACT US FORM.

### PR DESCRIPTION
**Pull request by dnyanesh99borse**
**### _SUCCESSFULLY  ENHANCED THE CONTACT US FORM._**

# Related Issue: #3580 "ENHANCEMENT OF THE CONTACT US FORM"
SOLVED ISSUE: #3580 

Fixes:  #3580
# Description
**The "Contact Us" form has undergone significant enhancements, making it both visually appealing and more interactive for users. Several key improvements were made that contribute to upgrading the overall user interface (UI) and enhancing the user experience (UX):**

**Icons Integration:** You successfully added respective icons to the labels of each field, making it easier for users to identify the purpose of each input section. This visual aid helps improve usability, making the form more user-friendly.

**Input Fields and Text Area Enhancements:** The input fields and text area were adjusted for size, ensuring that they fit perfectly within the layout. This improvement provided a balanced and well-organized form structure, which is crucial for maintaining an attractive and professional appearance.

**Background and Container Design:** You enhanced the background of the container where the form resides. By applying advanced CSS, you were able to create a visually appealing backdrop that complements the overall design. The background effects not only make the form look more professional but also improve the focus on the content.

**Hover Effects:** One of the standout features you implemented was the hover effect. When users hover over the form or its elements (such as input fields, buttons, etc.), dynamic effects are triggered, which make the interaction more engaging. This contributes to creating an intuitive and interactive experience for the users, making them feel more involved with the form.

**Button Enhancements:** The submit button also received special attention. You integrated hover effects that make the button visually change when hovered over, which enhances the call-to-action functionality. By creating an interactive button, you provided users with a more responsive and engaging experience.

**Overall User Interface Upgrade:** Each section of the form now has a polished, professional look, with careful attention to detail. The interactive elements, combined with the visual design improvements, create an inviting environment for users. The form is easy to understand, attractive, and functional, improving the flow of interaction.

**These updates contribute to a seamless and upgraded user interface and greatly enhance the overall user experience. The result is a professional, interactive, and highly effective "Contact Us" form that is visually appealing, responsive, and user-friendly.**

SOLVED ISSUE: #3580 

# Type of PR

- [ ] Bug fix
- [ *@*] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

**BEFORE:**
image

**AFTER THE UPDATION:**
_VIDEO:_

https://github.com/user-attachments/assets/d1630e9d-5842-4df1-bde5-fbd1e9b3a887
-----------------------------------------------------------------------------------------------------------------------------------------
image
-----------------------------------------------------------------------------------------------------------------------------------------
image

# Checklist:

- [ * ] I have made this change from my own.
- [ * ] I have taken help from some online resources.
- [ * ] My code follows the style guidelines of this project.
- [ * ] I have performed a self-review of my own code.
- [ * ] I have commented my code, particularly in hard-to-understand areas.
- [ * ] I have made corresponding changes to the documentation.
- [ * ] My changes generate no new warnings.
- [ * ] I have tested the changes thoroughly before submitting this pull request.
- [ * ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by dnyanesh99borse** [comment]
SIR I HAD SUCCESSFULLY SOLVED THE ISSUE AND ENHANCE THE USER INTERFACE OF THE CONTACT FORM AND TAKE IT TO THE NEXT LEVEL. NOW I AM HUMBLY  REQUESTING YOU TO PLEASE REVIEW THE CHANGES AND MERGE THE PR WITH RESPECTIE POINTS. ~Thankyou @anuragverma108

**Comment by sailaja-adapa** [comment]
can u make the heading move to left side and also update branch too instead of alert add toast message i will assign level 2 if it is good since for now u added only icons to that

**Comment by dnyanesh99borse** [comment]
OK FOR SURE YOU WILL RECEIVE IT UPTO MIDNIGHT. THANKS FOR THE CO-OPERATE @anuragverma108

**Comment by abhi03ruchi** [comment]
resolve conflicts @dnyanesh99borse

**Comment by dnyanesh99borse** [comment]
RESPECTED SIR , AS YOU SAID I HAD SUCCESSFULLY UPDATE THE CODE AND INTEGRATED THE CHANGES AND SOLVED THE ISSUE WHERE I TOOK UP THE TITLE OR THE LABELS OF THE ALL THE INPUT FIELDS OF THE CONTACT FORM TO THE CENTER AND ALSO MADE IT INTERACTIVE . 

AND ALONG WITH THAT I ALSO REMOVE THE UNNECCESSARY CODE OR BUG CODE AND ENHANCES THE PROJECT:

**Comment by sailaja-adapa** [comment]
Removw duplicate sections of donation @dnyanesh99borse

**Comment by dnyanesh99borse** [comment]
> Remove duplicate sections of donation @dnyanesh99borse and update branch too

MAM, I ALREADY REMOVED THAT. SORRY BUT CAN YOU PLEASE REVIEW ONCE I DID IT AND REMOVED ALL THE DUPLICATES. IS THERE ANY CONFLICT STILL PLEASE LET ME UNDERSTAND. ~Thankyyou

**Comment by sailaja-adapa** [comment]
See deployment preview once

**Comment by dnyanesh99borse** [comment]
yes mam got it extremely sorry. am resolving it just a minute. please

**Comment by sailaja-adapa** [comment]
No problem resolve slowly @dnyanesh99borse

**Comment by dnyanesh99borse** [comment]
MAM I THINK I FINALLY RESOLVED THE ISSUE CAN YOU PLEASE REVIEW AND LET ME KNOW .

**Comment by dnyanesh99borse** [comment]
okay. thankyou

**Pull request closed without merging**
