### PR TITLE
solved the bug of footer responsive

### PR DESCRIPTION
**Pull request by psychic-coder**
I Made the footer responsive and solved the bug , please add the bug under GSSoC'24 and add the level to the problem .
The modified footer should look like this . If there's any issue please free to contact.

Issue #479 

Screenshot 2024-05-17 at 3 53 50 AM

Screenshot 2024-05-17 at 3 54 20 AM

Screenshot 2024-05-17 at 3 53 39 AM

Screenshot 2024-05-17 at 3 39 56 AM

### CODE REVIEW

**Comment by psychic-coder** [comment]
If there's any issue with the code please feel free to tell me and please mark the bug under GSSoC'24 , and add the level

**Comment by huamanraj** [comment]
> If there's any issue with the code please feel free to tell me and please mark the bug under GSSoC'24 , and add the level

one pull and then try to push there is some conflicts

**Comment by psychic-coder** [comment]
@huamanraj can you please check and inform me

**Comment by anuragverma108** [comment]
image
Conflicting files
assets/css/style.css

Solve the conflicting issues & raise PR again

**Pull request closed without merging**
