### PR TITLE
Added dark mode in Community section and fixed the darkmode activation and index.html bugs.

### PR DESCRIPTION
**Pull request by RB137**
# Related Issue

Fixes the dark mode in community spotlight section. Already done a PR regrding this but there is some issue with index.html. Fixed all the issues and now the community section darkmode is working properly.

Fixes:  #3724 

# Description

Summary of Changes: Fixed the misalignment of the theme toggle and user logo within the navbar. Also, resolved the issue where the dark theme was not applied in the Community Spotlight section.

Issue Fixed: #3724 :  the community section darkmode is working properly.

Motivation and Context: Improves user experience by aligning elements properly and ensuring the dark theme works as expected.

Dependencies: No additional dependencies required.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before : 
Screenshot 2024-10-20 010959

After Darkmode activated :
Screenshot 2024-10-20 011234

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RB137** [comment]
I have completed the task. Please review it and kindly accept my PR. @anuragverma108 @sailaja-adapa @abhi03ruchi

**Comment by RB137** [comment]
@sailaja-adapa 
I have fixed the index.html issue as per your suggestion in this PR and reviewed the vercel deploy-preview. 

Please review it and kindly accept my PR. @anuragverma108 @sailaja-adapa @abhi03ruchi

**Comment by sailaja-adapa** [comment]
delete index.html file @RB137

**Comment by RB137** [comment]
@sailaja-adapa 
I'm unsure which index.html file is causing the issue. Should I delete the one inside assets/html/ or the one outside? I'm confused about which is the current index.html for the site. Could you help me resolve this?

In deploy-preview from my side it's working fine : 

https://github.com/user-attachments/assets/a4558f85-a269-4230-be60-e01f8365d2b0

**Comment by sailaja-adapa** [comment]
just work with updated branch and copy your code like where u made changes don't change anything on index.html file @RB137

**Pull request closed without merging**
