### PR TITLE
I've added html as well as css file for the quicklinks and some changes made.

### PR DESCRIPTION
**Pull request by ark0078**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.)#3101 solved

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by ark0078** [comment]
@sailaja-adapa kindly check and merge it

**Comment by sailaja-adapa** [comment]
post image where u made changes @ark0078

**Comment by ark0078** [comment]
@sailaja-adapa the quicklinks were not properly aligned in a place...I've aligned them in a correct column and it is now looking better..hope this helps ..kindly do merge it

**Comment by ark0078** [comment]
Screenshot (222)
@sailaja-adapa see here...all are in one column now

**Comment by ark0078** [comment]
@sailaja-adapa do you want me to change anything here??please do let me know otherwise you can close it.....

**Comment by sailaja-adapa** [comment]
@ark0078  i already merged your PR no need of changes anything

**Comment by ark0078** [comment]
@sailaja-adapa okay..thanks..I was thinking it could cause a problem because the issue #3101 hasn't been closed yet..that's what i was asking

**Comment by sailaja-adapa** [comment]
adapasailaja07@gmail.com

**Comment by ark0078** [comment]
@sailaja-adapa check your mail...if you face any issues,do let me know.Waiting for your reply

**Comment by sailaja-adapa** [comment]
yeah ok i will check tomorrow and update u :)

**Comment by ark0078** [comment]
@sailaja-adapa lol...check now...you're a project maintainer..you've lots of work to do...you won't be remembering it..don't mind..actually am saying the facts...do let me know what you think

**Comment by sailaja-adapa** [comment]
don't worry i will check @ark0078 and contact me in linkedin it would be better rather than here

**Comment by sailaja-adapa** [comment]
okay

**Pull request merged**
