### PR TITLE
Rate us modal fixed

### PR DESCRIPTION
**Pull request by sau-mili**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #2124 

# Description
- Rate us modal now active when clicked
- UI of rate us modal also fixed
- Added submit button styles
- JS function call works now

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Screenshot 2024-06-26 182734

Screenshot 2024-06-26 182414
Screenshot 2024-06-26 182421

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sau-mili** [comment]
@anuragverma108 please check this

**Comment by RitiChandak** [comment]
@sau-mili, please ensure that the changes are applied to all other pages to maintain uniformity, similar to the 'About Us' page and the 'Book List for Swapping' page, and verify them all.

**Comment by sau-mili** [comment]
Okay

**Comment by sau-mili** [comment]
which one do you think is better? 
Screenshot 2024-06-27 211748
Screenshot 2024-06-27 211800
I will add the one you say. In my edits, I created a modal pop up, but the about page and book swap page is linking to a new HTML page not a modal. Which one should I add?

**Pull request closed without merging**
