### PR TITLE
Animation on scroll

### PR DESCRIPTION
**Pull request by Priyanshi0112**
# Related Issue
none

Fixes:  #4124 

# Description
Added  scroll animations to your genre page  transforms the reading experience, making it more dynamic and engaging. These animations guide readers through the content, highlight key information, and create a visually appealing narrative flow.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/7e805330-11ba-4bad-bb5d-a9612b0ddd58

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
resolve branch conflicts .

**Comment by Priyanshi0112** [comment]
> resolve branch conflicts .

Done

**Comment by abhi03ruchi** [comment]
u may also enhance the UI of the cards in this genre page .
also there are too many cards , so could add a load more button in the section.

u may work on these issues and raise pr .

**Comment by Priyanshi0112** [comment]
@abhi03ruchi okay I'll  work on that issue

**Comment by Priyanshi0112** [comment]
@abhi03ruchi  
 I have made load more button but what issue number should I write for PR  ?

**Comment by abhi03ruchi** [comment]
create a new issue , and then raise pr  .

**Pull request merged**
