### PR TITLE
I corrected the position of navbar and also added floating effect

### PR DESCRIPTION
**Pull request by Shobhit1729Aryan**
BEFORE

https://github.com/user-attachments/assets/77c3d579-cc81-4103-9202-4eb279cab582

AFTER

https://github.com/user-attachments/assets/e984cbe0-855b-421f-bad8-f1c9114e6aaa

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
there is overflow issue in the navbar. Plz correct it . Check in inspect mode . 

https://github.com/user-attachments/assets/eae6e45b-8f44-4073-b2f0-f8906fd48788

**Comment by Shobhit1729Aryan** [comment]
@anuragverma108 please have a look at it

**Comment by Shobhit1729Aryan** [comment]
> there is overflow issue in the navbar. Plz correct it . Check in inspect mode .
> 
>  Screen.Recording.2024-10-15.at.6.32.37.AM.mov

Ok , I will fix it

**Comment by Shobhit1729Aryan** [comment]
@abhi03ruchi kindly have a look in it please

**Comment by sailaja-adapa** [comment]
@Shobhit1729Aryan resolve conflicts

**Comment by sailaja-adapa** [comment]
since this issue has been resolved work on new issue @Shobhit1729Aryan don't forget to work with updated branch

**Pull request closed without merging**
