### PR TITLE
solved issue #3073

### PR DESCRIPTION
**Pull request by Devanshu1603**
Fixes:  #3073

# Description

make the dropdown button work.

# Type of PR

- [*] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/fb2ff1fd-be7f-4fda-80b4-250f47ddc4db

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Devanshu1603** [comment]
@anuragverma108 Please review the PR and merge it accordingly.

**Comment by sailaja-adapa** [comment]
Can I post a video where you made changes @Devanshu1603

**Comment by Devanshu1603** [comment]
> Can u post a video where you made changes @Devanshu1603

ok i am posting one

**Comment by Devanshu1603** [comment]
@sailaja-adapa  I have updated the comment and added a video.

**Comment by sailaja-adapa** [comment]
Can you update the branch please

**Comment by Devanshu1603** [comment]
> Can you update the branch please

Can you please explain what to do. couldn't get it.

**Comment by sailaja-adapa** [comment]
U raised PR from a branch right 
go to that branch you can see update branch there this will help ur branch to be upto date since I made some changes in project

**Comment by Devanshu1603** [comment]
@sailaja-adapa  there is no options of updation 
Screenshot 2024-10-08 131144

**Comment by sailaja-adapa** [comment]
Ok leave it branch is upto date @Devanshu1603

**Pull request merged**
