### PR TITLE
new logo update on every navbar

### PR DESCRIPTION
**Pull request by heli0707**
# Related Issue 
UI related issue

Fixes:  #2302 

# Description
Updated the old logo with the new one on the navbar.  The task has been completed successfully.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
imageReplaced 

the old logo with the new one on the navbar and all other pages where the old logo was displayed.

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

CLOSE : #2302

### CODE REVIEW

**Comment by heli0707** [comment]
@RitiChandak 
review this and merge it!

**Comment by RitiChandak** [comment]
image
image

size of the logo is not same correct it and raise a new or reopen the PR

**Comment by heli0707** [comment]
I did it  Sent from Mail for Windows From: Riti ChandakSent: 04 July 2024 15:35To: anuragverma108/SwapReadsCc: Heli Detroja; AuthorSubject: Re: [anuragverma108/SwapReads] new logo update on every navbar (PR #2338) image.png (view on web)image.png (view on web)size of the logo is not same correct it and raise a new or reopen the PR—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by heli0707** [comment]
Both the issues have been closed, but I have not received any points. Why? Sent from Mail for Windows From: Riti ChandakSent: 04 July 2024 15:35To: anuragverma108/SwapReadsCc: Heli Detroja; AuthorSubject: Re: [anuragverma108/SwapReads] new logo update on every navbar (PR #2338) image.png (view on web)image.png (view on web)size of the logo is not same correct it and raise a new or reopen the PR—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request closed without merging**
