### PR TITLE
feat: improve Home/Index page responsiveness (Issue: #2919)

### PR DESCRIPTION
**Pull request by solanki03**
# Related Issue

BUG: Home/Index page isn't responsive #2919

Fixes:  #2919

# Description

I made the following changes to the project:
- Made the contact-container flexible to ensure proper layout on mobile.
- Used media queries to manage layout shifts at 768px and 480px screen widths.
- Centered the contact-card horizontally using flexbox.
- Adjusted form and button widths for mobile to avoid overflow or shrinkage issues.
- Maintained a clean layout with consistent margins, padding, and element stacking on smaller screens.
- Removed repeated lines of code and placed them in the style.css file.

### Impact:
- Better mobile experience with improved form usability.
- Visual alignment improvements for the contact-card.

 Issue No. : #2919

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before: 
Screenshot 2024-10-03 213017

Screenshot 2024-10-03 213034

After:
Screenshot 2024-10-04 211610

Screenshot 2024-10-04 211641

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@solanki03 resolve conflicts

**Comment by solanki03** [comment]
> @solanki03 resolve conflicts

@sailaja-adapa I have resolved the conflicts. Please review it and let me know if any changes are needed.

**Comment by sailaja-adapa** [comment]
Still Exists @solanki03

**Comment by solanki03** [comment]
@sailaja-adapa I resolved the conflicts, merged it with the main branch, and made a pull request from the branch I created. Sorry for the mistake. Can I create another pull request from the main branch? 

image

**Comment by sailaja-adapa** [comment]
Yeah create new PR @solanki03

**Pull request merged**
