### PR TITLE
Fixed the UI of the book cards

### LINKED ISSUE #3449: BUG:Make book info cards non-clickable and improve card size for better UI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Type: UI/UX Improvement

Summary:
Currently, the three cards displaying book information on the website are clickable, but they are not intended to act as links or interactive elements. Additionally, the cards appear too large, making the interface look unappealing. This impacts the user experience and visual balance of the page.

Image : 
Screenshot from 2024-10-14 19-35-34

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by LaibaKhalil61**
Fixes:  #3449

# Description

There was an issue with the cards on the books page. They were too empty and were clickable. So I added content in it and made them unclickable.
I fixed #3449 .

# Type of PR

- [ ] Bug fix

# Screenshots
After changing the UI:
Screenshot from 2024-10-19 02-49-40

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
1) There is blank space in the boxes at the end, which doesn't look good.  fix it.
2) [Explore new worlds] heading is horizontally aligned with the boxs .  Bring the heading outside , like other heading .

**Comment by LaibaKhalil61** [comment]
By the second point , do you mean it should appear above the cards like acclaimed authors heading ? Or am I wrong?

**Comment by abhi03ruchi** [comment]
> https://deploy-preview-3730--swapreadsconnect.netlify.app

yes .

**Comment by LaibaKhalil61** [comment]
Okay , I've made the necessary changes so I'll raise the PR then

**Pull request merged**
