### PR TITLE
Modify the Transition in Rate Us section

### PR DESCRIPTION
**Pull request by ShaikHafiza**
# Related Issue #3359 

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.) #3359 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by ShaikHafiza** [comment]
Completed this issue , review and requesting you to merge.

**Comment by sailaja-adapa** [comment]
create PR with good description @ShaikHafiza and screenshot too

**Comment by ShaikHafiza** [comment]
But how can we take a screenshot of a transition @sailaja-adapa

**Comment by sailaja-adapa** [comment]
record a video or something u should say what changes u made in clear while creating PR

**Comment by ShaikHafiza** [comment]
Ok @sailaja-adapa I'll make another PR

**Pull request closed without merging**
