### PR TITLE
Added dark mode in Community Spotlight section and fixed the darkmode activation bugs.

### PR DESCRIPTION
**Pull request by RB137**
# Related Issue

Fixes the dark mode in community spotlight section.

Fixes:  #3724 

# Description

Summary of Changes: Fixed the misalignment of the theme toggle and user logo within the navbar. Also, resolved the issue where the dark theme was not applied in the Community Spotlight section.

Issue Fixed:

Motivation and Context: Improves user experience by aligning elements properly and ensuring the dark theme works as expected.

Dependencies: No additional dependencies required.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before : 
image

After darkmode activated : 
image

checked the deploy preview as instructed.

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RB137** [comment]
I have completed the task. Please review it and kindly accept my PR. @anuragverma108 @abhi03ruchi

**Comment by RB137** [comment]
I have activated the dark mode in Community spotlight section and reviewed the vercel deploy-preview as suggested in previous PR. lease review it and kindly accept my PR. @anuragverma108 @sailaja-adapa @abhi03ruchi

**Comment by RB137** [comment]
Will go through it and update the code by tonight.

**Comment by sailaja-adapa** [comment]
just copy the code of index.html from current website and paste it , it will be enough @RB137

**Comment by RB137** [comment]
Thanks, I'll check it out for sure.

**Comment by RB137** [comment]
I have to create another PR for the updates right! or is there any possibility to continue with this PR. @sailaja-adapa

**Comment by sailaja-adapa** [comment]
u can continue with this PR @RB137 or else your wish

**Pull request closed without merging**
