### PR TITLE
Updated Logo and Responsiveness

### PR DESCRIPTION
**Pull request by Madhuri36**
Fix: #231
I have done all the changes as mentioned in the issue.

Description: 

-I have updated the Logo to match with the website's UI. 
-The logo changes according to the light and dark mode. 
Before:
image
After:
image

image

-I have also added responsiveness for devices larger than 992px screen.

### CODE REVIEW

**Comment by anuragverma108** [comment]
Please note that this is not in line with our code of conduct. To ensure clarity and proper assignment tracking, please attach the issue number to your PR description. This helps us confirm that the issue is assigned to you. Kindly update your PR with the issue number and resubmit.

Example:
Fixes #123 - Brief description of the fix.

**Comment by Madhuri36** [comment]
I have added the issue number

**Comment by anuragverma108** [comment]
Great contribution to GSSOC'24! 🎉

**Comment by Madhuri36** [comment]
It is working on my Laptop. I have updated my fork too.
image

**Comment by anuragverma108** [comment]
Create PR again

**Pull request merged**
