### PR TITLE
Profile section

### PR DESCRIPTION
**Pull request by ChanchalTolani**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1737

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x ] I have made this change from my own.
- [x ] I have taken help from some online resources.
- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
image

**Comment by RitiChandak** [comment]
If you need any help contact me or any mentor

**Comment by ChanchalTolani** [comment]
It's fine in my repo . After writing pr how can it delete css code? I tried it many times

**Comment by RitiChandak** [comment]
create a new branch

**Pull request closed without merging**
