### PR TITLE
added a hover effect #2203

### PR DESCRIPTION
**Pull request by Abhinavagarwa**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.)

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Abhinavagarwa** [comment]
before
Screenshot 2024-07-01 at 6 14 21
<img width=
 AM" src="https://github.com/anuragverma108/SwapReads/assets/119868907/92865f98-8d03-49ac-a2aa-70adc175fcdd">

**Comment by Abhinavagarwa** [comment]
Screenshot 2024-07-01 at 6 14 21 AM
before

**Comment by Abhinavagarwa** [comment]
Screenshot 2024-07-01 at 6 21 46 AM
after

**Comment by Abhinavagarwa** [comment]
after

**Comment by Abhinavagarwa** [comment]
in this i have just added an hover effect at the end of style.css in assets comparing to the main branch i have remained the interlaying of highlighting between author and price meaning when u hover at author price also highlights

**Comment by RitiChandak** [comment]
@Abhinavagarwa issue number??

**Comment by Abhinavagarwa** [comment]
> @Abhinavagarwa issue number??

#2203

**Pull request merged**
