### PR TITLE
completed work

### PR DESCRIPTION
**Pull request by abhi200446**
image
completed navbar @sailaja-adapa akka

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
good work @abhi200446

**Comment by sailaja-adapa** [comment]
work on fixing donation section and also remove unnecessary text on navbar which is appearing in home page i.e -->

**Comment by abhi200446** [comment]
ok akka

**Comment by sailaja-adapa** [comment]
Try to fix Navbar on all pages with good allignment and include all options remove icons

**Comment by abhi200446** [comment]
@sailaja-adapa akka clarity ga cheppava em changes cheyalo donate section lo

**Pull request merged**
