### PR TITLE
Responsiveness Optimization for Improved User Engagement of login page

### PR DESCRIPTION
**Pull request by Bhupendrakumar20**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4029 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Bhupendrakumar20** [comment]
@anuragverma108 kindly check out the solution pls...kindly go through my PR...

**Comment by abhi03ruchi** [comment]
the login page is already responsive . only the navbar is not visible in mobile view . 

and it is not visible in ur changes too .

**Comment by abhi03ruchi** [comment]
also there are branch conflicts . 

work on adding the navbar in mobile view , everything else is ok .

**Comment by Bhupendrakumar20** [comment]
ok @abhi03ruchi ..working on it..

**Pull request closed without merging**
