### PR TITLE
implementing Multilingual support

### PR DESCRIPTION
**Pull request by Anjankumarkamalapur**
<h2>Implementation of Multilingual support</h2>

# Description

This change introduces multilingual support to the application, allowing users to access the user interface in multiple languages. This addresses the issue of limited accessibility for users who do not speak the default language.

Fixes:  #848 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

[Watch the video]

### CODE REVIEW

**Comment by huamanraj** [comment]
> <h2>Implementation of Multilingual support</h2>
> 
> # Description
> 
> This change introduces multilingual support to the application, allowing users to access the user interface in multiple languages. This addresses the issue of limited accessibility for users who do not speak the default language.
> 
> Fixes:  #848 
> 
> ## Type of change
> 
> 
> 
> - [ ] Bug fix (non-breaking change which fixes an issue)
> - [X] New feature (non-breaking change which adds functionality)
> - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> - [X] This change requires a documentation update
> 
> # Checklist:
> 
> 
> - [X] I have made this from my own
> - [X] I have taken help from some online resourses 
> - [X] My code follows the style guidelines of this project
> - [X] I have performed a self-review of my own code
> - [ ] I have commented my code, particularly in hard-to-understand areas
> - [ ] I have made corresponding changes to the documentation
> - [ ] My changes generate no new warnings
> 
> 
> # ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
> 
> [Watch the video]
> 
> 
> 
> 
> 
> 
> 
> 

the position should be anywhere on top! @Anjankumarkamalapur

**Comment by Anjankumarkamalapur** [comment]
@anuragverma108 translation layer provided in the navbar in a structured manner

**Comment by huamanraj** [comment]
> @anuragverma108 translation layer provided in the navbar in a structured manner

there are some conflicts that resolve and make another PR i will merge that

**Comment by Anjankumarkamalapur** [comment]
@anuragverma108 Done

**Pull request closed without merging**
