### PR TITLE
Added the testimonials.

### PR DESCRIPTION
**Pull request by sharmi4590**
Hello @anuragverma108 
Solved issue #374 
I have added the testimonials and the design matches your interface. When a card is hovered it flips back. and I also made it as slider.
Screenshot (398)
Screenshot (399)
It is responsive as well.
Screenshot (400)
Screenshot (401)
Thank you!

### CODE REVIEW

**Comment by sharmi4590** [comment]
Hey @anuragverma108 
Without write access how will add testimonials , since it is showing as conflict.

**Comment by anuragverma108** [comment]
image

Solve the conflicting issues in index.html and raise PR again.

**Comment by sharmi4590** [comment]
Hey @anuragverma108 
The problem here is that as you have not given write access to the index.html I am not able to add anything in the file .
To solve the above conflicts I have to delete all the testimonial code and then it would be of no use. As you can see the PRs you have closed without merging are also having same problems. Changing styles in css won't occur this problem but adding a new component will do.
So please one give access to the index.html , then this issue will be resolved.
Thank you.

**Comment by sharmi4590** [comment]
The conflicts its showing marked red is not a conflict but an added code of testimonials itself

**Comment by anuragverma108** [comment]
Just clone the repo in your local host & Make changes in index.html

**Pull request closed without merging**
