### PR TITLE
added give aways page to the website

### PR DESCRIPTION
**Pull request by sahithinandikula**
# Related Issue

Fixes:  #4191 

# Description
I have added give aways section to the website

#4191 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/2292cc04-571b-4fe1-a835-cd12b8acda7a

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
from where can the user get to the page ?

**Comment by sahithinandikula** [comment]
@abhi03ruchi I have added the giveaway link to footer(quick links)

**Comment by abhi03ruchi** [comment]
chk deploy preview . the website is totally messed up , after u resolved conflicts

**Comment by abhi03ruchi** [comment]
work on updated branch .

**Comment by sailaja-adapa** [comment]
work with updated branch and raise new PR @sahithinandikula

**Pull request closed without merging**
