### PR TITLE
fix the footer link issue in diverse literacy section

### PR DESCRIPTION
**Pull request by adityalaxkar123**
now footer link is working in  diverse literacy section

after improving

https://github.com/user-attachments/assets/0e87eeec-f762-4a46-9343-044ff1449503

my issue no. is #4072

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
for pricing , redirect the user to the pricing section on the home page ( index.html)  . the pricing page , that u have linked to , does n't look good , and is redundant . 

so , remove that assets/html/pricing page .

**Comment by adityalaxkar123** [comment]
Ok

**Comment by adityalaxkar123** [comment]
review @abhi03ruchi

**Comment by abhi03ruchi** [comment]
this issue is there in other pages of benefit section as well . 

u may resolve this issue in all the pages  , and raise a pr .

**Comment by adityalaxkar123** [comment]
Ok

**Pull request merged**
