### PR TITLE
Community Spotlight Page issue

### PR DESCRIPTION
**Pull request by TBorundia**
Fixes:  #2823

# Description
Added similar header and footer like main page.
Improved UI to match website theme.
Made page responsive too.

# Type of PR

- [ ] Bug fix
- [X]  Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/96f479f8-431f-45af-874e-621accaabdfb

https://github.com/user-attachments/assets/153220fd-408f-4945-9634-c71aa10b90ad

# Checklist:
- [X] I have made this change from my own.
- [X]  I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X]  I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by TBorundia** [comment]
@huamanraj @anuragverma108 Sir,
Please review this PR as soon as possible because GSSoC'24 is closing today.

**Comment by huamanraj** [comment]
This branch has conflicts that must be resolved

Conflicting files
assets/html/comsp.html

fix ASAP i will merge it by today dont worry!!

**Comment by TBorundia** [comment]
@huamanraj Sir, Conflicts resolved !
Can you please assign it with level3 ?
Thank You!

**Comment by huamanraj** [comment]
> @huamanraj Sir, Conflicts resolved !
> Can you please assign it with level3 ?
> Thank You!


👍

**Pull request merged**
