### PR TITLE
Improve feedback section done !

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - https://github.com/anuragverma108/SwapReads/issues/4310
Done - #4311

https://github.com/user-attachments/assets/d2716c4f-2fe5-48ff-9f54-03149753badb

image

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@sailaja-adapa

**Comment by abhi03ruchi** [comment]
i have reverted ur changes . 

Screenshot 2024-11-01 at 9 29 10 AM

u have changed the  text color to white on home page . 

raise pr again .

**Comment by Subhajit-2023-44** [comment]
> i have reverted ur changes .
> 
> Screenshot 2024-11-01 at 9 29 10 AM
> u have changed the text color to white on home page .
> 
> raise pr again .

@abhi03ruchi What ?? I didn't understand..

**Comment by abhi03ruchi** [comment]
chk ur code , u had changed the text color to white on home page , due to which text wasn't visible properly .

**Comment by Subhajit-2023-44** [comment]
> chk ur code , u had changed the text color to white on home page , due to which text wasn't visible properly .

Okay wait i will give new PR soon 😓😓

**Pull request merged**
