### PR TITLE
how to use website page added

### PR DESCRIPTION
**Pull request by Prabhu1702**
# Related Issue

Fixes:  #4000 

# Description

This pull request introduces a "How to Use the Website" HTML page. The page provides step-by-step instructions for new users to navigate the platform, including screenshots for easier understanding. The guide covers key features such as:

1) Signing up and logging in.
2) Searching and browsing books.
3) Adding a book for swapping.
4) Understanding the swap process.
5) Managing user account settings.
This will help users quickly learn how to use the website and reduce potential confusion for first-time visitors.

#4000 

# Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ x] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ x] I have made this change from my own.
- [ x] I have taken help from some online resources.
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ ]x I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
u have not integrated the page with the website . u can add the link of the page in Quick Links ( footer on home page ) .

**Comment by abhi03ruchi** [comment]
also enhance the UI so that the page matches the website theme. ( colors ) . chk terms and condition page for reference .

**Comment by abhi03ruchi** [comment]
are u working on this issue? as gssoc ext is about to end.

**Comment by Prabhu1702** [comment]
i am working but the changes i am trying to commit are getting stuck on loading page

**Comment by abhi03ruchi** [comment]
> i am working but the changes i am trying to commit are getting stuck on loading page

loading page ?

**Comment by sailaja-adapa** [comment]
work with updated branch and raise new PR @Prabhu1702

**Pull request closed without merging**
