### PR TITLE
Add details to books

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4419

# Description

This PR adds details to the books on the horror page.

issue #4419 
# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/83ac336d-4453-4d2b-8ec6-32a9e0b4848d

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
this is irrelevant issue . when we click on detail , the same title of book is displayed .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi If the details idea is fine, I can add the details for individual books rather than showing the titles

**Comment by abhi03ruchi** [comment]
ok , but the UI of this page doesnt look good . 

chk https://swapreadsconnect.netlify.app/assets/html/top10 , add flip cards similar to these for ur page . and on the backside u can add details   for individual books  , like on this page .

**Comment by abhi03ruchi** [comment]
enhance all ur pages in similar manner . u can copy the card code from this page and add to ur page .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi okay I will do the changes

**Pull request closed without merging**
