### PR TITLE
Feat:Added of reveal elements on scroll

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#2810

# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #2810 

# Description

Added of reveal elements on scroll

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/59b5c426-4462-48ec-bb6c-cd0183a2abc0

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@huamanraj @anuragverma108  please review the PR.

**Comment by Anjaliavv51** [comment]
@huamanraj @anuragverma108 please review the PR.

**Comment by Anjaliavv51** [comment]
@huamanraj @anuragverma108 please review the PR.

**Comment by huamanraj** [comment]
This branch has conflicts that must be resolved

Conflicting files
assets/html/comsp.html

fix ASAP

**Comment by Anjaliavv51** [comment]
@huamanraj conflicts are resolved please review the PR.

**Comment by huamanraj** [comment]
@Anjaliavv51 good work 🚀🚀

**Comment by Anjaliavv51** [comment]
@huamanraj please add labels

**Comment by Anjaliavv51** [comment]
@huamanraj please add level and GSSOC labels

**Comment by huamanraj** [comment]
> @huamanraj please add level and GSSOC labels



ohh sorry now it added!

**Pull request merged**
