### PR TITLE
Adds User Profile Management, Book Review and Rating, Browsing History, Book Recommendations, Favorite Books.

### LINKED ISSUE #2265: Feat: Add User Profile Management, Book Review and Rating, Browsing History, Book Recommendations, Favorite Books.
### Describe the feature

This application now includes user profile management for updating email addresses, the ability to leave reviews and ratings for books, tracking users' browsing history, providing book recommendations based on that history, and allowing users to mark books as favorites. These new features enhance user interaction and personalization without requiring email configurations.

### Add ScreenShots

Screenshot 2024-06-23 at 1 35 16 PM

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by arunimaChintu**
# Related Issue
Closes #2265 
Fixes:  #2265 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by arunimaChintu** [comment]
@anuragverma108 Please assign it a level 3 as a lot of features were involved in 1 PR.

**Comment by arunimaChintu** [comment]
@anuragverma108 Please merge it and assign it to a greater level according to you if you feel it right

**Comment by RitiChandak** [comment]
Hi @arunimaChintu, please ensure to wait for the issue to be assigned to you before proceeding next time.

**Comment by arunimaChintu** [comment]
Okay! Sure

**Comment by arunimaChintu** [comment]
@anuragverma108 Could you please assign it a level 3 , as it has a lot of features merged in a single issue

**Comment by huamanraj** [comment]
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change

**Pull request closed without merging**
