### PR TITLE
solved #4491  added quiz to ramayan

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
added quiz to ramayan
Fixes:  #4491 

https://github.com/user-attachments/assets/fa2c6773-cbb0-4ba4-bfde-eb605b53409b

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@sailaja-adapa  @abhi03ruchi mam pleasemerge this kindly add level2 mam

**Comment by sailaja-adapa** [comment]
i am not able to see your changes @KapuluruBhuvaneswariVspdbct once check deployment preview and also one thing is that don't remove the details about that book just simply add quiz option below information

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Added quiz to ramayan book

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Mam the book info is in seperate page mam it is the quizes page where  quizes on books are present

**Comment by abhi03ruchi** [comment]
> Mam the book info is in seperate page mam it is the quizes page where quizes on books are present

remove quizzes from navbar and add it like this ( QUIZZES BUTTON )-->

Screenshot 2024-11-03 at 2 12 00 PM

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok mam

**Pull request merged**
