### PR TITLE
Fixed Dark Mode Toggle in Community Section and Updated Navbar to Latest Version

### PR DESCRIPTION
**Pull request by RB137**
# Related Issue

Fixed issue for activating dark mode. The dark mode toggle is now working fine inside the Community section. Additionally, updated the navbar with the latest version. Fixed issue #3724 

Fixes:  #3724 

# Description

This pull request fixes the dark mode activation issue. The dark mode toggle is now functioning properly inside the Community section. Additionally, the navbar has been updated to the latest version, ensuring consistency across the application.

- Motivation: 
 The dark mode toggle was previously not working in the Community section, and the navbar needed to be updated for better compatibility and user experience.
- Dependencies: 
No new dependencies were introduced with this change.

Fixed issue #3724 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
### Before: 
Darkmode toggle not working inside Community section

https://github.com/user-attachments/assets/c8b0a68f-8c70-426b-a996-f1ab02752e23

Screenshot 2024-10-23 014540

### After: 
Darkmode toggle working properly and NavBar Updated inside Community section

https://github.com/user-attachments/assets/8eeecd08-1531-4d38-a0fa-264a6d62ae00

Screenshot 2024-10-23 014914

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RB137** [comment]
Hi @sailaja-adapa, based on your suggestion from my previous PR, I’ve made the necessary changes for dark mode and updated the navbar slightly inside Community section. 

Please review and kindly approve my PR, and add the gssoc-ext, hacktoberfest, and hacktoberfest-accepted labels. 
@sailaja-adapa @anuragverma108

**Comment by abhi03ruchi** [comment]
chk the footer in dark mode . 
the navbar doesnt look good in dark mode . keep the color combo like that in home page dark mode .

**Comment by RB137** [comment]
@abhi03ruchi, I’ve fixed the dark mode toggle issue #3724 and made some updates to the navbar. This is a level 1 issue, so please approve my PR and close the issue #3724.

Regarding your suggestions (making the navbar consistent with the homepage and updating the footer dark theme in the community section), I’ll handle those in a new PR under a separate issue, as they are more complex and likely fit a level 2 task.

For now, please approve the current PR for the issue #3724 and close it, and I’ll address the other changes in the next PR.
@sailaja-adapa @anuragverma108

**Comment by RB137** [comment]
@sailaja-adapa @anuragverma108 I’ve been working on fixing the dark theme toggle for several days, and previous PRs weren’t accepted due to index.html changes. This PR works fine in the deploy preview, so please approve it.

**Comment by sailaja-adapa** [comment]
create new issue on fixing the profile logo into navbar in that page @RB137

**Comment by RB137** [comment]
@sailaja-adapa Thanks for merging! Soon I will work on that.

**Pull request merged**
