### PR TITLE
Icon-Based Navbar Enhancement

### LINKED ISSUE #995: Feat: Icon-Based Navbar Enhancement
### Describe the feature

We propose to enhance the website's navigation bar (navbar) by replacing text-based menu items with visually appealing icons. This change aims to improve user experience, making the navbar more effective, engaging, and modern.

Objective:

Increase user engagement and satisfaction by creating a visually stimulating navbar.
Enhance the aesthetic appeal of the website, aligning it with contemporary design trends.
Improve the usability of the navbar, making it quicker and easier for users to navigate the site.

Benefits:

Visual Appeal: Icons are more visually appealing than text, providing a sleek and modern look to the website.
Recognition and Speed: Icons can be recognized and processed faster than text, allowing users to find and select the desired navigation options more quickly.
Space Efficiency: Icons take up less space, allowing for a cleaner and more organized navbar.
Universal Understanding: Well-designed icons can be universally understood, reducing language barriers for international users.

Conclusion:
Transitioning from a text-based to an icon-based navbar is a strategic enhancement aimed at improving the overall user experience. By making navigation more intuitive and aesthetically pleasing, we expect to see higher user satisfaction and engagement rates.

### Add ScreenShots

Screenshot 2024-05-29 122419

we can make the navbar as like below one..
Screenshot 2024-05-29 122807
Screenshot 2024-05-29 122821

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Dhevamuthu**
# Related Issue

We propose to enhance the website's navigation bar (navbar) by replacing text-based menu items with visually appealing icons. This change aims to improve user experience, making the navbar more effective, engaging, and modern.

Fixes:  #995 

# Description

Changes Made:
**Navigation Items Update:**
Replaced text-based navigation links with corresponding icons for sections such as Home, Benefits, Genre, Contact, Rate Us, and Login/Signup.
Ensured that the "More" dropdown menu item now uses an icon instead of text, while retaining the dropdown functionality.

**Hover Effect:**
Implemented a hover effect that enlarges the icons when the user hovers over them.

**Styling Adjustments:**

- Used flexbox to stack icons and their corresponding text vertically within the navigation items.
- Added inline styles to adjust the font size for specific dropdown menu items where necessary.

fixed #995 

# Type of PR

- [ ] Bug fix
- [ ✅] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

**Before**: Navigation links displayed as text.
image

**After**: Navigation links displayed as icons, which enlarge on hover.
image
image

# Checklist:

- [✅] I have made this change from my own.
- [✅] I have taken help from some online resources.
- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [✅] I have tested the changes thoroughly before submitting this pull request.
- [✅] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by huamanraj** [comment]
the icon doesnt look similar one is filled one is just empty ones make it just unfilled it will go good also
I regret to inform you that the project code has undergone some major changes. Consequently, you will need to pull the new code and make the necessary adjustments to the codebase. After making these changes, please create a new pull request.

I apologize for any inconvenience this may cause and appreciate your understanding of the situation. Thank you for your cooperation.

**Comment by Dhevamuthu** [comment]
I can't understand..please explain @huamanraj 

What do u want me to do

**Comment by huamanraj** [comment]
> I can't understand..please explain @huamanraj 
> 
> What do u want me to do



here is two different type of styles 
one is filled and one is unfilled with black 
use any one filled or unfilled for all icon!

**Comment by Dhevamuthu** [comment]
okay okay.. will change and update u soon

**Comment by huamanraj** [comment]
> okay okay.. will change and update u soon

great 👍

**Pull request closed without merging**
