### PR TITLE
Add Cursor Tail Effector in Authors & Tips page done ! 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add Cursor Tail Effector in Authors & Tips page done -  #4158

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
there are some other pages where special cursor is missing --> map page and chk all home page footer page links  . 

u may work on this issue and raise pr .

**Comment by Subhajit-2023-44** [comment]
> there are some other pages where special cursor is missing --> map page and chk all home page footer page links .
> 
> u may work on this issue and raise pr .

okay i will try ...

@abhi03ruchi please upgrade the level 1 to 2 in this PR - #3960

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi Can I add this type of translation tool to all pages?, because this tool better than the existing translation tool & the existing translation tool only present in home page which doesn't look good..


like this -

image
Screenshot 2024-10-28 165352

**Comment by abhi03ruchi** [comment]
a contributor is already working on this issue .

u may work on other issues .

**Pull request merged**
