### PR TITLE
🛠️ FIX : Missing mouse pointer effect on some page

### PR DESCRIPTION
**Pull request by akash70629**
# Related Issue

“None”

Fixes:  #4627

# Description

On the some page, the mouse pointer effect was missing now it's added.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by akash70629** [comment]
@abhi03ruchi Please review and merge the PR. Please add a level 3 label.

**Comment by abhi03ruchi** [comment]
add in blog page , assets/html/checkout page too .

**Comment by akash70629** [comment]
> add in blog page , assets/html/checkout page too .

done . Please check and merge .

**Comment by abhi03ruchi** [comment]
assets/html/checkout page isme bhi

**Comment by abhi03ruchi** [comment]
benefits section ke pages chk karo , https://swapreadsconnect.netlify.app/#benefits
https://swapreadsconnect.netlify.app/intriguing-mysteries also

**Comment by akash70629** [comment]
> benefits section ke pages chk karo , https://swapreadsconnect.netlify.app/#benefits https://swapreadsconnect.netlify.app/intriguing-mysteries also

@abhi03ruchi intriguing-mysteries page ka to kar diya, lekin #benefits  me kya problem hai samjha nehi !! kya hai problem ?

**Comment by abhi03ruchi** [comment]
> > benefits section ke pages chk karo , https://swapreadsconnect.netlify.app/#benefits https://swapreadsconnect.netlify.app/intriguing-mysteries also
> 
> @abhi03ruchi intriguing-mysteries page ka to kar diya, lekin #benefits me kya problem hai samjha nehi !! kya hai problem ?


https://swapreadsconnect.netlify.app/costefficient , https://swapreadsconnect.netlify.app/revitalize . i was saying chk pages in benefit section , add effect in pages which dont have mouse effect .

**Comment by akash70629** [comment]
> > > benefits section ke pages chk karo , https://swapreadsconnect.netlify.app/#benefits https://swapreadsconnect.netlify.app/intriguing-mysteries also
> > 
> > 
> > @abhi03ruchi intriguing-mysteries page ka to kar diya, lekin #benefits me kya problem hai samjha nehi !! kya hai problem ?
> 
> https://swapreadsconnect.netlify.app/costefficient , https://swapreadsconnect.netlify.app/revitalize . i was saying chk pages in benefit section , add effect in pages which dont have mouse effect .

@abhi03ruchi I don't know why these 2 pages are not working (that effect)! Next PR me dekhta hu .Please abhi k liye is PR ko to merge karo level 3 label ke sath 😓

**Pull request merged**
