### PR TITLE
ADDED A FOOTER ELEMENT IN THE EVENTS PAGE

### PR DESCRIPTION
**Pull request by likitha-kapu**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4363 

# Description

The addition of a footer section on the events page is necessary to enhance user experience and accessibility. This footer should include key elements such as home,benefits,contact etc to encourage engagement. The addition of Swap Reads info is also required int the footer section.
Added icons of social media and a subscribe button

#4363 

# Type of PR

- [ ] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-01 161954

# Checklist:

- [X ] I have made this change from my own.
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generate no new warnings.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
create new PR and improve it more @likitha-kapu like in home page

**Comment by likitha-kapu** [comment]
@sailaja-adapa I have no much idea of how to resolve conflicts...

**Comment by sailaja-adapa** [comment]
seee in YT it will just take u 2min

**Comment by likitha-kapu** [comment]
@sailaja-adapa yeah ok

**Comment by likitha-kapu** [comment]
@sailaja-adapa resolved conflict

**Comment by likitha-kapu** [comment]
@sailaja-adapa 
image
Is this okay

**Comment by likitha-kapu** [comment]
@sailaja-adapa there are no conflicts now...can you merge my pullrequest

**Comment by sailaja-adapa** [comment]
Create new PR on fixing social media links in one line horizontally @likitha-kapu

**Comment by abhi03ruchi** [comment]
i have reverted ur changes . 

due to some error in resolving conflicts the calender went missing .

**Comment by abhi03ruchi** [comment]
> @sailaja-adapa there are no conflicts now...can you merge my pullrequest

i have reverted ur changes .  chk the deploy preview .

due to some error while resolving conflicts the calender went missing .

**Comment by abhi03ruchi** [comment]
raise  new pr to add navbar and footer in events page .

**Pull request merged**
