### PR TITLE
Improved the navbar of the home page

### PR DESCRIPTION
**Pull request by meetarora10**
# Related Issue
Fixes:  #2260

# Description
I have modified the navbar of the home page and now it is proper for responsive view and the navbar is clearly visible on click of the hamburger icon for smaller screens.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot (590)
Screenshot (591)
Screenshot (592)
Screenshot (593)

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

Please consider this under level 2.

### CODE REVIEW

**Comment by meetarora10** [comment]
@anuragverma108 kindly review and merge this PR.

**Comment by RitiChandak** [comment]
image
image
They both are different it doesn't look good 

Correct it and create a new PR or reopen this one

**Comment by RitiChandak** [comment]
and please don't do it like this
image

**Comment by RitiChandak** [comment]
make it in center

**Comment by meetarora10** [comment]
Okay

**Comment by meetarora10** [comment]
@RitiChandak made the changes as you said.

**Pull request closed without merging**
