### PR TITLE
Fixes #3868:  enhance ui for faqs page

### LINKED ISSUE #3868: Feat: enhance ui for faqs page
### Describe the feature

after the user expands a particular faq, other's should collapse. only one faq should be expanded at a time. this makes the user interaction smoother.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by jainaryan04**
Fixes:  #3868 

# Description
change <script> code to ensure than after the user expands a particular faq, the previous answer is hidden

# Type of PR
- [X] UI enhancement

# Checklist:
- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
there is another faq in books page. this is leading to redundancy . 
remove faq section from books page .

**Comment by jainaryan04** [comment]
@abhi03ruchi I have not added faqs
 Just added the script code so that only one faq can be expanded at a time.

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi I have not added faqs Just added the script code so that only one faq can be expanded at a time.

i know that . just chk books page . it also had a faq section . just delete faq section code from there .

**Comment by jainaryan04** [comment]
> > @abhi03ruchi I have not added faqs Just added the script code so that only one faq can be expanded at a time.
> 
> i know that . just chk books page . it also had a faq section . just delete faq section code from there .

FAQ's are there in these 12 files. Just to conform, you want me to remove them from all the files other than index.html ?

**Comment by abhi03ruchi** [comment]
just check once the pages , if the faq section is the same on the pages as on the home page . delete them.

**Comment by jainaryan04** [comment]
@abhi03ruchi done

**Pull request merged**
