### PR TITLE
Fixed Issue in Contact page ! #3254 #3257

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #3254 & #3257

When you select Dark mode this "Name", "Email", "Subject" & "Message" text boxes color & text color almost blends with the background color,  but now Issue Fixed -

Screenshot 2024-10-12 041044
Screenshot 2024-10-12 041030

Fixed text color & text boxes gap issue -
Screenshot 2024-10-12 034608

# Description

[Text boxes color, text color & text boxes gap ]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@sailaja-adapa @avantikasankhe  PA please add the level 2 tag as I have solved these[#3254 & #3257] 2 issue properly.

Screenshot 2024-10-12 043308

**Comment by Subhajit-2023-44** [comment]
@sailaja-adapa

**Comment by sailaja-adapa** [comment]
yeah done @Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
Thank you PA @sailaja-adapa

**Comment by sailaja-adapa** [comment]
i'm mentor @Subhajit-2023-44

**Pull request merged**
