### PR TITLE
created issue reminder workflow

### PR DESCRIPTION
**Pull request by amiya-cyber**
# Related Issue

none

Fixes:  #4182 

# Description

Description: Create a GitHub Actions workflow that sends reminders on open issues without updates for 7 days. The workflow should post a comment prompting assignees to take action.

issue #4182 

# Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by amiya-cyber** [comment]
Hello @sailaja-adapa can you level 3 label as GSSOC ext will be over in 2 days

**Review by MastanSayyad — COMMENTED** [review]
Reducing to level 1

image

**Comment by amiya-cyber** [comment]
Let it be @MastanSayyad bcoz it’s their choice if they are not having any problem giving high labels

**Comment by MastanSayyad** [comment]
Hi @amiya-cyber but the Guidelines are same for everyone.

**Pull request merged**
