### PR TITLE
Feat : Added dark mode feature in privacy notice 

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
# Related Issue
Fixes:  #2280 

# Description

- Added dark mode feature in privacy notice page as per the theme of the project

- Also , fixed the allignment of the top part of the page so that the whole container is fully visible.

# Type of PR
- [X] Feature enhancement

# Screenshots / videos (if applicable)
Before :

https://github.com/anuragverma108/SwapReads/assets/162733812/8e38e154-13af-42d6-a29a-42fe8ae1d113

After:

https://github.com/anuragverma108/SwapReads/assets/162733812/ea495d03-9759-4e0a-ad1f-d9be43c4c65a

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @RitiChandak @huamanraj @RishabhDhawad I have made the required changes , please review it and merge it under gssoc...Thank you!

**Comment by RitiChandak** [comment]
it's same
image

**Comment by Maana-Ajmera** [comment]
@RitiChandak its showing correct in mine ... you can look at the video 

https://github.com/anuragverma108/SwapReads/assets/162733812/45537997-1b83-4c0a-bcdc-76a11218b08e

**Comment by RitiChandak** [comment]
let me check it with others

**Comment by Maana-Ajmera** [comment]
@RitiChandak @huamanraj @anuragverma108 @RishabhDhawad  Thank you ! Really enjoying working with you all in this wonderful project

**Pull request merged**
