### PR TITLE
Correct URL Path for Reader Connection in Dropdown Menu

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #3830

# Description

- Corrected the URL path for the Reader Connection page in the "More" dropdown menu.
- The link now accurately directs users to the correct page, enhancing overall navigation reliability.
- Ensured the dropdown menu's functionality remains consistent across all sections.
- This PR fixes the incorrect Reader Connection link, ensuring users can access the page without any issues from the dropdown 
   menu.

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
### BEFORE

https://github.com/user-attachments/assets/3ebd3d7f-57e3-40e7-9413-73929e9b76bf

### AFTER
https://github.com/user-attachments/assets/79f43232-9e81-4fa6-981c-39a71960cbe3

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
resolve conflicts @SrijaVuppala295

**Comment by sailaja-adapa** [comment]
create new PR @SrijaVuppala295

**Comment by sailaja-adapa** [comment]
I think I said I to work with updated branch in one of your PR's @SrijaVuppala295

**Comment by sailaja-adapa** [comment]
Since it is causing conflicts again and again

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , Ok mam i will not  repeat them again , But again it would be very much long process to do it again, hope you not close the issues.

**Comment by sailaja-adapa** [comment]
Do u want me to reopen PR try update branch do u know that

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , Mam I didnt said like that , I have said about the issues section , not PR as some of my issues were closed before

**Comment by SrijaVuppala295** [comment]
> So your recent issue closed related to this PR @SrijaVuppala295 ??

No mam

**Pull request closed without merging**
