### PR TITLE
Hover effect added

### PR DESCRIPTION
**Pull request by dishathakurata**
Fixes issue #245 

I added a hover effect on FAQ section to make it more attractive. Background color changes to rose pink whenever someone hovers over the FAQ questions.
Suggest any other changes if you want.

Before:
pink

After: 
after
after 2

Thank you @anuragverma108

### CODE REVIEW

**Comment by anuragverma108** [comment]
Good Work @dishathakurata

**Comment by dishathakurata** [comment]
Thank you so much @anuragverma108 sir

**Comment by anuragverma108** [comment]
No need to call me Sir.
I have seen your LinkedIn. 
You are my Senior 🙏

**Comment by dishathakurata** [comment]
LOL it's okay !!

**Pull request merged**
