### PR TITLE
Fixing benefits pages

### PR DESCRIPTION
**Pull request by Riyachauhan11**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4879

# Description
the dark mode bg looked all messed up and headers didnt align well in the pages present in the benefits section of home page. I have fixed this.

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

https://github.com/user-attachments/assets/34591ac2-4c8d-4d84-9d2c-4a6e00f37bad

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by atmajaa** [comment]
image
image

The cards are aligned a little too much on the left. And the dark theme toggle button should be on the navbar for connect with same url.

**Comment by atmajaa** [comment]
@Riyachauhan11 can you work on this and give me updates. There is one more similar pr on this issue.

**Comment by Riyachauhan11** [comment]
> @Riyachauhan11 can you work on this and give me updates. There is one more similar pr on this issue.

Sure I'll work on it

**Comment by Riyachauhan11** [comment]
@atmajaa i have tried to align the cards on all pages more to center

**Comment by atmajaa** [comment]
@Riyachauhan11 it's still showing the same in deployment preview
image

**Comment by Riyachauhan11** [comment]
wbt now?
image

**Comment by abhi03ruchi** [comment]
in https://deploy-preview-4880--swapreadsconnect.netlify.app/costefficient page , add latest navbar and footer . like the one in diverse literary page.

**Comment by Riyachauhan11** [comment]
@atmajaa @abhi03ruchi is it fine now?

**Comment by abhi03ruchi** [comment]
not https://deploy-preview-4880--swapreadsconnect.netlify.app/connectwithsame , this page

**Comment by abhi03ruchi** [comment]
also change the backgrd of all pages in light mode , to the one that is there on home page .

**Comment by Riyachauhan11** [comment]
> not https://deploy-preview-4880--swapreadsconnect.netlify.app/connectwithsame , this page

image
image

but the navbars in these 2 pages are pretty much the same

**Comment by Riyachauhan11** [comment]
@abhi03ruchi @atmajaa should be fine now

**Pull request merged**
