### PR TITLE
improve event page

### PR DESCRIPTION
**Pull request by dipak2005**
# Related Issue

Fixes: #3382 
closes : #3382 

# Description

[impove the event page ui for better user experience]
# Screenshot : 
Screenshot 2024-10-13 220619

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
good work @dipak2005

**Comment by sailaja-adapa** [comment]
good work @dipak2005 keep it up

**Comment by dipak2005** [comment]
> good work @dipak2005

Thank you ma'am

**Comment by sailaja-adapa** [comment]
work on fixing this issue @dipak2005 

m

**Comment by dipak2005** [comment]
> work on fixing this issue @dipak2005 
> 
> m
> 

Ok ma'am

**Pull request merged**
