### PR TITLE
Centered the donation card on donate books to Schools page

### PR DESCRIPTION
**Pull request by sachan13harshit**
# Related Issue

Fixes: # [2637](https://github.com/anuragverma108/SwapReads/issues/2637)

# Description

The donation card on the "Donate Books to School" page was off-center, affecting the overall aesthetic and user experience. This pull request addresses the issue by updating the CSS to ensure the card is horizontally centered within the viewport, creating a more balanced and visually appealing layout.
# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

**Before:**
Screenshot from 2024-07-26 11-19-38

**After:**
Screenshot from 2024-07-29 08-17-15

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Review by sachan13harshit — COMMENTED** [review]
Fixing Merge conflicts

**Comment by huamanraj** [comment]
fix conflicts

**Review by sachan13harshit — COMMENTED** [review]
Fixed Merge Conflicts

**Comment by anuragverma108** [comment]
Conflicting files
index.html

Resolve Conflicts and raise conflict again!

**Pull request closed without merging**
