### PR TITLE
Fixes #489 : Added Google Map

### LINKED ISSUE #489: Feat: Addition of Google Map in the Contact Us form
### Describe the feature

I want to add a Google Map feature to the Contact Form in the website, along with the address, as it'll make the contact form more complete with the pinned Map location on it.

Kindly assign me this issue under GSSoC '24.

Thank you!

### Add ScreenShots

Before:

Screenshot 2024-05-16 021800

After:

Screenshot 2024-05-16 021556

(P.S.: The After part is for illlustration purposes, the actual feature will be similar like that, but of course it'll be just an integration into the already existing UI design)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
A feature of viewing the address on Google Map, and the location being pointed is added.

Before: 

Screenshot 2024-05-16 021800

After:

Screenshot 2024-05-16 134543

### CODE REVIEW

**Comment by Sambit-Mondal** [comment]
Also, considering the complexity and the time and effort required, it'd be very kind if you assign this issue as Level 2. :)
Thank you!

**Comment by huamanraj** [comment]
> A feature of viewing the address on Google Map, and the location being pointed is added.
> 
> Before: 
> 
> Screenshot 2024-05-16 021800
> 
> After:
> 
> Screenshot 2024-05-16 134543
> 

is there any issue regarding this?

**Comment by huamanraj** [comment]
> Also, considering the complexity and the time and effort required, it'd be very kind if you assign this issue as Level 2. :)
> Thank you!

this design doesn't look good please try some other design arrangements!

**Comment by Sambit-Mondal** [comment]
Sure Sir, on it!

**Comment by Sambit-Mondal** [comment]
@huamanraj Sir, I've got something to discuss regarding this, can I ping you on Discord?

**Comment by Sambit-Mondal** [comment]
Sir, I've done some enhancements to the design. Kindly check!

Screenshot 2024-05-16 155531

Screenshot 2024-05-16 155544


Responsiveness:

Screenshot 2024-05-16 155823

Screenshot 2024-05-16 155805

**Comment by Sambit-Mondal** [comment]
@huamanraj Kindly check the enhancements I've made :)

**Comment by anuragverma108** [comment]
image
Submit & your message box is repeated two times. Fix it & raise PR again. We will merge!

**Pull request closed without merging**
