### PR TITLE
improved css of contact section

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Fixes:  #3709 

# Description

I have improved the css of contact section address and map

Issue #3709 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Gauravtb2253** [comment]
pls check

**Comment by abhi03ruchi** [comment]
changes are not visible . chk deploy preview.

**Comment by abhi03ruchi** [comment]
@sailaja-adapa .

**Comment by sailaja-adapa** [comment]
changes were not resembling work on new issue like adding hover effect @Gauravtb2253

**Pull request closed without merging**
