### PR TITLE
Updated the navbar and footer

### PR DESCRIPTION
**Pull request by Anjaliavv51**
# Related Issue
BUG:comsp.html page , changes navbar and footer

Fixes:  #2809 

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

image

image

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@anuragverma108 please review the PR.

**Comment by Anjaliavv51** [comment]
@huamanraj 108 please review the PR.

**Comment by Anjaliavv51** [comment]
@huamanraj @anuragverma108 please review the PR.

**Comment by Anjaliavv51** [comment]
@huamanraj @anuragverma108 please review the PR.

**Comment by huamanraj** [comment]
done ✅!! sorry for late review but there was a lot of PRs so it does take time i hope you understands !!

**Pull request merged**
