### PR TITLE
Fixed/Responsiveness

### PR DESCRIPTION
**Pull request by Arghya-Chakraborty0812**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #3862 

# Description

Responsiveness of the navbar was fixed.

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/beadc85e-edbc-45bd-8ef9-d8caeef93a08

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

Please merge my PR.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
#4054 is working on similar issue already .

**Comment by abhi03ruchi** [comment]
audio page footer design doesnt match with the website 's  standard footer design . 

u can copy the footer design from play now page . ( click on play now button ) .

**Comment by Arghya-Chakraborty0812** [comment]
I have changed the navbar color and its responsiveness. I have not added hover effect like the home page. Please review and merge my PR
https://github.com/user-attachments/assets/5f15247a-3c69-42f1-bde5-d97028cdb8a6

**Comment by abhi03ruchi** [comment]
this doesnt look good . just copy code from  navbar on play now page . ( click on play now button ) , and paste on your page .

**Pull request closed without merging**
