### PR TITLE
Add Details and Update the horror page UI

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

This PR is raised again for the changes in the PR #4420 

# Description

PR #4420 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-02 211543
Screenshot 2024-11-02 211554

# Checklist:

- [X]I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
@abhi03ruchi Please review these changes so that I can make them for the other pages.

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-02 at 9 40 06 PM
keep the heading like this . also fix the spacing b/w the heading and the cards .

**Comment by haseebzaki-07** [comment]
hey @abhi03ruchi udpated the styling, please check

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi Please review these changes so that I can make them for the other pages.

on classic literature page , another contributor is working . u can do other pages first . and add details to that page at last.

**Comment by haseebzaki-07** [comment]
@abhi03ruchi Iwill do that

**Comment by abhi03ruchi** [comment]
i have reverted ur changes . u changed assets/html/top10.html also due to which quizzes ( a feature added by a contributor) were deleted . 

commit only those changes that are related to ur issue . 

raise new pr for horror page .

**Pull request merged**
