### PR TITLE
 adding translator in all pages

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes: #4090

# Description

Added translator in all the pages of your site

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/343bdb10-11cd-41b2-b5ce-401614a646ae

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Antima2004** [comment]
please assign this pr to label level 3 @anuragverma108

**Comment by abhi03ruchi** [comment]
add the translator in  login page , events page . in all pages in the profile dropdown . 

chk these pages too that are in quick links . 
Screenshot 2024-10-27 at 4 51 45 PM

**Comment by abhi03ruchi** [comment]
fix this bug .
https://github.com/user-attachments/assets/d9315cf5-fa41-40d0-9077-b17a2f66d181

**Comment by abhi03ruchi** [comment]
fix the bug , it is majority pages. 
https://github.com/user-attachments/assets/965838a6-d096-4fbf-91f6-07bd647c6774

**Comment by Antima2004** [comment]
Ok

**Comment by Antima2004** [comment]
I am doing this again @abhi03ruchi

**Pull request closed without merging**
