### PR TITLE
solved #4232 added new top 10 books 

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
solved #4232 added the images to the books 
Fixes:  #4232 

Uploading swapcardimage.mp4…

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@sailaja-adapa  please review this mam

**Comment by abhi03ruchi** [comment]
do the changes u were told in pr  #4215 .  will merge the pr then .

**Comment by abhi03ruchi** [comment]
coding time has been extended 10th Nov . aaram se karlo .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Mam no update on website

**Comment by sailaja-adapa** [comment]
Soon you will know @KapuluruBhuvaneswariVspdbct see the post on LinkedIn 

IMG-20241030-WA0000

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok mam

**Comment by abhi03ruchi** [comment]
#4244  is resolved here . change the name of the pr . 

and u can create separate pr to solve this issue .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi changed mam

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi Mam  untill now made many changes for this contribution mam and resolved conflicts mam would you please increase the level mam

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok mam

**Pull request merged**
