### PR TITLE
[BUG]:card is not visible in price section

### PR DESCRIPTION
**Pull request by nikhilnishadoo7**
Fixes:  #2275

# Description

card is not visible properly in price section 

# Type of PR

- [x] Bug fix

# Screenshots / videos (if applicable)

Screenshot 2024-07-01 005240

### CODE REVIEW

**Comment by nikhilnishadoo7** [comment]
Hi @huamanraj,

Please check my PR. If you need any changes, please let me know.

Thank you!

**Comment by RitiChandak** [comment]
@nikhilnishadoo7 , the issue has not been assigned to you yet. Please do not start working on it until it is officially assigned to you.
This is the last time i am considering it

**Comment by nikhilnishadoo7** [comment]
Dear @RitiChandak ,

Thank you for bringing this to my attention. I apologize for any confusion caused. I will ensure to wait for the official assignment before beginning work on the issue.

Thank you for your understanding.

Best regards,
@nikhilnishadoo7

**Comment by RitiChandak** [comment]
image

@nikhilnishadoo7 the content is overlapping with buy now correct it and open a new PR or reopen this one

**Pull request closed without merging**
