### PR TITLE
Adding AI book recommendation generator which would give book recommendations based on the questions asked 

### LINKED ISSUE #4688: Feat: Adding a separate page for AI book recommendation generator which would give book recommendations based on the questions asked
### Describe the feature

Feat: Adding a separate page for AI book recommendation generator which would give book recommendations based on the questions asked

### Add ScreenShots

Feat: Adding a separate page for AI book recommendation generator which would give book recommendations based on the questions asked

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shriyadindi**
# Related Issue
Adding AI book recommendation generator which would give book recommendations based on the questions asked 

Fixes:  #4688 

# Description

Adding AI book recommendation generator which would give book recommendations based on the questions asked 

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
delete index.html file and notify me @shriyadindi

**Comment by abhi03ruchi** [comment]
create a demo video , to show the feature u have added .

**Comment by atmajaa** [comment]
@shriyadindi any updates? add a demo video today is the last date to contribute

**Comment by shriyadindi** [comment]
@atmajaa 

https://github.com/user-attachments/assets/6c837114-bcd9-4767-a409-f96fee1e0c82

**Comment by abhi03ruchi** [comment]
u have also changed the footer ?

**Comment by atmajaa** [comment]
@shriyadindi I cannot see the AI link in the footer in deployment preview

**Comment by abhi03ruchi** [comment]
there are conflicts

**Comment by shriyadindi** [comment]
@abhi03ruchi resolved

**Comment by abhi03ruchi** [comment]
chk deply preview

**Pull request closed without merging**
