### PR TITLE
Changed book exchange hub UI

### PR DESCRIPTION
**Pull request by AlaynaShaheen**

### CODE REVIEW

**Comment by anuragverma108** [comment]
Show me before and after screen shot first! @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Before:
Screenshot 2024-05-10 081404

After:
Screenshot 2024-05-10 214742

**Comment by anuragverma108** [comment]
@AlaynaShaheen The before one & After one have the same look. Also the before one is responsive. Is your after one is responsive. Confirm it before merging ??

**Comment by anuragverma108** [comment]
image

Resolve this conflicting issue & create PR again.
Make sure to pull all to existing changes before creating a PR

**Pull request closed without merging**
