### PR TITLE
Add Classic literature books

### LINKED ISSUE #3911: Feat: API for classic literature books
### Describe the feature

I want to write and integrate API for bringing in data for Classic Literature books. So that users will have more options to see and explore.

### Add ScreenShots

Screenshot 2024-10-23 115805

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
## fixes #3911 

# Description
This PR adds a new page classic-literature.html for bringing in different book options.
Created a API for the purpose .

## issue #3911

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-10-24 163831

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
Can you please record a video from home page to view your changes @haseebzaki-07

**Comment by haseebzaki-07** [comment]
hey @sailaja-adapa here is the video 
https://github.com/user-attachments/assets/3639f67e-379f-44cd-ac3a-62d7dcba5145

**Comment by sailaja-adapa** [comment]
make that text to be in black colour it is appearing in blue colour right? @haseebzaki-07

**Comment by haseebzaki-07** [comment]
hey @sailaja-adapa removed the blue color

**Comment by haseebzaki-07** [comment]
hey @sailaja-adapa @abhi03ruchi please finalize this PR

**Comment by sailaja-adapa** [comment]
work with updated branch @haseebzaki-07 once view deployment preview

**Pull request closed without merging**
