### PR TITLE
change in html h2 section-title

### PR DESCRIPTION
**Pull request by pankhuripanday**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #2246

# Description

Have made changes to the h2 section-title and shifted it a little down from the hovering image of main screen.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@pankhuripanday Provide me with the issue no. description and screenshot of the changes you made

**Comment by pankhuripanday** [comment]
Issue no.is #2246
Have made the changes to html H2 section -title by shifting the text
message a little down from the hovering image of main screen.

**Comment by RitiChandak** [comment]
i am asking for issue number not for PR number

**Comment by pankhuripanday** [comment]
Issue no.#2254

**Comment by RitiChandak** [comment]
@pankhuripanday, the issue has not been assigned to you yet. Please do not start working on it until it is officially assigned to you.
This is the last time i am considering it

**Comment by pankhuripanday** [comment]
Okay. I didn't read the guildlines. I'll take care next time.

**Pull request merged**
