### PR TITLE
Added settings page

### PR DESCRIPTION
**Pull request by ayush-848**
# Related Issue

Fixes:  #2268

# Description
Added the setting page.
Made the data added to local storage.
Added profile visibility option.
Password change setting added.

EVERY DATA CAN BE DOWLOADED
image

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by ayush-848** [comment]
@RitiChandak Check it

**Comment by ayush-848** [comment]
@RitiChandak please can you give me a higher level. I have added backend functionality, a setting page and new features

**Comment by RitiChandak** [comment]
the level will be assigned based on your work

**Comment by ayush-848** [comment]
> the level will be assigned based on your work

sure do check it

**Comment by RitiChandak** [comment]
@ayush-848 i haven't login in the page but as i click to the setting it asking for the current password first it should confirm your account

**Comment by RitiChandak** [comment]
there is no navbar or footer how i should know this is the part of swapreads 
Its simple HTML file to me

**Comment by RitiChandak** [comment]
you are saying you have added backend functionality how are you checking current password

**Comment by RitiChandak** [comment]
image
How did he change the password without checking the current one?

**Comment by RitiChandak** [comment]
Regarding the privacy settings, we have not yet implemented the public profile option; currently, no one can view another's profile. How will this function be implemented. even profile is not fully functional till now

**Comment by ayush-848** [comment]
> you are saying you have added backend functionality how are you checking current password

In my previous PR #2222 in which I made the name and avatar to get stored in the local storage, so that after the name and avatar gets edits or page gets refreshed it still remains in the local storage for that user's local server.

So in that context I added the backend word as I am fetching the user info from /profile and downloading it.

**Comment by ayush-848** [comment]
In that change password, I tried to fetch the user details when the login takes place, but it was not happening.

So I added in the local server.
So the form takes effect properly.

 But after this PR I noticed that my previous part was in stash.
 So yeah, I will update it

**Comment by ayush-848** [comment]
The visibility part I will remove it.

As you rightly said that the profile is not fully functional

**Comment by ayush-848** [comment]
But the website's firebase auth is not properly working for which I am not able to retrieve the data, neither it have database to fetch it from there.

My idea was to put in application memory for that user's server and than read or update it when user fills the form

**Comment by ayush-848** [comment]
> But the website's firebase auth is not properly working for which I am not able to retrieve the data, neither it have database to fetch it from there.
> 
> My idea was to put in application memory for that user's server and than read or update it when user fills the form

@RitiChandak should I do it in this way?????

**Comment by ayush-848** [comment]
For this way I have the logic

Since the firebase registration is not working properly, if user enter email and pwd and press the button the page gets sort of refreshed.

However the password and email will get stored as a cache in the server that will be retrievable.

**Comment by RitiChandak** [comment]
@ayush-848 But still it won't functional and in today's scenario security is very important

**Comment by ayush-848** [comment]
> @ayush-848 But still it won't functional and in today's scenario security is very important

Yea that's the case I refrained from adding it.

Else password would be publicly available

**Pull request closed without merging**
