### PR TITLE
Rate Us Improved

### PR DESCRIPTION
**Pull request by MansiJangid**
# Related Issue

Improved the Rate Us page

Fixes:  #4354 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
### Before
Screenshot (190)

### After
Screenshot (191)

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
resolve conflicts @MansiJangid

**Comment by MansiJangid** [comment]
conflict resolved @sailaja-adapa

**Comment by sailaja-adapa** [comment]
Recheck @MansiJangid again conflicts occurred

**Comment by sailaja-adapa** [comment]
work with updated branch and raise new PR @MansiJangid

**Pull request closed without merging**
