### PR TITLE
#3509 fixed the alignment of donate btn

### PR DESCRIPTION
**Pull request by jayashisbarua**
#3509 

Fixes:  #3509 

# Description

I have fixed the alignment of the buttons in donate section. Now they are in same base line and looks good in the website.
#3509 

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
<h3>Before:</h3>
Screenshot 2024-10-15 at 11 34 21 PM
<h3>After:</h3>
Screenshot 2024-10-18 at 7 51 11 AM

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
Resolve conflicts @jayashisbarua

**Comment by jayashisbarua** [comment]
> Resolve conflicts @jayashisbarua

Done ma'am.
Ma'am  I have a request, I am a new contributor to GSSOC'24 and have been contributing to this project. However, I have reached the points cap for Level 1, and as I don’t have other projects left in my area of expertise, I would like to request a Level 2 tag so I can continue contributing and raise my total points to 60.

**Comment by jayashisbarua** [comment]
@sailaja-adapa Thank you ma'am 😊

**Comment by sailaja-adapa** [comment]
Wlcm @jayashisbarua

**Pull request merged**
