### PR TITLE
Add Scroll profile

### LINKED ISSUE #3452: BUG: Scroll in Profile components
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Components order history, wishlists et... in the profile page have contents that are overflowing. I want to fix this components by making them scrollable

Screenshot 2024-10-14 203811

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue
fixes #3452 

# Description
Added a scrollbar aligning the UI of the page in the components of the profile section
issue #3452 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-10-14 220241

# Checklist:

- [X] I have made this change from my own.

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
u have done changes in emailJs <script> tag also ? The pr says only UI is enhanced .

**Comment by haseebzaki-07** [comment]
Yeah that is from a previous issue I created but that does not work anyways @abhi03ruchi. So didn't raised separate PR for it

**Comment by abhi03ruchi** [comment]
only commit the UI changes ... undo everything else .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi Since u have merged this PR please add some label tag

**Pull request merged**
