### PR TITLE
Added refresher

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#2619

# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #2619 
# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/04699100-287b-4d63-a2a1-9fe8bebccedd

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@huamanraj please review the PR.

**Comment by Anjaliavv51** [comment]
@huamanraj the screenshoot added in the PR description is the preview from the netlify.

**Comment by huamanraj** [comment]
> @huamanraj please review the PR.

it is good but make it better in mobile responsiveness i will give L2 then ! 
just decrease the size in the mobile view a bit

**Comment by Anjaliavv51** [comment]
@huamanraj sure

**Comment by Anjaliavv51** [comment]
@huamanraj please review the PR it made responsive now.

**Comment by huamanraj** [comment]
> @huamanraj please review the PR it made responsive now.

good work 👏 @Anjaliavv51 !

**Comment by Anjaliavv51** [comment]
> > @huamanraj please review the PR it made responsive now.
> 
> good work 👏 @Anjaliavv51 !

@huamanraj Thank You.

**Pull request merged**
