### PR TITLE
Modified the download buttons in explore freebook section

### PR DESCRIPTION
**Pull request by SadafKausar2025**

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Can you please assign the issue no #419 to me?

**Comment by SadafKausar2025** [comment]
Screenshot (1718)


now it looks much better priviously it was taking full width.

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me #426?

**Comment by anuragverma108** [comment]
image

Conflicting files
assets/css/style.css

Resolve the above conflicts & raise PR again.

To ensure clarity and proper assignment tracking, please attach the issue number to your PR description. This helps us confirm that the issue is assigned to you. Kindly update your PR with the issue number and resubmit.

Example:
Fixes #123 - Brief description of the fix.

**Pull request closed without merging**
