### PR TITLE
solved #4945 #4946 #4947

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
solved #4945 #4946 #4947

# Description

To horror books added:
Added Quiz
Added solutions to quiz
Added approach to quiz

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@atmajaa please merge this

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@atmajaa please merge this

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-10 at 3 23 55 PM
change the color. . backgrd white , text black is ok . red par red is not ok

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
ok mam

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi made changes mam 
please merge
image

**Pull request merged**
