### PR TITLE
Fixes issue #2611

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
This PR adjusted the card size in Acclaimed Authors Section to fit the text, also aligns buttons in the book list section of each Literary realms card.
Improves navbar for each card page in Literary realms

Fixes:  #2611 

# Type of PR

- [X] Bug fix
# Screenshots / videos (if applicable)
Before:
image
image
image

After:
image
image
image

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@anuragverma108 @huamanraj 
Kindly review this PR also add labels to this.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@huamanraj please review this PR.

**Comment by Bhattu-Anitha-07** [comment]
@huamanraj 
can you please label this as level2.

**Comment by Bhattu-Anitha-07** [comment]
Modified all the pages of Literary realms cards.

**Comment by huamanraj** [comment]
> @huamanraj 
> can you please label this as level2.

sorry but it doesn't qualify the criteria of L2 because it is just some css change! not any minir  feature update or Major bug!

**Comment by Bhattu-Anitha-07** [comment]
Ok @huamanraj 
Thank you.
Will contribute more.

**Comment by huamanraj** [comment]
> Ok @huamanraj 
> Thank you.
> Will contribute more.

😊 stay leaning and contributing!

**Pull request merged**
