### PR TITLE
Bug Fixed

### PR DESCRIPTION
**Pull request by sristy17**
Closes issue #1556 

# Description

Earlier when we were trying to get into about us page in dark mode it automatically turn on the light mode, i.e it was not linked with the system theme and we need to manually turn it on to dark mode, now it is fixed, it will automatically turn according to system theme, dark or light.

# Type of PR

- [X] Bug fix

# Screenshots / videos (if applicable)
I wasn't able to take the screen recording, but I did make sure it doesn't bother existing code, and bug is also fixed, hope it works :)

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@sristy17   it's not working
image
image

**Comment by sristy17** [comment]
> @sristy17 it's not working image image

The issue was when we switch the theme to dark mode then render to about page the deafult theme doesnt apply now after the changes it gets apply can you please check with dark mode..in light mode it is okay.

**Comment by sristy17** [comment]
@RitiChandak Okay i got the issue you're talking about, will fix it soon, by EOD?

**Comment by sristy17** [comment]
Screenshot from 2024-06-08 12-36-05
Screenshot from 2024-06-08 12-35-57
Fixed :)

**Comment by huamanraj** [comment]
> Screenshot from 2024-06-08 12-36-05
> Screenshot from 2024-06-08 12-35-57
> Fixed :)

great work 👏

**Pull request merged**
