### PR TITLE
Added: New Genre Mythology

### LINKED ISSUE #2650: Add new genre "Mythology"
### Describe the feature

Will add new genre section "Mythology"

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by kosuri-indu**
# Related Issue

Fixes #2650 

# Description

Added a new genre "Mythology" with content
Fixes #2650 

# Type of PR

- [x] Feature enhancement

# Screenshots / videos (if applicable)
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by kosuri-indu** [comment]
@huamanraj 
Please merge this sir

**Comment by kosuri-indu** [comment]
@huamanraj 
Sir could you add the level1 to this PR

**Comment by huamanraj** [comment]
> @huamanraj 
> Sir could you add the level1 to this PR

 

i can but as gssoc guidelines this is not a contribution that should have a level!

**Comment by kosuri-indu** [comment]
> > @huamanraj
> > Sir could you add the level1 to this PR
> 
> i can but as gssoc guidelines this is not a contribution that should have a level!

thank you sir

**Pull request merged**
