### PR TITLE
Login file js edit and correction

### PR DESCRIPTION
**Pull request by PriyanshiAgr**
#4063

"None"

Fixes:  #4063 

# Description

Edited the login and logout options and there were some corrections needed in the Login file (script) for issue: #4063 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
screencapture-swapreadsconnect-netlify-app-assets-html-login-2024-10-27-00_22_55

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
plz create a demo video to show what u have done . and explain properly

**Comment by abhi03ruchi** [comment]
are u working on this issue? as gssoc ext is about to end.

**Comment by PriyanshiAgr** [comment]
Yes I am, will submit by the EOD.

**Comment by sailaja-adapa** [comment]
work with updated branch and raise new PR @PriyanshiAgr

**Pull request closed without merging**
