### PR TITLE
`Nav Bar` is now on the top of screen in `Environmental Impact` Page

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
# Related Issue

`Nav Bar` is not on the top of screen in `Environmental Impact` Page

Fixes:  #4074 
# Description

Made NAV bar on the top and center of screen similar to home page.

@anuragverma108 

# Type of PR

- [x] Bug fix

# Screenshots / videos (if applicable)
## before
Screenshot 2024-10-27 221141
## now
image

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/3d2224cc-985b-47e6-8948-03e5c1a10f37

fix the bug . 

also fix the position of the profile icon  in the navbar .

**Comment by Adarsh-Chaubey03** [comment]
> 
> https://github.com/user-attachments/assets/3d2224cc-985b-47e6-8948-03e5c1a10f37
> 
> fix the bug . 
> 
> also fix the position of the profile icon  in the navbar .

Okk

**Comment by Adarsh-Chaubey03** [comment]
CORRECTED THE  NAV BAR 
image
@abhi03ruchi please check this out

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/6f4c5c9e-5e0d-4ee4-85f2-8c0946b07fb5

fix the bug .

**Comment by Adarsh-Chaubey03** [comment]
fixed bug @abhi03ruchi 
image

**Comment by abhi03ruchi** [comment]
similar issue is there in other pages of benefit section . 

u may work on this issue and raise pr . will increase ur level for it .

**Comment by Adarsh-Chaubey03** [comment]
> similar issue is there in other pages of benefit section .
> 
> u may work on this issue and raise pr . will increase ur level for it .

do i need to create another issue for that

**Comment by Adarsh-Chaubey03** [comment]
> similar issue is there in other pages of benefit section .
> 
> u may work on this issue and raise pr . will increase ur level for it .

okk

**Comment by abhi03ruchi** [comment]
sorry , #3857 is already working on this issue , u can work on other issues .

**Pull request merged**
