### PR TITLE
fixed the translator button

### PR DESCRIPTION
**Pull request by Antima2004**
#4188 

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4188 

# Description

fixed the translator button in the navbar section in all pages.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before:
Screenshot 2024-10-30 095212
After:
Screenshot 2024-10-30 091710

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Antima2004** [comment]
can i do these in further pages of your website??

**Comment by abhi03ruchi** [comment]
explain properly what have u done ? add before and after pics . or demo video . 

cant understand what u have done as the pic is too much close up .

**Comment by abhi03ruchi** [comment]
explain properly what have u done ? add before and after pics . or demo video . 

cant understand what u have done as the pic is too much close up .

**Comment by abhi03ruchi** [comment]
explain properly what have u done ? add before and after pics . or demo video . 

cant understand what u have done as the pic is too much close up .

**Comment by Antima2004** [comment]
I fixed the close button of the translator @abhi03ruchi

**Comment by abhi03ruchi** [comment]
in the login page , the close button is not working , so u have corrected that ?

**Comment by abhi03ruchi** [comment]
in the login page , the close button is not working , so u have corrected that ? 

> can i do these in further pages of your website??

no , UI is ok .

**Comment by Antima2004** [comment]
> in the login page , the close button is not working , so u have corrected that ?
> 
> > can i do these in further pages of your website??
> 
> no , UI is ok .

yes I have corrected and also changes the translator close ui

**Pull request merged**
