### PR TITLE
different navbar on some pages #4010

### PR DESCRIPTION
**Pull request by jainaryan04**
Fixes:  #4010 

# Description
about us and audiobooks page had different navbar than the home page. fixed it.

# Type of PR
- [X] Bug fix

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
in about us page navbar also add toggle button   . keep the more dropdown also , so the navbar will look less congested . 

and in audio books page add the same white navbar .  

keep the contents same as earlier.

**Comment by jainaryan04** [comment]
@abhi03ruchi About page has not been styled for dark mode.
Should I just add the toggle button now and work on the dark mode as another issue or add that also here ?

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi About page has not been styled for dark mode. Should I just add the toggle button now and work on the dark mode as another issue or add that also here ?

ya just add toggle here . and for dark mode create another issue.

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi About page has not been styled for dark mode. Should I just add the toggle button now and work on the dark mode as another issue or add that also here ?

ya just add toggle here . and for dark mode create another issue.

**Comment by abhi03ruchi** [comment]
there are some branch conflicts .

**Comment by abhi03ruchi** [comment]
there are some branch conflicts .

**Comment by jainaryan04** [comment]
done @abhi03ruchi

**Comment by abhi03ruchi** [comment]
chk navbar on play now page . ( click on play now button ) , u can copy that navbar design for this page .

**Comment by jainaryan04** [comment]
@abhi03ruchi done

**Comment by sailaja-adapa** [comment]
resolve conflicts @jainaryan04

**Pull request merged**
