### PR TITLE
center aligned the submit button

### PR DESCRIPTION
**Pull request by JomanaMahmoud**
# Related Issue

Fixes:  #4384 

# Description

center aligned the submit button

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before:
image
After:
image

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
we can't assign level to minor issue can u work on other issue too like making the text too in center @JomanaMahmoud and notify me

**Comment by JomanaMahmoud** [comment]
Okay i will make an issue for centering the text and the button as well now

**Comment by sailaja-adapa** [comment]
@JomanaMahmoud do one thing work on other issue on book exchange hub it's size is more decrease it and notify me

**Comment by JomanaMahmoud** [comment]
Do you want me to decrease the width or height or both

**Comment by sailaja-adapa** [comment]
Both @JomanaMahmoud

**Pull request closed without merging**
