### PR TITLE
Modified the Authors page

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Related Issue

Fixes:  #4095 

# Description

The Authors Page was looking very bland before. I have modified the cards and added images of the Authors, which makes the page visually appealing. I have also modified and moved the name of the authors in the front of the card to the bottom of the card so that the author's face is clearly visible. 
The cards were sticking with the navbar before. I have also added space between the navbar and the first row of cards to make it look much neater. Also the Page title was previously **About Us**. I changed it to **Authors** to make it accurate.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

- Before

https://github.com/user-attachments/assets/8aec0b93-7537-49de-977c-57eb522fd5c6

- After

https://github.com/user-attachments/assets/0e45a770-8cb9-44c7-8920-a5317c970621

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
I have only updated the **author.html** file. The other changes were automated most probably by GitHub workflow.

**Comment by rajdeepchakraborty-rc** [comment]
@sailaja-adapa Thanks for reviewing the PR! Sorry, it took me quite a long time to come back to contributing to this repository.

**Comment by rajdeepchakraborty-rc** [comment]
@abhi03ruchi Thanks for assigning the labels. Hope you all have a great day/night ahead!

**Comment by sailaja-adapa** [comment]
Thank you so much @rajdeepchakraborty-rc :)

**Pull request merged**
