### PR TITLE
Fix : There bug/error occur in profile.html which creates conflicts.

### PR DESCRIPTION
**Pull request by salonijoshi1980**
## Description
- Fix:  There bug/error occur in profile.html which creates conflicts.
- This pull request addresses a minor usability issue. A bug was identified in profile.html that caused conflicts when rendering user profiles. This issue led to unexpected behavior, such as incorrect data being displayed or elements not appearing as intended.

**Changes Made :**
- Correct the indentations which causes conflicts.

**Rationale :**
- The primary goal of these changes is to enhance the stability and usability of the profile page. By addressing the bug directly, users will have a smoother experience without the disruptions caused by the previous errors. 
- The modifications also ensure that the codebase remains maintainable and adheres to best practices, which will benefit future development efforts.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Screenshot 2024-10-28 202205

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by salonijoshi1980** [comment]
@anuragverma108 ,  @abhi03ruchi  assign me this pls.. with labels of Gssoc extd , hacktoberfest and level 2 i need points so, it would be great!✨

**Comment by salonijoshi1980** [comment]
@abhi03ruchi hey can u assigned me? why closed this..

**Comment by abhi03ruchi** [comment]
what have u done ? nothing . 

work on some real issue .

**Comment by salonijoshi1980** [comment]
Ok @abhi03ruchi i'll do it

**Pull request closed without merging**
