### PR TITLE
Fixed the navbar alignment

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4357 

# Description
This pr align the navbar section in the login page.

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before:
Screenshot 2024-11-02 193037

After:
Screenshot 2024-11-02 194610

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
chk deploy preview .

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/46a41737-b0ce-401e-9d49-ecfcdbb3d1cb

the heading is hidden . resolve the issue , also in navbar the profile avatar dropdown is not visible .

**Comment by Antima2004** [comment]
ok

**Comment by abhi03ruchi** [comment]
> ok There is no dropdown in the profile avatar in the community spotlight page.

u can remove the profile avatar then . chk now .

**Comment by Antima2004** [comment]
@abhi03ruchi by mistakenly i push the pr in this only for footer quick link changes, please make this pr level 3.

**Comment by abhi03ruchi** [comment]
both of the issues are minor bugs/tasks --> level 1 is ok .

**Comment by Antima2004** [comment]
At least give level 2 because I have make a lots of changes in styling of the quicks links @abhi03ruchi

**Comment by Antima2004** [comment]
Thanks @abhi03ruchi

**Comment by Antima2004** [comment]
Anything else that i can do?? @abhi03ruchi

**Comment by abhi03ruchi** [comment]
> At least give level 2 because I have make a lots of changes in styling of the quicks links @abhi03ruchi

i was talking about both tasks individually level 1 . 

plz be careful , from next time . only commit those changes that resolve the given issue .

**Comment by Antima2004** [comment]
> > At least give level 2 because I have make a lots of changes in styling of the quicks links @abhi03ruchi
> 
> i was talking about both tasks individually level 1 .
> 
> plz be careful , from next time . only commit those changes that resolve the given issue .

Ok thanks 🙏

**Pull request merged**
