### PR TITLE
#made the navbar similar

### PR DESCRIPTION
**Pull request by nandani-goyal**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1834 

# Description

I have made the navbar of "about us" page similar to this rest of the pages.

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
before 
Screenshot 2024-06-24 123135
home page navbar
Screenshot 2024-06-24 144039
about us navbar
Screenshot 2024-06-24 144016

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by nandani-goyal** [comment]
@huamanraj please assign me this pull request so that i can get my scores.

**Comment by RitiChandak** [comment]
@nandani-goyal Done and sorry for the inconvenience caused

**Comment by nandani-goyal** [comment]
Thank u so much @RitiChandak for your efforts but I have still not got my scores shown in the leaderboard for this pull request.

**Comment by nandani-goyal** [comment]
Please can u tell me what could possible problem?

**Pull request merged**
