### PR TITLE
To Adjust the address area in the contact page

### PR DESCRIPTION
**Pull request by Shekhar-Raj**
Fixes:  #3054 
Fixed the contaact form format and address div

<h2>Before:</h2>

https://github.com/user-attachments/assets/b3e0cfb8-cacf-4a4f-a6c4-c469d9312477

<h2>After:</h2>

https://github.com/user-attachments/assets/de2b69ab-1150-48fd-920a-e7dadf2b71e3

# Checklist:

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
try to rework on this again like i want the image in contact section beside details @Shekhar-Raj

**Comment by Shekhar-Raj** [comment]
> try to rework on this again like i want the image in contact section beside details @Shekhar-Raj 
> create new issue

Ya sure

**Comment by sailaja-adapa** [comment]
@Shekhar-Raj someone has did it thanks for ur time :)

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj someone has did it thanks for ur time :)

Ok ☺️

**Comment by sailaja-adapa** [comment]
try to allign contact section and adress section in same width

**Pull request merged**
