### PR TITLE
CREATE CUSTOM ISSUE TEMPLATE

### PR DESCRIPTION
**Pull request by alo7lika**
# Related Issue

Fixes: #4869

# Description

Creating a custom issue template for the project will streamline the process of issue reporting and tracking. This template includes specific fields that guide users to provide relevant details, making it easier for maintainers to understand, prioritize, and resolve issues effectively. This addition is expected to improve the overall quality of reported issues and enhance team productivity.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
N/A

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by alo7lika** [comment]
@anuragverma108 the task has been completed. Kindly review the PR
Don't forget to add label "GSSOC-EXT"

**Comment by alo7lika** [comment]
> @anuragverma108 the task has been completed. Kindly review the PR Don't forget to add label "GSSOC-EXT"

@abhi03ruchi @sailaja-adapa please review

**Comment by abhi03ruchi** [comment]
provide screenshot of the template u have made .

**Comment by alo7lika** [comment]
> provide screenshot of the template u have made . as we have different template for diff issues --> doc , feature ...

Screenshot 2024-11-10 113818
@abhi03ruchi

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-10 at 11 48 24 AM

on this page , u have added a section of CUSTOM ISSUE ?

**Comment by alo7lika** [comment]
> Screenshot 2024-11-10 at 11 48 24 AM
> on this page , u have added a section of CUSTOM ISSUE ?

yes

**Pull request merged**
