### PR TITLE
Bug-Footer styling and fixing

### PR DESCRIPTION
**Pull request by Molza01**
Fixes:  #4539 

# Description

There was multiple pages in which the footer was aligned improperly and in few pages there was bug too.
I had styled the footer page and have linked to all the pages and also the pages which had contained bug has been resolved too.

#4539 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)
Screenshot!!

Before!!
Screenshot 2024-11-04 014458

After!!

Screenshot 2024-11-04 031450

Bug Before!!
Screenshot 2024-11-04 013857

Bug After!!
Screenshot 2024-11-04 031947

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
#4532 is already working on similar issue . will review ur pr after merging her pr .

**Comment by Molza01** [comment]
> #4532 is already working on similar issue . will review ur pr after merging her pr .

 ok

**Comment by abhi03ruchi** [comment]
there are conflicts . 

assets/html/event.html
assets/html/fantasy.html
assets/html/romance.html
assets/html/science-fiction.html
assets/html/suspense-thriller.html
index.html

all these pages  footer is ok . recheck once and resolve conflicts carefully .

**Comment by Molza01** [comment]
Conflicts are not showing on my side , i have tried to resolve it, but in the local i am unable to see and yesterday only event.html and fantasy.html conflict was coming but now there are more conflicts?
@abhi03ruchi

**Pull request closed without merging**
