### PR TITLE
add classic-literature page and api

### LINKED ISSUE #3911: Feat: API for classic literature books
### Describe the feature

I want to write and integrate API for bringing in data for Classic Literature books. So that users will have more options to see and explore.

### Add ScreenShots

Screenshot 2024-10-23 115805

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

## fixes #3911 

Raised the PR again for the issues in  #3958

# Description

#issue #3911

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
chk deploy preview once . 
https://github.com/user-attachments/assets/5f44d6de-c77e-4bfa-8513-22894bd459f8

**Comment by haseebzaki-07** [comment]
@abhi03ruchi this is because u need to start the backend for the API to work, that is only the frontend preview @abhi03ruchi .
command to start the backend : node server.js

please attach the level tags to the PR

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi this is because u need to start the backend for the API to work, that is only the frontend preview @abhi03ruchi . command to start the backend : node server.js
> 
> please attach the level tags to the PR

then u must add this disclaimer to the page . for normal people to understand and see.

**Comment by sailaja-adapa** [comment]
@haseebzaki-07 even after I merged your PR the changes were not reflecting on website please look into it

**Comment by haseebzaki-07** [comment]
We need to deploy the backend to some service then it will be available in production. Should i raise another issue?? Assign me there and I'll do it

**Comment by sailaja-adapa** [comment]
Okk do it @haseebzaki-07

**Comment by haseebzaki-07** [comment]
Sure @sailaja-adapa

**Comment by sailaja-adapa** [comment]
@haseebzaki-07 for now stop working on that I will update you soon since then try to work on new issues

**Comment by haseebzaki-07** [comment]
Okay @sai

**Pull request merged**
