### PR TITLE
SUCCESSFULLY REARRANGE TEH CODE AND MADE THE USER INTERFACE PROPER BY SOLVING BUG.

### PR DESCRIPTION
**Pull request by dnyanesh99borse**
**### SUCCESSFULLY REARRANGE TEH CODE AND MADE THE USER INTERFACE PROPER BY SOLVING BUG.**

# Related Issue: #3583 
**SOLVED ISSUE:** #3583 

**Fixes:** #3583

**# Description**

**SOLVED ISSUE:** #3583 

# Type of PR

- [ **] Bug fix
- [ ** ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

**BEFORE:**
image
 THE OVERLAPPING AND DISTURBANCE CREATION BY THE ELEMENTS DUE TO SOME MISSPROPERTIES.

**### AFTER:** 
image

image

# Checklist:

- [ * ] I have made this change from my own.
- [ * ] I have taken help from some online resources.
- [ * ] My code follows the style guidelines of this project.
- [ * ] I have performed a self-review of my own code.
- [ * ] I have commented my code, particularly in hard-to-understand areas.
- [ * ] I have made corresponding changes to the documentation.
- [ * ] My changes generate no new warnings.
- [ * ] I have tested the changes thoroughly before submitting this pull request.
- [ * ] I have provided relevant issue numbers and screenshots after making the changes.

~Thankyou. _[hope you will like the changes, please merge the pr by encouraging me]_

### CODE REVIEW

**Comment by dnyanesh99borse** [comment]
SIR I HAD SUCCESSFULLY RESOLVE MY ISSUE AND MADE THE WEBSITE USER INTERFACE INTERACTIVE PLASE REVIEW THE CHANGES AND MERGE THE PR BY ENCOURAGING ME AND MY ART. ~Thankyou. @anuragverma108

**Comment by sailaja-adapa** [comment]
resolve conflicts and update branch @dnyanesh99borse

**Comment by sailaja-adapa** [comment]
Resolve this and notify me update your branch too

**Comment by sailaja-adapa** [comment]
Resolve this and notify me update your branch too

**Comment by dnyanesh99borse** [comment]
I HAD DID IT SUCCESSFULLY I AM REQUESTING YOU TO PLEASE REVIEW THE CHANGES AND ASSIGN THE RESPECTIVE POINTS TO MY HARDWORK PLEASE @anuragverma108

**Pull request merged**
