### PR TITLE
Added a book preference quiz

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
swapread
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #3088

# Description
Added a book preference quiz
with the gender,age,genre,author name 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
post a video where u made changes

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
> Collaborator

done uploading the quiz

**Comment by sailaja-adapa** [comment]
Post me full video from home page how u r going through that Page

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Actually there is an error in home page and other pages to open the more drop down ,i will raise a seperate isuue for that if possible but for now more is working perfectly in the about us page so i have worked from there
https://github.com/user-attachments/assets/9fcb0101-6d5b-4a87-aba0-ac0d24c2d7a9

**Comment by sailaja-adapa** [comment]
update branch

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
To what branch

**Comment by sailaja-adapa** [comment]
just go to your branch and update branch since i made some change to project see in youtube

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok, will do that.

**Comment by sailaja-adapa** [comment]
@KapuluruBhuvaneswariVspdbct  don't update branch resolve conflicts it wil be enough

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
What should I do now mam

**Comment by sailaja-adapa** [comment]
just resolve conflicts it will be enough

**Comment by sailaja-adapa** [comment]
please notify me once u r done @KapuluruBhuvaneswariVspdbct

**Comment by sailaja-adapa** [comment]
remember please don't update branch

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sure!

**Comment by sailaja-adapa** [comment]
resolve conflicts u don't know how to do that?

**Comment by sailaja-adapa** [comment]
once u r done with solving conflicts notify me @KapuluruBhuvaneswariVspdbct

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
please check  it once

**Comment by sailaja-adapa** [comment]
Thanks for your time and patience @KapuluruBhuvaneswariVspdbct

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
its my pleasure

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
can you tell me how many points will i get

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Awesome, thanks!

**Comment by sailaja-adapa** [comment]
25 marks I given level 2 because of your patience u had even though it is level 1

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Thank you

**Pull request merged**
