### PR TITLE
solved #4122 Added heade,footer to map page

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue

solved #4122 Added heade,footer to map page
Fixes:  #4122 

https://github.com/user-attachments/assets/92b0874c-0f02-4272-8636-0092e12c5ebd

# Description
solved #4122 Added heade,footer to map page

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
remove the blue back to home button  , and u may also remove the more dropdown from navbar . 

add the dark mode toggle button in navbar .

**Comment by abhi03ruchi** [comment]
and for dark mode , u can raise separate pr .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi kindly review mam

**Comment by abhi03ruchi** [comment]
behind the navbar the heading of the page is hidden . fix it too .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image
solved

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi please merge

**Comment by abhi03ruchi** [comment]
u removed the heading , plz add it back . ( how will the user know about the page map , without some description )

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image

please check @abhi03ruchi

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
mam as soon as you merge the pull request i will solve the other issues faster

**Pull request merged**
