### PR TITLE
Gssoc level1 1366

### PR DESCRIPTION
**Pull request by kapilG0**
# Related Issue

None
Fixes:  #1366

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/anuragverma108/SwapReads/assets/59639410/b6c4b9cd-b99e-4076-8620-507e16e13c68

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@kapilG0 The code you provide in that dark mode is not working anymore
image
image

**Comment by kapilG0** [comment]
> @kapilG0 The code you provide in that dark mode is not working anymore image image

Ok will check

**Comment by kapilG0** [comment]
> > @kapilG0 The code you provide in that dark mode is not working anymore image image
> > I did that change for only index.html page and that is home page on which you are checking should I do for all pages ?

Hello @RitiChandak but it is working for me please check below video 

Uploading SwapReads - Google Chrome 2024-06-08 11-30-51.mp4…

**Comment by RitiChandak** [comment]
@kapilG0 please breif me about the changes you want to do and on which file/page

**Comment by kapilG0** [comment]
> @kapilG0 please breif me about the changes you want to do and on which file/page

Yes sure @RitiChandak previously when I clicked on toggle button for changing background. The toggle icon is not reflecting on button so that why I worked on that so toggle should reflect on toggle button and background also change

**Comment by RitiChandak** [comment]
@kapilG0 okay and you made changes in index.html and style.css.

The changes you made in the index file are not working. The home page is not responding to dark mode or light mode anymore.

**Comment by RitiChandak** [comment]
@kapilG0 Please do the changes for all the pages. Uniformity should be maintained across all pages.

**Comment by huamanraj** [comment]
> > > @kapilG0 The code you provide in that dark mode is not working anymore image image
> > > I did that change for only index.html page and that is home page on which you are checking should I do for all pages ?
> 
> Hello @RitiChandak but it is working for me please check below video 
> 
> 
> https://github.com/anuragverma108/SwapReads/assets/59639410/813bb371-0cd5-4477-b253-e71b90d49ad5
> 
> 
> 

maybe you need to pull the latest code

**Comment by anuragverma108** [comment]
image
Conflicting files
assets/css/style.css


Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
