### PR TITLE
Icons on Home Page(left side-vertical)

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes: Issue  #3053 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]
I noticed that all the icons were not present on the home page. Thus felt the need to add the missing icons to website.

This fixes the ISSUE #3053 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

https://github.com/user-attachments/assets/64d1e8c4-e175-404a-9fc5-cc2756f08ed6

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please add the necessary labels and assign the PR to me: 

- level1/level2/level3
- gssoc-ext
- hacktoberfest-accepted

**Comment by rajdeepchakraborty-rc** [comment]
@sailaja-adapa Thanks for reviewing the PR! Also wanted to ask whether you would be closing the issue or should I close it?

**Comment by rajdeepchakraborty-rc** [comment]
@sailaja-adapa This was assigned directly level1 by the github bot. But I feel it should be **level2**. Since the icon div was also broken and I had to adjust the div to adjust it somewhat into the centre and fix it there along with adjusting the icons.

**Comment by sailaja-adapa** [comment]
=

> @sailaja-adapa Thanks for reviewing the PR! I just wanted to ask should this issue not be tagged **level2**? Also wanted to ask whether you would be closing the issue or should I close it?

i will close the issue its fine thanks for asking when coming to level you did on frontend only so i given level 1 since its a minor issue

**Comment by sailaja-adapa** [comment]
> @sailaja-adapa This was assigned directly level1 by the github bot. But I feel it should be **level2**. Since the icon div was also broken and I had to adjust the div to adjust it somewhat into the centre and fix it there along with adjusting the icons.

since u made these many changes i assigning you level 2 @rajdeepchakraborty-rc

**Comment by rajdeepchakraborty-rc** [comment]
Thanks @sailaja-adapa also please update the level on the issue

**Comment by sailaja-adapa** [comment]
> Thanks @sailaja-adapa also please update the level on the issue

done

**Comment by sailaja-adapa** [comment]
@rajdeepchakraborty-rc can u work on other issue on fixing navbar i feel ur work is good

**Comment by rajdeepchakraborty-rc** [comment]
> > Thanks @sailaja-adapa also please update the level on the issue
> 
> done

I am sorry but it is not visible on my end. The corresponding issue is #3053. Please can you check again.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc can u work on other issue on fixing navbar i feel ur work is good

Thanks for your appreciation. Sure I will open an Issue for that give me some time as I am working on 2 Issues currently. I will open the issue but will need some time before starting with the work. Hope you understand.

**Comment by sailaja-adapa** [comment]
Yeah that's fine Thank you remember to update branch and work since i made some changes to project @rajdeepchakraborty-rc

**Comment by rajdeepchakraborty-rc** [comment]
> Yeah that's fine Thank you remember to update branch and work since i made some changes to project @rajdeepchakraborty-rc

Sure I will start with a new updated fork if necessary. Looking forward to contributing to this repository and helping out with what I can! 😄

**Comment by rajdeepchakraborty-rc** [comment]
> work with newly updated brach

I just finished working on a project with resolving at least 7 merge conflicts(due to delay in review). I can assure you with providing the best I can.

**Comment by sailaja-adapa** [comment]
Yeah sure Looking Forward to work ☺️

**Pull request merged**
