### PR TITLE
Contact Us Section Enhancement

### PR DESCRIPTION
**Pull request by bharat-c27**
# Related Issue

Fixes:  #1823 

# Description

**1) Hover Effects (Name, Subject, Message Input Boxes) -** I added hover effects to the name, subject, and message input boxes and improved its visual appeal.

**2) Email Input box was not sized properly -** Email type input was not styled properly so fixed the bug and increased the width of the Email Type Input to its 100% width, which aligned it with other input elements.

**3) Update Contact Us Section Heading** - I have replaced the current headings "Write me anything" to "Have a Question?" with a clearer and more descriptive option like "Contact Us".

**4) Structed the css and html file** - Removed the parts of CONTACT SECTION which were not useful and repeated.

**5) Added Character Count** - The character count was not visible so made it visible.

**6) Styling the card title of Address, Phone, Email** - The styling of right side card box was not visualling appealing so reduced its padding and increased the font-size making it visually appealing.

**7) Missing Rounded Corner (Email Input Box) -**  The email input box lacks rounded corners compared to the other inputs so added appropriate styling.

Hello @huamanraj and @anuragverma108, as mentioned earlier in the issue that the css files were containg rules (**NEWSLETTER SECTION**) that were overriding the **CONTACT SECTION css rules** and hence the EMAIL INPUT in CONTACT SECTION was **not having the styling** compared to other input you can **see in below screenshot**. So it took me **around 2-3 hours** to **find that bug**, then **I structured the code** so that css rules don't override. 

So please **assign to me the labels** (gssoc and level) and can you **please re-consider the label level.**
I have found few more issue, I am happy to contrubute more to the project.

Thank you!!

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

### BEFORE : 

Screenshot 2024-06-16 152917

### AFTER : 

https://github.com/anuragverma108/SwapReads/assets/125469847/a3c43de1-c6d9-4daa-9a8b-365f34aa7513

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RishabhDhawad** [comment]
There are some conflicts in style.css file, resolve them.

**Comment by RitiChandak** [comment]
image
please resolve the conflict and create new PR

**Comment by bharat-c27** [comment]
Sure I will solve the conflict, but how I could know where the conflict is ?
@RitiChandak  @RishabhDhawad

**Comment by RitiChandak** [comment]
image
Hi @bharat-c27 this the conflicts

**Pull request closed without merging**
