### PR TITLE
Enhanced Navbar and Header for the Diverse Literacy Page

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4343

# Description

"Refined the navbar and header design on the Diverse Literacy page to ensure a fixed, streamlined user experience. The improved navigation bar now stays fixed at the top, providing easy access to key sections without interrupting page flow. Icons, dropdowns, and links were also optimized for a cleaner, user-friendly layout, enhancing overall accessibility and visual appeal."

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

# BEFORE :
image

# AFTER :
image
image

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-01 at 8 58 00 AM
it does nt look good ,  still  there is bug .

chk audio books page , copy navbar design from there and paste in ur page .

**Comment by SrijaVuppala295** [comment]
@abhi03ruchi , Okay mam !

**Comment by SrijaVuppala295** [comment]
@abhi03ruchi , please review it !!

image

**Comment by abhi03ruchi** [comment]
in dark mode text is not visible .

**Comment by abhi03ruchi** [comment]
> in dark mode text is not visible . navbar contents .

work on this , resolve this error .

**Comment by abhi03ruchi** [comment]
create another pr for it .

**Pull request merged**
