### PR TITLE
Fixes issue #2531

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
Alignment of nav items inside the navbar in login/signup page

Icons and nav items had some misplacement, the icons at the top right corner are getting overlapped.

Fixes:  #2531

This PR adjust the alignment of nav items for better UI design..

# Type of PR

- [yes ] Bug fix

# Screenshots / videos (if applicable)
Before: 
image
After:
image

# Checklist:

- [yes ] I have made this change from my own.
- [yes ] I have taken help from some online resources.
- [yes ] My code follows the style guidelines of this project.
- [yes ] I have performed a self-review of my own code.
- [yes ] I have commented my code, particularly in hard-to-understand areas.
- [yes ] I have tested the changes thoroughly before submitting this pull request.
- [ yes] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@anuragverma108 @huamanraj 
Please review this PR.
Thank you

**Comment by Bhattu-Anitha-07** [comment]
@huamanraj  Please add labels to the issue.

**Comment by Bhattu-Anitha-07** [comment]
@huamanraj 
Please review this PR and kindly assign labels.

**Comment by Bhattu-Anitha-07** [comment]
@anuragverma108 @huamanraj 
Please review this PR and assign labels.
Thank you

**Comment by huamanraj** [comment]
good work!! sorry for late PR review! i hope you understands that it takes time to review code! @Bhattu-Anitha-07

**Review by huamanraj — APPROVED** [review]

**Comment by Bhattu-Anitha-07** [comment]
Thankyou @huamanraj for merging my PR.
That's fine.
Will contribute more!!

**Pull request merged**
