### PR TITLE
Added Icons to Navbar

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Icons to Navbar - Solved #2734 
Kindly Please go through this PR @anuragverma108 

sl

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@anuragverma108 kindly please go through this PR

**Comment by huamanraj** [comment]
this issue isnt assigned yet and you created a PR?!! it is against our code of conduct! also the icons on nav is not looking good!!

**Comment by sailaja-adapa** [comment]
Yeah okk no problem @huamanraj

**Comment by sailaja-adapa** [comment]
Now I see that git assigned me I thought it was assigned to me

**Comment by huamanraj** [comment]
> Yeah okk no problem @huamanraj 

do open new relevant issues anytime i will assign that! 😊

**Comment by sailaja-adapa** [comment]
Okk Thank you @huamanraj ☺️

**Pull request closed without merging**
