### PR TITLE
upated donate books

### PR DESCRIPTION
**Pull request by abhi200446**
inka  modifications  emaina cheyala @sailaja-adapa akka

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
Conflicts resolve chaii

**Comment by abhi200446** [comment]
ha

**Comment by abhi200446** [comment]
ha

**Comment by sailaja-adapa** [comment]
duplicates vachai choodu dontions and also oka danilo image ledu choosi changes chaii

**Comment by abhi200446** [comment]
@sailaja-adapa duplicates nuvvu chepinattey modifications chesi pr pettina akka

**Comment by sailaja-adapa** [comment]
m

duplicates vunnai just konchem code remove chai chaalu two times vachesindi okasari choodu

**Comment by abhi200446** [comment]
image
chesa akka aey code nenu modify chesi petta kani neeku previous dhi chupistundhi malli pr pettala?

**Comment by sailaja-adapa** [comment]
Sare kasepu aagi merge chestha le e lopu Navbar Allign chai anni pages lo

**Comment by sailaja-adapa** [comment]
Branch update chesi malli work chai

**Comment by abhi200446** [comment]
image
idhi enti akka @sailaja-adapa

**Comment by sailaja-adapa** [comment]
Andaka nenu merge chesesthanu okk na nuvvu malli duplicate ni remove chaii

**Comment by sailaja-adapa** [comment]
> image idhi enti akka @sailaja-adapa

Branch update avuthundi anduke ala vasthundi kasepu aagi merge chaii

**Comment by abhi200446** [comment]
ha

**Comment by sailaja-adapa** [comment]
IMG_20241017_215643

Choosi update chai Navbar and edi rendu oka danikone chesi pettu oka PR lo

**Comment by sailaja-adapa** [comment]
Message me in LinkedIn

**Comment by abhi200446** [comment]
image
deniki extension em use chesav akka

**Comment by sailaja-adapa** [comment]
Phone view adi

**Pull request merged**
