### PR TITLE
inline back to top #4932

### PR DESCRIPTION
**Pull request by jainaryan04**
# Related Issue
#4932 

# Description
back to top div was taking up a new row. made it inline
# Type of PR

- [X] Bug fix

# Screenshots / videos (if applicable)
image

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
add back to top , similar to the one , on home page .

**Comment by jainaryan04** [comment]
@abhi03ruchi i tried. it's not working. some component is overlapping, i am not able to figure out which

**Comment by abhi03ruchi** [comment]
remove the back on top button , that is there in footer in events page then .

**Comment by jainaryan04** [comment]
done @abhi03ruchi

**Comment by jainaryan04** [comment]
done @abhi03ruchi

**Pull request merged**
