### PR TITLE
added achievements section

### PR DESCRIPTION
**Pull request by SanikaBhalerao1345**
# Related Issue
None

Fixes:  #3742 

# Description

added badges for various tasks on hover title is displayed(for achievement button, badge earned in my profile)

#3742 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
added a bubble
image

main site for badge information:
image
image

added some badges in my profile
image

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
can u add this functionality --> that if user signin to website , then they get the points --> and the respective badge is displayed on the profile page  .

like  github profile badges .

**Comment by SanikaBhalerao1345** [comment]
@abhi03ruchi but I have already added some badges in my profile. Are you suggesting to make changes there too?

**Comment by abhi03ruchi** [comment]
u have added all badges in the my profile for now . 

i was saying , add functionality where badges actually earned by user are displayed in there profile . like u get badge and points if u signin to SwapReads , so if user sign in karta hai toh , usse woh badge deekhe my profile par .

**Comment by abhi03ruchi** [comment]
like github mein hota hai . i have completed tasks and fulfilled some conditions so i have 3 badges .  u have 2 badges which u have earned .

**Comment by abhi03ruchi** [comment]
do u understand what i am trying to say . mujhe tuhmara samjh nhi aaya . temporary nhi hoga na , jo earn kiya hai woh rahega

**Pull request merged**
