### PR TITLE
Fix Navbar

### PR DESCRIPTION
**Pull request by KrishChothani**
Fixes:  #4028 

# Description

navbar are not align at center in lol.html
# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
BEFOR:
image

AFTER ::
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/40664742-07c4-48a7-bfeb-3c1f3018e0a9

there are still issues in the navbar . 
the dropdown of profile avatar , on clicking on more button dropdown doesnt come . 

also fix the navbar responsiveness .

**Comment by KrishChothani** [comment]
like i am not able to  find your original navbar on index.html --> it's very hard to find that --> i find minimum 40 to 50 minutes but not get --> just because of css and html code within one file and also come some css from style.html and styles.html

so it's very difficult -- > then i do only center the navbar

**Comment by KrishChothani** [comment]
if you like this changes then merged it otherwise you closed it.

**Comment by KrishChothani** [comment]
Thank you

**Comment by abhi03ruchi** [comment]
the navbars are really messed up . different pages have different navbar design . also there is problem in all navbars  . 
 u can work on this issue and resolve all pages navbar , make them uniform .

**Comment by KrishChothani** [comment]
Ohk .. i will work ...

**Pull request closed without merging**
