### PR TITLE
solved #4499 removed quiz button from navbar

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
solved #4499 removed quiz button from navbar
Fixes:  #4499
image

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@sailaja-adapa mam please merge this and try to add level2 if possible

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-03 at 5 04 20 PM

correct the alignment of the button bring it down . also on hover remove the underline .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi please go through this mam ,kindly add level2 if possible

https://github.com/user-attachments/assets/9113f285-1ef5-4f4a-971c-ce86f9143d8a

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi could you please raise the level

**Pull request merged**
