### PR TITLE
Dark mode

### LINKED ISSUE #380: Feat: Dark mode lacks UI .
### Describe the feature

In dark mode the logo is not visible and card are not shown  all are black, let me fix it.

### Add ScreenShots

Screenshot (862)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sshivangi882**
Resolved #380

Added UI to the dark mode.

<h2> Before </h2>

image

image
image

<br>

<h2>After</h2>

Screenshot (872)
Screenshot (873)
Screenshot (874)
Screenshot (875)

### CODE REVIEW

**Comment by anuragverma108** [comment]
@sshivangi882 

Great contribution to GSSOC'24! 🎉

**Comment by anuragverma108** [comment]
@sshivangi882 
How the dark mode button got removed from the navbar ?
Look into it & raise a PR for that too.

image

Vercel Preview of your PR

**Comment by sshivangi882** [comment]
let me check once! I'll improve it.

**Comment by sshivangi882** [comment]
hey! @anuragverma108  I have resolved the Dark mode button and created a pull Request. kindly have a look, and sorry for the inconvenience caused by me!!

**Pull request merged**
