### PR TITLE
Changed the styling and the look for "Different Genres" section and some interactivity so that users feel good while reading

### PR DESCRIPTION
**Pull request by ark0078**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.) #3697 solved

Enhancements:
1)Responsive Design
2)Icons for Romance and Suspense
3)Box Shadow
4)Smooth Scaling Transition
5)Hover Effect
6)Card Flip on Click
7)Animated Icons

Screenshot (305)
Screenshot (306)
Screenshot (307)
Screenshot (309)

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by ark0078** [comment]
@sailaja-adapa kindly check everything and merge it...if you want,I can change the styling of all others genres too in this same section

**Comment by abhi03ruchi** [comment]
ur changes are not visible . see deploy preview.
Screenshot 2024-10-19 at 8 05 28 PM

**Comment by ark0078** [comment]
@abhi03ruchi dear..just wait...let the project maintainer merge it first and then you can tell that...also here all the contributors come for contributing so don't peep into anyone's issue...try to find an issue and raise..thank you dear..May God bless you

**Comment by sailaja-adapa** [comment]
@ark0078 
@abhi03ruchi  is also a mentor for this project

**Comment by ark0078** [comment]
@abhi03ruchi sorry....extremely sorry....kindly do pardon me

**Comment by ark0078** [comment]
@abhi03ruchi all the checks have been passed...what's wrong with that?I'm not getting..anyways,it's your choice ..you can reject this if you want..

**Comment by sailaja-adapa** [comment]
> > @ark0078 @abhi03ruchi is also a mentor for this project
> 
> @sailaja-adapa am so sorry

its okay

**Comment by abhi03ruchi** [comment]
ur changes arent visible . chk deploy preview . 

Screenshot 2024-10-19 at 9 56 54 PM

you have updated the [ Explore different Genres] section of the home page na ?

**Comment by ark0078** [comment]
> ur changes arent visible . chk deploy preview .
> 
> Screenshot 2024-10-19 at 9 56 54 PM
> you have updated the [ Explore different Genres] section of the home page na ?

@abhi03ruchi yes, but here it's showing,it's successfully deployed...

**Comment by ark0078** [comment]
@abhi03ruchi I've just updated the 3 portions of it.....if u want,I can do it for others..ig total 27 genres are there but I've updated just 3 of them..ig for that it's not getting deployed there..you can merge this....I'll make styling for rest genres and raise another PR for this

**Comment by sailaja-adapa** [comment]
If deployment is success it doesn't mean your changes were made @ark0078  we can see your branch website like what changes u have made in your branch and we merge them accordingly as for now click on deployment preview link and see the part where u made changes and were the changes were resembling or not?  She checked like that and she is saying changes were not resembling so check once

**Comment by abhi03ruchi** [comment]
u have created  cards.html page. but u havent  integrated it in index.html . I guess this is the issue.

plz make a demo video .

**Comment by ark0078** [comment]
@abhi03ruchi am just changing the portion which i feel like it is to be changed...actually I'm not changing the website as a whole..just the part where it needs changes..so should i send the demo video which clearly depicts the portion where i've changed it? and @sailaja-adapa

**Comment by abhi03ruchi** [comment]
ya , send demo video.

**Comment by abhi03ruchi** [comment]
so this is what u have done --> created a booksreco.html page with these 3 cards . 

but , 
u have to add the code of these cards to the homepage index.html ,  [explore different genre] part . delete the code under this section and add ur new code there .

**Comment by abhi03ruchi** [comment]
are u able to get what I am trying to say . After u do this , u will be able too ur changes in deploy preview as well .

**Pull request closed without merging**
