### PR TITLE
adding pages to book recommendation 

### PR DESCRIPTION
**Pull request by Riyachauhan11**
# Related Issue
None

Fixes:  #4517

# Description
I have added book recommendations for 3 different genres accessible from their cards on home page : historical fiction, self help and biography

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
382584627-90849547-67e1-452b-bcc3-c9468b7b96eb

# Checklist:

- [ X]I have made this change from my own.
- [X] I have taken help from some online resources.
- [ X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Riyachauhan11** [comment]
pls refresh the page on chrome for more genres to be visible if they arent visible

**Comment by abhi03ruchi** [comment]
a contributor is already working on this issue . if he doesnt raise pr within few days , will merge ur pr .

**Comment by abhi03ruchi** [comment]
u can work on other issues , like enhancing events page . etc ...

**Comment by abhi03ruchi** [comment]
u can enhance the genre section on the home page . enhance the cards UI and add book recommendation button and delete the books given below it , as we have created a new page which contains book recommendations . 
Screenshot 2024-11-03 at 11 54 40 PM

**Comment by Riyachauhan11** [comment]
> meanwhile , u can work on other issues , like enhancing events page . etc ...

ill discard this pr since he seems to have raised an issue for this and work on the events page

**Comment by Riyachauhan11** [comment]
> u can enhance the genre section on the home page . enhance the cards UI and add book recommendation button ( redirect user to. the page ) and delete the books given below it , as we have created a new page which contains book recommendations . Screenshot 2024-11-03 at 11 54 40 PM

ok ill try to work on this after the events page

**Pull request closed without merging**
