### PR TITLE
🛠️FIX: volume control  , playback speed of Audio book added

### PR DESCRIPTION
**Pull request by akash70629**
# Related Issue

“None”

Fixes:  #4462

# Description

Added favicon links, font awesome stylesheet, and audio controls; and commented out input range and time info elements as it looks bad, in future if someone wants to use them they can.

# Key feature added

1. Volume Control
2. Playback speed

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)

## Before
image

## After
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by akash70629** [comment]
@abhi03ruchi please review and merge the PR.

**Comment by abhi03ruchi** [comment]
add playback speed in premium books too .

**Comment by abhi03ruchi** [comment]
the login form isnt working , firebase auth error is displayed . 

u may work on the issue and raise new pr

**Comment by akash70629** [comment]
> the login form isnt working , firebase auth error is displayed .
> 
> u may work on the issue and raise new pr

Ok , I'll take a look and try to fix it.

**Comment by akash70629** [comment]
> the login form isnt working , firebase auth error is displayed .
> 
> u may work on the issue and raise new pr

@abhi03ruchi The error message "Firebase: Error (auth/operation-not-allowed)" indicates that the authentication method  (Facebook sign-in)  has not been enabled in your Firebase project settings. Can you check and let me know?

**Comment by abhi03ruchi** [comment]
facebook , google and normal sign in with password . kuch nhi chal raha . sab mein same message .  "Firebase: Error

**Comment by akash70629** [comment]
> facebook , google and normal sign in with password . kuch nhi chal raha . sab mein same message . "Firebase: Error

@abhi03ruchi 
Haan just notice kiya ki normal email,password see bhi nehi ho raha facebook k sath  , Par Google se to ho gya hai mera 😕


https://github.com/user-attachments/assets/a5648658-8d40-4f11-bfb9-334467745ac2

**Pull request merged**
