### PR TITLE
Fixed navbar  hover effect

### PR DESCRIPTION
**Pull request by Ketanop321**
issue no:- #1997 

Fixed hover effect of navbar 

Before fixing issue
https://github.com/anuragverma108/SwapReads/assets/146806880/55ac98d7-b50a-4858-b9ff-37958cf66dd6

After fixing the issue
https://github.com/anuragverma108/SwapReads/assets/146806880/43803812-1e5d-4968-a7f3-9bf8a0029a82

### CODE REVIEW

**Comment by Ketanop321** [comment]
@huamanraj  atleast make it label of level 1 , it took me hours just to find that mistake 😭

**Comment by Gamerking177** [comment]
@huamanraj pls add level1 plss sir

**Comment by huamanraj** [comment]
> @huamanraj  atleast make it label of level 1 , it took me hours just to find that mistake 😭

i can but how it is going to get removed by gssoc because the 1 line change will not be accepted as any level! and it will effect the repo also it could be temporarily blocked from GSSOC i hope you understand

**Comment by Gamerking177** [comment]
@huamanraj sir pls check the deployed link before merge it into main plss sir

**Pull request merged**
