### PR TITLE
Modified navbar on the homepage.

### PR DESCRIPTION
**Pull request by meetarora10**
# Related Issue

Fixes:  #2260

# Description
I have modified the navbar for responsive view and also aligned the contents on the center. The navbar is now clearly visible on click of the hamburger icon.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)
Screenshot (629)
Screenshot (628)
Screenshot (627)

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
image
image
ig the changes you created has distorted about us navbar please recheck

**Comment by RitiChandak** [comment]
Make the changes and create a new PR or reopen this

**Comment by meetarora10** [comment]
I will check

**Comment by meetarora10** [comment]
@RitiChandak the about us navbar was like this without my PR also.
Please can you check it once again and tell me whether to create a new PR.

**Comment by meetarora10** [comment]
@RitiChandak please reply this PR was not disturbing the about us navbar . 
Please check once.

**Pull request closed without merging**
