### PR TITLE
[FEATURE]: Added a Returns and Refunds Page 

### PR DESCRIPTION
**Pull request by paridhi1114**
# Related Issue

None

Fixes:  #3981 

# Description

I have added a Returns and Refunds Page to the website which will enable users to understand the intricacies of shipping and returns and refunds related process in case they face some damage or misplacement of the book and will guide them regarding the further steps that they should take and how we as SwapReads team could help them.

I have added the link for this page in the footer on home page.

Issue #3981 

# Type of PR

- [x] Feature Enhancement

# Screenshots / videos (if applicable)
image
I have added the link for the same by the name of "Refund Policy" in the footer on home page.
image

# Checklist:

- [x ] I have made this change from my own.
- [x ] I have taken help from some online resources.
- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/cc11d70e-aff7-4c4e-a856-7da3f4854876

fix the bug .

**Comment by abhi03ruchi** [comment]
update all footers with the link of new page .

**Comment by paridhi1114** [comment]
https://github.com/user-attachments/assets/9601f4a5-878f-459b-9172-7fb20c1dc8fc

@abhi03ruchi but it is working perfectly at my end. So what should I do right now?

**Comment by paridhi1114** [comment]
https://github.com/user-attachments/assets/8a28df68-8293-4a33-9194-16c5cc15d768

@abhi03ruchi but it is working perfectly at my end. So what should I do right now?

**Comment by abhi03ruchi** [comment]
chk depoly preview once .   the redirecting link must be --> /refundpolicy.html and not /SwapReads/refundpolicy.html .

Screenshot 2024-10-27 at 10 47 56 PM

**Comment by paridhi1114** [comment]
@abhi03ruchi  I have fixed the bug and added the link to footers of all pages. Please let me know if it is working at your end.

**Comment by abhi03ruchi** [comment]
there are many more pages in the website . in their footer section add the refund link . 

u can work on this issue and create new pr .

**Comment by paridhi1114** [comment]
okay sure, thanks @abhi03ruchi !

**Pull request merged**
