### PR TITLE
Bug fixer

### PR DESCRIPTION
**Pull request by dipak2005**
# Related Issue
fixes issue : #4245 
closes issue : #4245 

Fixes:   #4245 

# Description

changing alignment  of the navbar on about us page

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
add before after screenshots . or demo video

**Comment by abhi03ruchi** [comment]
resolve conflicts.

**Comment by dipak2005** [comment]
> resolve conflicts.

i resolve the conflict and i upload before and after ss
before changes :
Screenshot 2024-10-30 000252
after changes : 
Screenshot 2024-10-30 014204

**Comment by abhi03ruchi** [comment]
chk deploy preview . everything is messed up after u resolved conflicts . 

work on updated branch .

**Comment by abhi03ruchi** [comment]
> > resolve conflicts.
> 
> i resolve the conflict and i upload before and after ss before changes : Screenshot 2024-10-30 000252 after changes : Screenshot 2024-10-30 014204


for navbar , fix the position of dark mode toggle . when we click on it , it shifts . 
everything else is fine .

**Comment by dipak2005** [comment]
> for navbar , fix the position of dark mode toggle . when we click on it , it shifts . everything else is fine .
> 
> Screenshot 2024-10-30 at 8 31 14 AM

ok ma'am

**Comment by dipak2005** [comment]
solve the issue according to deployment : 
here SS:
Screenshot 2024-10-30 103435

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/a38ceb62-cfdb-43e5-bed8-b4ac70a1bcc9

work on updated branch . raise new pr .

**Comment by dipak2005** [comment]
> Screen.Recording.2024-10-30.at.11.56.50.AM.mov 
> work on updated branch . raise new pr . the issue isnt resolved .

ok ma'am

**Pull request closed without merging**
