### PR TITLE
add navbar and footer

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4260 

This PR adds a consistent navbar and footer to the Cookie Policy page to improve navigation and user experience. The navbar provides links to major sections, and the footer includes links to important policies, aligning the Cookie Policy page with the overall site structure.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before:

https://github.com/user-attachments/assets/372baf38-8de7-496a-8f9f-2da78a21a653

After:

https://github.com/user-attachments/assets/422eebc2-5be8-4491-be6b-eaa79b326d11

# Checklist:

- [x] I have made this change from my own.

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
Screenshot 2024-10-30 at 1 56 26 PM
where is the link to open the page ?

**Comment by Antima2004** [comment]
IMG_20241030_141351
@abhi03ruchi

**Comment by abhi03ruchi** [comment]
the recommend link isnt working in footer . fix it .

**Comment by Antima2004** [comment]
Ok

**Comment by Antima2004** [comment]
I have linked the recommend pages in the footer of the cookie policy pages @abhi03ruchi

**Comment by Antima2004** [comment]
@abhi03ruchi there are 2-3 pages of your website in which recommend page its working

**Comment by abhi03ruchi** [comment]
no , level 2 is ok . 
In our project we will assign level 3 for either more no of commits or some new feature Introduction .

**Pull request merged**
