### PR TITLE
Modified the Tips page

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Related Issue

Fixes:  #4111 

# Description

The Authors Page was looking very bland before. I have modified the cards and added images of the Authors, which makes the page visually appealing. I have also modified and moved the name of the authors in the front of the card to the bottom of the card so that the author's face is clearly visible. 
The cards were sticking with the navbar before. I have also added space between the navbar and the first row of cards to make it look much neater. Also the Page title was previously **About Us**. I changed it to **Authors** to make it accurate.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
- Before

https://github.com/user-attachments/assets/436b435b-93d6-4241-9b61-fe64484a09aa

- After

https://github.com/user-attachments/assets/1fa3e684-aa55-4c63-801e-b91d74390ddb

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please review the PR and assign it to me along with proper labels.

**Comment by rajdeepchakraborty-rc** [comment]
Also, I have a general doubt about the repository that I want to know. Since the issues are being assigned automatically by the GitHub Bot, there's a high chance that similar issues are being opened. How do you all handle that? I was just curious and wanted to know.

**Comment by rajdeepchakraborty-rc** [comment]
@atmajaa Thanks for reviewing the PR. Also shouldn't the PR be labelled **level2**? I had resolved a similar issue before and it was level2

**Comment by abhi03ruchi** [comment]
> Also, I have a general doubt about the repository that I want to know. Since the issues are being assigned automatically by the GitHub Bot, there's a high chance that similar issues are being opened. How do you all handle that? I was just curious and wanted to know.

preference is given to person who raises pr first . also we also chk issues , and if some issues are redundant or useless if we close them there only .

**Comment by rajdeepchakraborty-rc** [comment]
Ok. Thanks for the clarification. I was wondering this because it is rare to see the issues being assigned by the bot. Thanks for all the hard work you are doing! Hope you all have a great day/night ahead!

**Pull request merged**
