### PR TITLE
💥FIX : Unwanted page removed

### PR DESCRIPTION
**Pull request by akash70629**
# Related Issue

“None”

Fixes:  #4974 

# Description

Unwanted page removed. Here are the removed file `cookies.html` , `darkmode1.html` , `email.css `, `emails.html `, `footer.html` , `footer.css` , `e.html` , `e.css` ,` e.js` .

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by akash70629** [comment]
@abhi03ruchi please review and merge the PR.

**Comment by akash70629** [comment]
@abhi03ruchi merge kar lo yaar !!! 7 bajne wale hai !!!

**Comment by abhi03ruchi** [comment]
7 pm over hai kya ?

**Comment by akash70629** [comment]
> 7 pm over hai kya ?

Haan !!!
Screenshot_2024-11-10-18-53-27-986_com android chrome

**Comment by akash70629** [comment]
> thanks for informing , i didnt know . merged other prs too .

@abhi03ruchi Wo log to bach gye mere or apke waja see !! lekin mera point pain me gya !! chapak !!!!😢😢

ye dekho bhai ne merge hi nehi kiya !!!  bich me aaya 2 merge kiya fir bhag gya !!!

image


Pata nehi bhai ka kya dusmani hai mere se !😥

**Pull request merged**
