### PR TITLE
created local storage for 2 forms✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.) issue #3040 

# Description
I have added local storage to 2 forms , rate us form and contact form.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Screenshot 2024-10-07 at 5 43 22 PM

Screenshot 2024-10-07 at 5 43 16 PM

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@anuragverma108 can you please review this PR. this was initirally given level1 but since i did for 2 forms can u please give me a higher level.

**Comment by sailaja-adapa** [comment]
@T-Rahul-prabhu-38 resolve conflicts and update branch and even deployment failed can u create new PR

**Comment by T-Rahul-prabhu-38** [comment]
can you give me write access

**Comment by T-Rahul-prabhu-38** [comment]
i just need to remove some inline css , i can do it here if you give me write access.

**Pull request closed without merging**
