### PR TITLE
Add hover effect

### PR DESCRIPTION
**Pull request by Antima2004**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #3469 

Added hover effect to the social media icon (Discord) in the login page.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before:
https://github.com/user-attachments/assets/b4a466d2-3ea8-43f0-b995-f607d23b90cc
After:
https://github.com/user-attachments/assets/44d32b1d-f21a-45a8-a7ae-4c13f02545aa
# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Antima2004** [comment]
@anuragverma108 
fixes the issue #3469, please merge it.

**Comment by sailaja-adapa** [comment]
work with updated branch since some changes were made

**Comment by Antima2004** [comment]
@sailaja-adapa 
I un fork the repository and then fork and start the new branch and make changes to that.

**Comment by sailaja-adapa** [comment]
Yeah okk @Antima2004 after that notify me once

**Pull request closed without merging**
