### PR TITLE
i have successfully added scroll to top button to community spotlight page ..

### PR DESCRIPTION
**Pull request by 2004pra**
… page
https://github.com/user-attachments/assets/d987c251-d216-4efe-91aa-04bbd8cf2911

Fixes:  #4057

# Description

i have successfully added the javascript , css for the scroll to top button and also verfiied it by previewing it multiple times.
it was amazing experience to contribute with your projects. 

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

#screenshots         

https://github.com/user-attachments/assets/179acce7-d500-431a-bf4f-2af4d2595236

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by atmajaa** [comment]
@2004pra add screenshots/videos of you work

**Comment by 2004pra** [comment]
please sir if you can make it level 2 as i havent
got any good points  please sir ..

**Comment by 2004pra** [comment]
ok sir new pr will be there is few minutes

**Comment by 2004pra** [comment]
the new changes have been made @abhi03ruchi @atmajaa 
please review it

**Comment by abhi03ruchi** [comment]
the scroll to top button is not present on most of the pages in the website . 
add it in all pages , will increase ur level . 

u may work on the issue and raise pr .

**Pull request merged**
