### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by dishathakurata**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1646 

# Description
1. Added additional content after clicking 'Learn more'
2. Added a function to hide the cookie after a click

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Before:
cookie

After:
1. Single cookie content
Single cookie

2. Additional content after clicking learn more
learn more content

4. Cookie hidden after a click
hidden

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

@huamanraj Label this PR with at least level2 under GSSoC24 as I worked on multiple issues in one.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@dishathakurata Learn More is not working 

We apologize, but this is a level 1 issue.

**Comment by dishathakurata** [comment]
@RitiChandak I'm sorry, my mistake. Let me update learn more.

**Review by dishathakurata — COMMENTED** [review]
@RitiChandak Please review this commit, and sorry for inconvenience.

**Comment by anuragverma108** [comment]
@dishathakurata 

Great contribution to GSSOC'24! 🎉
I gave you level 2 for this contribution!

**Pull request merged**
