### PR TITLE
Add Books and details to Poetry, Philosophy and Adventure

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4552 

# Description

This PR adds books with details to the Poetry, Philosophy and Adventure genre.
issue #4552

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-04 102551
Screenshot 2024-11-04 102603

# Checklist:

- [X]I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
change the navbar and footer of these pages . chk https://swapreadsconnect.netlify.app/assets/html/fantasy page .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi should i change the card designs also like in the above page. Like titles below the cards.

**Comment by abhi03ruchi** [comment]
no , just change navbar and footer .

**Comment by haseebzaki-07** [comment]
Okay

**Comment by haseebzaki-07** [comment]
@abhi03ruchi made the changes. Please check!

**Comment by abhi03ruchi** [comment]
fix the toggle button it is shifting . 

will merge the pr then .

**Comment by abhi03ruchi** [comment]
and do these changes in  pr #4555 too .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi made the toggle button changes here

**Comment by abhi03ruchi** [comment]
are u able to view these changes on the website .  is it visible to u or its my internet .

**Comment by abhi03ruchi** [comment]
@haseebzaki-07  , u have deleted the footer from the fantasy page .  add it back in new pr . 

be careful from next time .

**Comment by haseebzaki-07** [comment]
@abhi03ruchi sorry for the mistake, I am bringing it back

**Comment by haseebzaki-07** [comment]
@abhi03ruchi can I add two genre books at a time?? Will I get the same levels??

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi can I add two genre books at a time?? Will I get the same levels??

no , add 3 .

**Pull request merged**
