### PR TITLE
updated the rate us section

### PR DESCRIPTION
**Pull request by nandani-goyal**
# Related Issue

Fixes:  #2510 

# Description

I have made the changes in the rate us section as per commented in the issue 2510.

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-07-18 120345
Screenshot 2024-07-18 120400
Screenshot 2024-07-18 120408
Screenshot 2024-07-18 120418
Screenshot 2024-07-18 120424
in the dark mode
Screenshot 2024-07-18 120447
Screenshot 2024-07-18 120457

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by nandani-goyal** [comment]
kindly merge this pull request

**Comment by RitiChandak** [comment]
image
Not in the center correct it

**Review by RitiChandak — CHANGES_REQUESTED** [review]
image
not in the center

**Comment by nandani-goyal** [comment]
Ok I will the changes

**Pull request merged**
