### PR TITLE
solved #4125 added dark mode map pages 

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
added dark mode map pages 

https://github.com/user-attachments/assets/c2a277ff-1ca8-494a-9269-75015c483070

Fixes:  #4125 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi  please review  try to add level 3 mam

https://github.com/user-attachments/assets/3d9b20cf-d1d6-4bc8-9e99-2e12d4818d99

**Comment by abhi03ruchi** [comment]
the dark mode toggle button isnt there in the navbar.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image
it is not visible clearly

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@abhi03ruchi mam could you please merge this later i will change that toggle button because the gssoc ends by tomorrow mam ,i will work on all other  isssues raised by me mam ,if you merge this i will do that changing of button later mam,please merge it i will complete other isses too as fast as posible because coding period ends tomorrow

**Comment by sailaja-adapa** [comment]
@KapuluruBhuvaneswariVspdbct you can start on other issue even if we didn't merged your PR

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
thank you

**Pull request merged**
