### PR TITLE
 The text is invisible on Dark mode and the titles are too small in contact section(fixes #4301)

### LINKED ISSUE #4301: BUG: The text is invisible on Dark mode and the titles are too small in contact section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Screenshot (331)
Screenshot (332)
here the above two images show the difference in text color o the side headings of contact us form
I'd like to change and enhance them so that they are visible in both the modes
Screenshot (334)
Also the above texts have a question and get in touch need enhancements in both dark and light modes along with the font size 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by laxmikandivalasa**
# Related Issue
None
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4301 

# Description
on dark mode name,email and remaining..those titles only not visible on dark mode
therefore I've changed the color of the text so that that problem of invisibility of text doesn't occur
now it becomes visible in both light and dark modes
also changed color of address
increased font sizes

# Type of PR

- [ X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Screenshot (339)
Screenshot (340)
Screenshot (341)

# Checklist:

- [ X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ X] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have made corresponding changes to the documentation.
- [X ] My changes generate no new warnings.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
remove have a question and get in touch line . it is not visible properly in dark mode .

**Comment by laxmikandivalasa** [comment]
@anuragverma108 can you review this pr??

**Comment by laxmikandivalasa** [comment]
@anuragverma108 I'd like to do any other changes!

**Comment by abhi03ruchi** [comment]
remove all of this . delete it

**Comment by abhi03ruchi** [comment]
change address location color  from pink to blue 

Screenshot 2024-11-02 at 2 14 46 PM

**Comment by laxmikandivalasa** [comment]
@abhi03ruchi can you review now?

**Pull request merged**
