### PR TITLE
Add genre books and details to AUTOBIOGRAPHY

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

Fixes:  #4581

# Description

#issue #4581

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-05 001711

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
will merge ur pr after #4596

**Comment by haseebzaki-07** [comment]
okay @abhi03ruchi

**Comment by abhi03ruchi** [comment]
chk https://swapreadsconnect.netlify.app/#genre , when we click book_recomm button , then autobiography page isnt opened.

**Comment by haseebzaki-07** [comment]
@abhi03ruchi It is opening and Do u have more issues on mind that I can work on!!

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi It is opening and Do u have more issues on mind that I can work on!!


https://github.com/user-attachments/assets/7cbf0330-e660-4e29-853e-3ca0a040140b

**Comment by abhi03ruchi** [comment]
https://swapreadsconnect.netlify.app/assets/html/classic , isme bhi add the summary or details .

**Pull request merged**
