### PR TITLE
Navbar Alignment and Usability Improvements

### PR DESCRIPTION
**Pull request by Bhupendrakumar20**
# Navbar Alignment and Usability Improvements

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4440 

# Description

1. Redesign the navbar layout to ensure consistent spacing and alignment between items.
2. Utilize a dropdown menu for secondary items under a "More" section to reduce clutter.
3. Apply uniform styling across all navbar items for a cohesive look.
4. Implement a clear and visible toggle button for the dropdown menu.
5. Ensure that the navbar is fixed at the top of the page for easier accessibility.

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Screenshot_2-11-2024_43351_127 0 0 1]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Bhupendrakumar20** [comment]
@abhi03ruchi kindly go through ..and possibly merge it pls

**Comment by abhi03ruchi** [comment]
add the dropdown icon also beside More . 
Screenshot 2024-11-02 at 8 40 54 AM

**Comment by abhi03ruchi** [comment]
also there is some repetition , fix it 
Screenshot 2024-11-02 at 9 00 24 AM

**Comment by abhi03ruchi** [comment]
chk deploy preview

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/b89d01c2-6b65-42de-b63b-20deddda4000

fix it too .

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/0e563ff9-8e67-492f-b57f-b6f01dc2c167

also in dark mode in more dropdown doesnt look good , add black backgrd and white font color , hover effect is ok .

**Comment by abhi03ruchi** [comment]
u have also done changes in login page footer ? undo them . 

commit only those changes that are related to the u issue mentioned .

**Comment by Bhupendrakumar20** [comment]
Sure !! May you please add level 1 to this issue

**Comment by abhi03ruchi** [comment]
this is level 2 task .

**Comment by abhi03ruchi** [comment]
are u working on the issue ?

**Comment by Bhupendrakumar20** [comment]
Yes

**Comment by Bhupendrakumar20** [comment]
Surely complete tonight

**Comment by Bhupendrakumar20** [comment]
yes ...surely completed tonight

**Comment by abhi03ruchi** [comment]
> yes ...surely completed tonight

do complete it , its an imptt issue .

**Pull request closed without merging**
