### PR TITLE
Feat:in desktop after click on more it is not working properly #1368

### PR DESCRIPTION
**Pull request by kapilG0**
# Related Issue

None

Fixes:  #1368 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@kapilG0 please resolve the conflict
image

**Comment by kapilG0** [comment]
Hello @RitiChandak can you check now I resolve in the same commit

**Comment by huamanraj** [comment]
> Hello @RitiChandak can you check now I resolve in the same commit

still conflicts

**Comment by anuragverma108** [comment]
image
Conflicting files
assets/css/style.css


Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
