### PR TITLE
fixed more button and its dropdown menu alignment

### PR DESCRIPTION
**Pull request by Ketanop321**

### CODE REVIEW

**Comment by Ketanop321** [comment]
fixed more button dropdown menu under the more button and alignment of dark mode button

**Comment by Ketanop321** [comment]
fixed the more button and its dropdown menu and alignment of dark mode

**Comment by Ketanop321** [comment]
Screenshot 2024-05-26 135951
fixed dropdown menu of more button and alignment of dark mode

**Comment by Gamerking177** [comment]
all the best @Ketanop321

**Pull request merged**
