### PR TITLE
Twitter icon

### PR DESCRIPTION
**Pull request by Adityazzzzz**
**Add twitter icon along with other social media icon with full css and transitions.**

# Related Issue

Fixes:  **#3249** 

# Description
Older version does not contains one missing social media icons i.e. **TWITTER** 
I have added it to the home page below other social media icons.

# Type of PR

**- [x] Feature enhancement**

# Screenshots / videos (if applicable)
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Adityazzzzz** [comment]
please add the gssoc-ext and hacktoberfest tags.

**Comment by sailaja-adapa** [comment]
update branch @Adityazzzzz

**Comment by sailaja-adapa** [comment]
@Adityazzzzz  work on new issue since your icons were collding with navbar

**Comment by Adityazzzzz** [comment]
Sure!! Thankyou for guiding

**Comment by sailaja-adapa** [comment]
welcome :)

**Pull request merged**
