### PR TITLE
Added a Custom cursor effect in Website 

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
# Related Issue

Fixes:  #2961 
Please Merge the pull request and give a level3 label 

# Description
-> Used Recursive pattern of Circles for attractive cursor design .
-> It makes website more attractive and User-Interactive.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/9f6114a7-5bb0-4166-ab20-8beb9f08a96f

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
update branch

**Comment by sailaja-adapa** [comment]
Uploading r.mp4…

it's not working properly @AnujShrivastava01

**Comment by AnujShrivastava01** [comment]
Pls check now its working fine 

https://github.com/user-attachments/assets/2b1a7152-c5ec-4283-bb1e-a255fac833e8

**Comment by AnujShrivastava01** [comment]
Pls check now its working fine 

https://github.com/user-attachments/assets/2b1a7152-c5ec-4283-bb1e-a255fac833e8

**Comment by sailaja-adapa** [comment]
resolve conflicts @AnujShrivastava01

**Comment by AnujShrivastava01** [comment]
I have resolved the conflicts , Now please give me a level3 label and merge the pull request.

**Pull request merged**
