### PR TITLE
Fixed all misalignment issue in main page ! #3728

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #3728

All misalignment Issue - #3728

Fixed all misalignment Issue in main page -

https://github.com/user-attachments/assets/6ed9d3dd-cfb7-4af2-8b0f-663aea4c85e1

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________
# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@sailaja-adapa ma'am check my videos and code & give me "Level 3" for it because I fixed all misalignment issue in main page(Header, navbar, icon, buttons, text, text box, banner, heading text...)

Thank You  🙏🏻

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/ea039186-4c2c-44df-8452-2ede94641402

the pricing section boxs are misaligned , there is no space in right margin . U may reduce the size of the boxs to solve the issue. They are v large.

**Comment by Subhajit-2023-44** [comment]
> Screen.Recording.2024-10-19.at.7.32.20.AM.mov 
> the pricing section boxs are misaligned , there is no space in right margin . U may reduce the size of the boxs to solve the issue. They are v large.

image
image

**Comment by abhi03ruchi** [comment]
this issue is irrelevant , there are no major alignment issue now . I chked , u have deleted the code . and pasted the same again. (majority part )

Find other issues and raise new pr .

**Comment by Subhajit-2023-44** [comment]
> this issue is irrelevant , there are no major alignment issue now . I chked , u have deleted the code . and pasted the same again. (majority part )
> 
> Find other issues and raise new pr .

What 😱? l spent 2 hours for solving all these issues in one PR... and you closed my PR without seeing... 

@abhi03ruchi See all these issues still exist - 


https://github.com/user-attachments/assets/9579f9dd-a1bc-43aa-a706-7fcf44b96d3e


@abhi03ruchi Please merge my PR with level 3, because I fixed all misalignment issue in main page(Header, navbar, icon, buttons, text, text box, banner, heading text...)

@sailaja-adapa ma,am please look into this matter 🙏🏻..

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi ??

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi @sailaja-adapa Please merge my PR with level 3

**Comment by Subhajit-2023-44** [comment]
@abhi03ruchi @sailaja-adapa Please merge my PR with level 3

**Comment by anuragverma108** [comment]
@Subhajit-2023-44 
PA this side!
image

Why you are trying to fool us ? You are deleting the same lines of code & pasting it again. You have did this only. 

We are unable to identify your contribution in the current PR. Kindly attach **before and after screenshots** to clearly showcase the changes you have made. Additionally, please provide a detailed explanation of the work you have done in the PR description. This will help us better understand your contribution and proceed with the review. Kindly open a New PR

Thank you!

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 PA this side! image
> 
> Why you are trying to fool us ? You are deleting the same lines of code & pasting it again. You have did this only.
> 
> We are unable to identify your contribution in the current PR. Kindly attach **before and after screenshots** to clearly showcase the changes you have made. Additionally, please provide a detailed explanation of the work you have done in the PR description. This will help us better understand your contribution and proceed with the review. Kindly open a New PR
> 
> Thank you!

@anuragverma108 PA I am not trying to fool you in any way...  It took me 2 hours to solve all these issues, there are a lot of misalignment issues👀 on this whole page, so I had to delete the values and check with new values to see if everything is aligned properly or not.  So you think it is and you're just showing me these lines.  See how many changes I made to fix the whole issue 👇🏻


https://github.com/user-attachments/assets/b799e283-7343-4b04-af18-8cc16eb7b2c8

⭐& you said this - "We are unable to identify your contribution in the current PR. Kindly attach before and after screenshots to clearly showcase the changes you have made..." 😮😱

🔴Check again I have provided both before and after videos.  How can you say this even after checking the videos?  Please see the issues that I have resolved...

Before - #3728 

@anuragverma108 PA please merge my PR with level 3..

Thank You 🙏🏻

**Comment by anuragverma108** [comment]
@Subhajit-2023-44 Open a new PR

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Open a new PR

@anuragverma108 Sir see how many changes I have made, you are asking me to made a new PR😓.. That would require me to change everything from beginning which would waste a lot of time, I already wasted a lot of time solving it, and even then I wouldn't get more than level 3 for it 😞...

Sir kindly merge this PR 🙏🏻🥺

**Comment by Subhajit-2023-44** [comment]
> > @Subhajit-2023-44 Open a new PR
> 
> @anuragverma108 Sir see how many changes I have made, you are asking me to made a new PR😓.. That would require me to change everything from beginning which would waste a lot of time, I already wasted a lot of time solving it, and even then I wouldn't get more than level 3 for it 😞...
> 
> Sir kindly merge this PR 🙏🏻
> 
> Hope you understand me 🥺

@anuragverma108 ??

**Pull request closed without merging**
