### PR TITLE
Done Validation in Book Exchange Hub and Improved Rate US UI

### PR DESCRIPTION
**Pull request by PankajR007**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(767.)

# Description

[Added the Validation for Book Exchange Hub. Made it more specific. Enhanced the UI of Rate US and the Thank you UI after submitting the Rating]

#767 

# Type of PR

- [ X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Before Validation
Screenshot (36)
AfterValidation
Screenshot (46)

Before Nav bar 
Screenshot (35)
After Nav bar
Screenshot (47)

Before UI
rate us issue

After UI
RateusUpdatedCode

Added Close Button (X) to Thank you Box.
AddedXButton in thank you box

# Checklist:

- [X ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ X] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have made corresponding changes to the documentation.
- [ X] My changes generate no new warnings.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by RitiChandak** [comment]
image
Conflict file

**Comment by PankajR007** [comment]
What need to be Done?

**Comment by huamanraj** [comment]
> What need to be Done?
> 

pull the latest codebase and make changes in that and create PR and tag me

**Comment by anuragverma108** [comment]
image
Conflicting files
assets/css/style.css


Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
