### PR TITLE
Navbar Fixed

### PR DESCRIPTION
**Pull request by rishmiiee26**
Successfully fixed the navbar. Issue #404 
Attaching before:
SwapReads Navbar Before

after: 
SwapReads Navbar After

### CODE REVIEW

**Comment by rishmiiee26** [comment]
Before:
SwapReads Navbar Before

After: 
SwapReads Navbar After

**Review by huamanraj — APPROVED** [review]

**Comment by huamanraj** [comment]
> Successfully fixed the navbar. Issue #404 
> Attaching before:
> SwapReads Navbar Before
> 
> after: 
> SwapReads Navbar After
> 
> 
> 
> 
> 
> 
> 
> 

there are some conflicts,  resolve it then i will merge it!

**Comment by rishmiiee26** [comment]
Changes are made & resolved!

**Comment by anuragverma108** [comment]
@rishmiiee26 

Make sure to pull all the existing changes before pushing anything. Solve the above conflicting issues and raise your PR again.

Conflicting files
assets/html/rate.html

**Pull request closed without merging**
