### PR TITLE
solved #4066 Added map pointing low,medium,high readers states in india

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
 Added map pointing low,medium,high readers states in india
Fixes:  #4066 

# Description

https://github.com/user-attachments/assets/63e8583a-ad02-48c7-bdd4-bce424026886

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Please add level3 label mam,by considering my efforts 

https://github.com/user-attachments/assets/b8bc405f-cfb0-4ff1-a00a-ab69e184def4

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
What is  the mistake,can you elaborate

**Comment by sailaja-adapa** [comment]
See the Navbar community spotlight option is appearing double times not Alligned properly rest of fine @KapuluruBhuvaneswariVspdbct

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@sailaja-adapa  kindly check once and try to add level3 mam

**Comment by abhi03ruchi** [comment]
what is your source ? based on which u have made this map ?

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
openleaflet

**Comment by abhi03ruchi** [comment]
Screenshot 2024-10-27 at 8 45 54 PM
the map of india is distorted , add the correct map .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image
i think this is ok

**Comment by abhi03ruchi** [comment]
nhi hai . add a new map . 

Screenshot 2024-10-27 at 8 55 28 PM

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image
is it ok

**Comment by abhi03ruchi** [comment]
no

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image
changed level3 please

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@sailaja-adapa please chweck

**Comment by abhi03ruchi** [comment]
enhance the UI of the page . add navbar , footer and dark mode . 

u can work on these issues and raise pr for it .

**Comment by sailaja-adapa** [comment]
Good work keep Contributing @KapuluruBhuvaneswariVspdbct  :)

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
thank you

**Pull request merged**
