### PR TITLE
UI of terms and condition and privacy policy is enhanced

### PR DESCRIPTION
**Pull request by adityalaxkar123**
now ui of terms and condition is enhance 

my issue no. is #3924

### CODE REVIEW

**Comment by atmajaa** [comment]
@adityalaxkar123 please add screenshots/videos of the changes you have made.

**Comment by adityalaxkar123** [comment]
Ok

**Comment by adityalaxkar123** [comment]
https://github.com/user-attachments/assets/14b59c2e-1111-4123-b77f-4b021d0779f8


https://github.com/user-attachments/assets/eb846c34-1a6f-4023-af79-2f4991615233

**Comment by abhi03ruchi** [comment]
in terms and condition page , add navbar and footer ( from the community spotlight page ) .

remove the white background from privacy page . 

create a new issue to incorporate these changes .

**Pull request merged**
