### PR TITLE
🛠️Fix : Book pref page quiz section 

### PR DESCRIPTION
**Pull request by akash70629**
# Related Issue

"None"

Fixes:  #4758 

# Description
Book pref page's UI changed and quiz section added.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/32e5e797-d427-4526-90a3-ab26ec255159

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
Screenshot 2024-11-08 at 8 03 06 AM


add this page link in Footer Quick Links . [ BOOK QUIZ ].  
ADD TERMS AND CONDITIONS BELOW THE HOEIZONTAL LINK WITH COPYRIGHT , PRIVACY ETC...

**Comment by akash70629** [comment]
image

added ! @abhi03ruchi

**Comment by akash70629** [comment]
@abhi03ruchi please review and merge it

**Comment by akash70629** [comment]
@sailaja-adapa  Please review and merge it . Please add level 3 label

**Comment by sailaja-adapa** [comment]
update branch and resolve conflicts @akash70629

**Pull request merged**
