### PR TITLE
#added trending section in the book recommendation section

### PR DESCRIPTION
**Pull request by nandani-goyal**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1840 

# Description

I have added a trending book section where i have added all the trending books .In it i have added images of 5 trending books and also a "Read Now" button which on being clicked takes the user to the book.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-06-19 170503
Screenshot 2024-06-19 170516
the hovering effect of the Read Now button is as follows:
Screenshot 2024-06-19 170542
when Read now button is clicked it takes the user to the following website:
Screenshot 2024-06-19 170605

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by nandani-goyal** [comment]
please add gssoc label to my pull request so that my contribution can be considered under gssoc'24.please

**Comment by nandani-goyal** [comment]
please add gssoc label to my pull request so that my contribution can be considered under gssoc'24.please

**Comment by nandani-goyal** [comment]
I will be highly grateful if u add the "gssoc" tag to my pull request so that i can get my scores increased in the leaderboard and my contribution comes under gssoc'24.

**Comment by nandani-goyal** [comment]
please @huamanraj add gssoc label to this pull request please.

**Comment by nandani-goyal** [comment]
please @huamanraj add gssoc label to this pull request please

**Comment by nandani-goyal** [comment]
@RitiChandak please add gssoc label to this pull request so that I can get my scores and my contribution can be considered under gssoc24

**Comment by huamanraj** [comment]
> please @huamanraj add gssoc label to this pull request please

sorry @nandani-goyal ! in hurry i did the mistake and thanks for reminding me this much! really sorry for my mistake!

**Pull request merged**
