### PR TITLE
Enhanced Footer Design for Homepage with New Quick Links and Newsletter Subscription

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #4853

# Description

This pull request introduces an enhanced footer on the homepage, which includes:

- **Quick Links:** Added icons with labels for easy navigation to various sections such as Home, Benefits, Pricing, Contact, and more, improving accessibility and user experience.
- **Newsletter Subscription Section:** Added a subscription form for users to sign up for updates, with form validation and a responsive design for various screen sizes.
- **Google Translate Integration:** Integrated Google Translate widget to allow users to view content in their preferred language.
- **Back to Top Button:** Added a button to help users quickly return to the top of the page.

This footer update enhances the website’s overall usability and provides more intuitive access to important site sections.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

# BEFORE:

image

# AFTER:

image
image

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
Present one is fine @SrijaVuppala295

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , the present one is only not properly organised !! I have kept the ss from deployment link 

image

**Comment by sailaja-adapa** [comment]
Ohh is it? I merged one guy PR he did some changes on footer ok no problem will merge this

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , please add label to this pr #4340

**Comment by sailaja-adapa** [comment]
Can't add level to that since it is less change in lines of code @SrijaVuppala295

**Comment by sailaja-adapa** [comment]
According to guidelines we can't assign levels to less line is code which are 1 line or 2 lines

**Comment by SrijaVuppala295** [comment]
@sailaja-adapa , okay 👍

**Pull request merged**
