### PR TITLE
🛠️FIX : Unwanted page removed

### PR DESCRIPTION
**Pull request by akash70629**
# Related Issue

“None”

Fixes:  #4664 

# Description
Deleted Unwanted duplicate/old files .

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by akash70629** [comment]
@abhi03ruchi jaisa tumne kaha tha ki unwanted page delete karne ke liye , kar diya  jaha tak mujhe pata hai jo unwanted hai . Agar koi or bhi page delete karna hai to batana jo mujhse chut gya ho . Please level 2 label add kar do. 🥺

**Comment by abhi03ruchi** [comment]
https://swapreadsconnect.netlify.app/assets/html/comsp  yeh bhi

**Comment by akash70629** [comment]
> https://swapreadsconnect.netlify.app/assets/html/comsp yeh bhi

@abhi03ruchi Kar diya ! please level 2 label add kar do .🥺

**Comment by akash70629** [comment]
@abhi03ruchi  done !

**Pull request merged**
