### PR TITLE
Revert "Issue #231: Updated the logo and UI of scroll bar"

### PR DESCRIPTION
**Pull request by anuragverma108**
Reverts anuragverma108/SwapReads#509

### CODE REVIEW

**Comment by Madhuri36** [comment]
@anuragverma108 I am not understanding where is the problem because on my laptop it is working properly. Please help me out.

**Comment by anuragverma108** [comment]
@huamanraj Plz look into this. 
@Madhuri36 He is your mentor for this Project.

**Comment by huamanraj** [comment]
> @anuragverma108 I am not understanding where is the problem because on my laptop it is working properly. Please help me out.

first pull the code then push! maybe you have older codebase

**Comment by Madhuri36** [comment]
I did refresh the code and then only worked on it. @huamanraj

**Comment by Madhuri36** [comment]
I will try again and raise the PR @huamanraj . please let me know if it working.

**Pull request merged**
