### PR TITLE
🛠️ FIX : Wishlist Page added

### PR DESCRIPTION
**Pull request by akash70629**
# Related Issue

“None”

Fixes:  #4415

# Description

Added a wishlist page. It saves the user's wishlists and reflects them on the profile page.
# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/012be098-6503-4537-99f8-5f09f1ccfa29

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by akash70629** [comment]
@abhi03ruchi @abhi03ruchi please review it and merge it with gssoc , level 3 label

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi @abhi03ruchi please review it and merge it with gssoc , level 3 label

ok, enhance the UI so that it matches the theme of the website . for the backgrd add the backgrd design present in the home page . 

and add back to home button like button too , basically to navigate user out of the page.

**Comment by akash70629** [comment]
> > @abhi03ruchi @abhi03ruchi please review it and merge it with gssoc , level 3 label
> 
> ok, enhance the UI so that it matches the theme/ color combo (pink) of the website . for the backgrd add the backgrd design present in the home page .
> 
> and add back to home button like button too , basically to navigate user out of the page.

ok, wait ...I'm adding .

**Comment by akash70629** [comment]
> > @abhi03ruchi @abhi03ruchi please review it and merge it with gssoc , level 3 label
> 
> ok, enhance the UI so that it matches the theme/ color combo (pink) of the website . for the backgrd add the backgrd design present in the home page .
> 
> and add back to home button like button too , basically to navigate user out of the page.

## Done !! matched the UI theme , added home button .
image

**Comment by abhi03ruchi** [comment]
items that the user has added in wishlist are not displayed in my profile , similar case is with address  .

in the wishlist page , u can also add author and genre . like some people have fav authors , like roald dahl or agatha christe or  suspense books or romantic novels etc...

**Comment by abhi03ruchi** [comment]
u may work on these issues and raise pr .

**Comment by akash70629** [comment]
> items that the user has added in wishlist are not displayed in my profile , similar case is with address .
> 


wait !!! what !!! "Live website works !!! Why won't it work on your machine !!? If you're referring to displaying all wishlist items, note that the current code only shows the first two. Please clarify the problem . @abhi03ruchi

**Comment by akash70629** [comment]
> u may work on these issues and raise pr .

Sure 😊

**Pull request merged**
