### PR TITLE
added genre fairy tales

### PR DESCRIPTION
**Pull request by dfghjkbd**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.) #2515 

# Description
Added new genre Fairy Tales

# Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [X ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
before:
image
after:
image

# Checklist:

- [X ] I have made this change from my own.
- [X ] I have taken help from some online resources.
- [ X] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have made corresponding changes to the documentation.
- [ X] My changes generate no new warnings.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by huamanraj** [comment]
the change is too basic to get a level!

**Comment by dfghjkbd** [comment]
@huamanraj what changes you expect?

**Comment by huamanraj** [comment]
> @huamanraj what changes you expect?

i dont expect as gssoc guidelines there is no label for basic changes! the changes must be a feature update or a major bug resolve to get levels!

**Comment by dfghjkbd** [comment]
@huamanraj ok

**Pull request merged**
