### PR TITLE
icons added

### PR DESCRIPTION
**Pull request by abhi200446**
successfully added icons with hover effect with necessary HTML and CSS code 

https://github.com/user-attachments/assets/f2bb4b2b-9474-4351-a18a-0d66c4d70a87

 @sailaja-adapa please label gsscoc ext and hacktoberfest accepted

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
Work on another issue like removing unnecessary arrows

**Comment by sailaja-adapa** [comment]
Work on another issue like removing unnecessary arrows @abhi200446 

IMG_20241011_140029

**Comment by abhi200446** [comment]
@sailaja-adapa  thanks akka for giving idea i will work on it

**Comment by sailaja-adapa** [comment]
Welcome ☺️

**Pull request merged**
