### PR TITLE
Fix top10 page

### LINKED ISSUE #4470: BUG: Top 10 books of India not visible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Top 10 books of India not visible in the top 10 page because of the html breaking.
Screenshot 2024-11-02 213204
Screenshot 2024-11-02 213213

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

## fixes #4470

# Description
Brings back the "Top 10 books of India"

# issue #4470 

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-02 213929
Screenshot 2024-11-02 213947

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
ur changes arent visible in the deploy preview , chk once .

**Comment by haseebzaki-07** [comment]
https://github.com/user-attachments/assets/653deac4-31b9-4520-aff0-3b0e8cb69921

@abhi03ruchi I am able to see the changes in the deploy preview

**Comment by abhi03ruchi** [comment]
i didnt understand what have u done ? top 10 books are already there . u have 10 more books ? 

just add the heading below the navbar . everything else is fine .

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi for now the website only has the first ten books name "midnights children, the god of small things" but the other book section that is "top 10 books of India" is not visible due to the html breaking in the page what I fixed. I have only added closing tags and nothing else, The other ten books were already there on the code but not rendered on the site.
> 
> for now the production page looks like this:
> 
>  2024-11-02.23-42-11.mp4 
> and after fixing the page looks like the deploy preview video that I shared.

ok , only 10 books shd be there . remove the below 10 books ( books mentioned below the heading ) .

will merge the pr then .

**Comment by haseebzaki-07** [comment]
hey @abhi03ruchi removed the below books

**Pull request merged**
