### PR TITLE
Sovled the issue of profile features to be visible on Home page also

### PR DESCRIPTION
**Pull request by patilpratik1905**
Screenshot (1107)

Here you can the see the changes as this feature to open the content for user profile was not available before at home page which now is available and user don't have navigate to other pages for changes the user content

### CODE REVIEW

**Comment by patilpratik1905** [comment]
#3740 This is the issue which i created and have requested its solution to merge if you find it appropriate

**Comment by sailaja-adapa** [comment]
it was good but instead of sky blue colour add website colour theme @patilpratik1905

**Comment by patilpratik1905** [comment]
@sailaja-adapa Mam I tried few combinations, I want ur suggestion which suits the most according to ur requirements

Combination-1
Screenshot (1108)

Combination-2
Screenshot (1112)

Combination-3
Screenshot (1113)

**Comment by abhi03ruchi** [comment]
combo 3

**Pull request closed without merging**
