### PR TITLE
functional-login-page

### LINKED ISSUE #4510: BUG:The sign up page is redirecting to it's own , and not to the home page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login.sign-up page is not redirecting user to home page. when clicked to login-sign in button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by pinakviramgama**
Fixes #4510 

Dear @anuragverma108 , i have resolve issue number #4510 of directing user to login page correctly

image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @anuragverma108 , please approve this pull request.

**Comment by pinakviramgama** [comment]
Dear @anuragverma108 ,please approve this pull request

**Comment by atmajaa** [comment]
@pinakviramgama the navbar is not present in the login/signup page. Also, when I click on register it directs me to homepage

**Comment by abhi03ruchi** [comment]
we already have a login page . its UI is v good , but its not working . 

make that login page working via firebase backend . 

and in ur form google isnt working . 

Screenshot 2024-11-03 at 11 32 16 PM

**Comment by abhi03ruchi** [comment]
the issue u have created doesnt match with ur work .

**Pull request closed without merging**
