### PR TITLE
solved #4455 Added quiz page to top 10 books

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
solved #4455 Added quiz page to top 10 books
Fixes:  #4455 

https://github.com/user-attachments/assets/d4747171-66fa-43e8-8bdf-4c41abc2df43

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@sailaja-adapa mam please consider this as level3 if possible and kindly merge   it mam

**Comment by abhi03ruchi** [comment]
ur changes arent visbile in deploy preview .

**Comment by abhi03ruchi** [comment]
u can add the start quiz button ,(  like random tip button is placed in tips page )

no need to add start quiz on backside of the book cover . books are good .

**Comment by abhi03ruchi** [comment]
abhi u have added quiz only for midnight children?

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Yes mam

**Comment by abhi03ruchi** [comment]
add other quizzes in new pr .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
ok mam

**Pull request merged**
