### PR TITLE
Fix: #666 Updated Footer

### PR DESCRIPTION
**Pull request by Madhuri36**
# Description

I have updated the UI of the footer and also changed the colours of social media icons to match with the website's UI. @huamanraj please review this.
Fixes:  #666 

## Type of change

- [X ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X ] I have made this from my own
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Before:

image

After:
image

### CODE REVIEW

**Comment by huamanraj** [comment]
> # Description
> 
> I have updated the UI of the footer and also changed the colours of social media icons to match with the website's UI. @huamanraj please review this.
> Fixes:  #666 
> 
> 
> 
> ## Type of change
> 
> - [X ] Bug fix (non-breaking change which fixes an issue)
> - [ ] New feature (non-breaking change which adds functionality)
> - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> - [ ] This change requires a documentation update
> 
> # Checklist:
> 
> 
> - [X ] I have made this from my own
> - [X ] My code follows the style guidelines of this project
> - [X ] I have performed a self-review of my own code
> - [X ] I have commented my code, particularly in hard-to-understand areas
> - [X ] My changes generate no new warnings
> 
> 
> # ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
> 
> Before:
> 
> image
> 
> 
> After:
> image
> 
> 

is it mobile responsive?

**Comment by Madhuri36** [comment]
there is some problem i will raise the pr again @huamanraj

**Comment by Madhuri36** [comment]
@huamanraj please check it once.

**Comment by huamanraj** [comment]
> @huamanraj is there any issue? 
> image
> why is this check still not completed?

Let's wait for some time! we cant do anything about it 😁

**Pull request closed without merging**
