### PR TITLE
icon issue fixed

### PR DESCRIPTION
**Pull request by Sameeratweb**
Image display issues have been resolved
Before:
Screenshot 2024-10-06 104008

After:
Screenshot 2024-10-06 104016
 
I hope to merge it.

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@Sameeratweb resolve conflicts

**Comment by Sameeratweb** [comment]
i solved conflicts please check and let me know

**Comment by Sameeratweb** [comment]
Thanks for merging ! does my pr comes under Hactoberfest 2024?

**Comment by sailaja-adapa** [comment]
Yeah I added label now sorry for Inconvenience @Sameeratweb

**Pull request merged**
