### PR TITLE
Added autoscroable animated testimonial page

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
#4598 

 

Fixes:  #4598

https://github.com/user-attachments/assets/c7868563-4135-42f6-b117-31469c49fad9

 # can i get level 2 for it

 

# Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________
 

- [X ] I have made this change from my own.
- [ X] I have taken help from some online resources.
- [ X] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have made corresponding changes to the documentation.
- [ X] My changes generate no new warnings.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
dont create separate page for testimonial . 

keep it , at home page only . 
Screenshot 2024-11-05 at 5 34 32 PM

**Comment by atmajaa** [comment]
@Sawan-Kushwah any updates? Today is the last day to contribute!

**Comment by Sawan-Kushwah** [comment]
@atmajaa please merge this as it is , because if i put this testimonial in main page it will create a lot of conflicts , to put this conflicts aside i choose to add this tesimonial at new page !! 
this way code is modular you can add this testimonial anywhere else 
and no confilcts will be there

**Comment by atmajaa** [comment]
@Sawan-Kushwah we don't need a separate page for testimonials. Thank you for your efforts!

**Pull request closed without merging**
