### PR TITLE
enhacement in css #3564

### PR DESCRIPTION
**Pull request by Amankr200**
Fixes:  #3564

# Description
rate us css enhacement 

# Type of PR

 
- [x] Feature enhancement
 
 

# Checklist:
 

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by abhi03ruchi** [comment]
What enhancement in css of rate section have u done ? Plz explain ( add demo video ).  It looks the same as earlier . Submit button ?

**Comment by Amankr200** [comment]
I improved the CSS of the rate section by adding hover effects and a more visually appealing layout. The submit button now has a distinct style and animation for better user feedback.

**Comment by abhi03ruchi** [comment]
Ok . 
Screenshot 2024-10-16 at 9 39 28 PM

change the text color . 

After we click on submit button , the popup that appears doesnt look good . U can enhance that too .

**Comment by sailaja-adapa** [comment]
work with updated branch @Amankr200

**Pull request closed without merging**
