### PR TITLE
adding buttons in genre section of home page

### PR DESCRIPTION
**Pull request by Riyachauhan11**
# Related Issue
Working on #4549 

Fixes:  #4548 

# Description

Since different pages have been created for specific genre of books, I have removed the recommended books written in text (in genre section of home pg) and replaced them with buttons leading to pages consisting of diff genre of books. (works in both light and dark mode)

(I have repeated the same link for pages that dont exist currently but are wip)

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

before:
image

after:
image
image

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Riyachauhan11** [comment]
(working on it)

**Comment by abhi03ruchi** [comment]
there is some bug .  chk deploy preview .

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/0c3ded12-168d-4b2c-bc6f-9f267d3c28f3

**Comment by abhi03ruchi** [comment]
also classic literature page isnt linked .

**Comment by Riyachauhan11** [comment]
> also classic literature page isnt linked .
> 
> pages exist for all cards , link all of them correctly .

ill update em in this pr

**Comment by abhi03ruchi** [comment]
> > also classic literature page isnt linked .
> > pages exist for all cards , link all of them correctly .
> 
> ill update em in this pr

ok

**Comment by Riyachauhan11** [comment]
@abhi03ruchi should be good to go

**Pull request merged**
